FoundationDB/fdb-record-layer

docs/index.md
This adds a "-core" which was missing. This fixes #303.
=> Fixes #303: Broken URLs to Javadoc for core libraries

fdb-extensions/fdb-extensions.gradle, fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle, fdb-record-layer-core/fdb-record-layer-core.gradle, gradle/publishing.gradle
This adds the extra information needed in the pom.xml for maven central publishing that was not present before. Most of that is encapsulated in the gradle/publishing.gradle script plugin, but each subproject has its own description. That configuration remains only in the subprojects.
Note that this PR is against the 2.4.35 branch (in case we need to publish something from there). My plan was to submit a second PR against master once this one is in so that both branches can publish things. I have verified that the pom validation steps on the maven central uploader all pass with the pom generated from artifacts from this PR.
This fixes #305.
=> Fixes #305: Add the fields to the pom.xml needed for maven central publishing

docs/index.md
I added the link to the table of contents. I'm not sure what our rule of thumb is for what order the documents should be placed in. The release notes make more sense if you've read the part of the guide on semantic versions, so I put it right before the release notes, but there isn't really a lot of science in it, tbqh.
=> Fixes #322: Versioning guide missing from docs table of contents

fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle
This only "addresses" #328 rather than "resolves" it as this does not correctly merge the sources or fix the shaded paths. It does, however, generate non-empty sources and Javadoc jars for the shaded artifacts, which is good enough for some amount of work. In particular, I was able to verify that IntelliJ was able to use these Jars and give Javadocs and fill in parameter names, which is a good start. I think I would still prefer if it combined the Jars correctly, but this probably is good enough to get most people unstuck.
=> Address #328: Generate sources and javadoc jars for the shaded artifacts

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/ExpressionRef.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/PlannerExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/PlannerProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/SingleExpressionRef.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/properties/RecordTypesProperty.java
Prior to this change, writing properties as visitors was very tedious. Most properties can be expressed as a depth-one recursion, so augmenting the `visitLeave()` methods with the results of calling `visitLeave()` on its children (or members, in the case of references) makes properties easier
to read and write. This change also renames the visitor methods, changing `visitEnter()` to `shouldVisit()` and `visitLeave()` to `evaluateAtExpression()` and `evaluateAtRef()`, which also aids in
comprehension.
I discussed this change with @ScottDugas. I hope that the example property already in the code base (`RecordTypesProperty`) illustrates how this change is helpful.
=> Resolves #317: Make the PlannerProperty visitor more expressive.

docs/ReleaseNotes.md, fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle
This resovles #329 by tweaking how we choose things for the shaded jar. It includes the `fdb-extensions` subproject, which means that anything that was explicitly depending on both `fdb-record-layer-core-shaded` and `fdb-extensions` may get clashing jars. It should be the case that they can just remove the `fdb-extensions` dependency, but they should be aware that they need to do that.
The upshot is that guava is no longer a transitive dependency of the shaded plugin, which means that it is *actually* safe to upgrade the guava dependency without messing up anyone who depends on the shaded artifact, which wasn't actually the case before despite the fact that we were going through all of the trouble to shade guava, which seemed like a waste.
This includes the changes in #330. I did this …
=>  Resovles #329: Include fdb-extensions in shaded jars to avoid leaking guava

docs/ReleaseNotes.md
There was a problem where something that was supposed to push to the fdb-record-layer-2.3.32 branch on its "origin" remove actually pushed to a new branch named "origin/fdb-record-layer-2.3.32".  This gets that commit onto the right branch so that other things can be merged on top of it.
=> Merge faulty branch into fdb-record-layer-2.3.32

docs/GettingStarted.md
It looks like this was missing from the gradle config to get the source directory to be picked up at compile time. This also makes it possible to see the generated files from an IDE.
=> Resolves #342: Getting started guide should include information on setting source dirs

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java
Tests were showing an excessive number of read-only commits taking place.
This was due to the fact that the directory layer cache was accidentally
set to a size of zero by default, meaning that every request to look up
an entry required a new transaction.
As a side note: we could buy some efficiencies by doing the initial read
within the existing client transaction and only use a secondary transaction
in the case that the entry needs to be created. I think that this path wasn't
taken in the current code because it makes the semantics of passing a
context into the resolve() call a little confusing.
=> Fix #251:  Directory layer cache size was accidentally defaulted to zero

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/AsyncLoadingCache.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBReverseDirectoryCache.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ExtendedDirectoryLayer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpacePathImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpacePathWrapper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolver.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ResolverMappingDigest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ResolverMappingReplicator.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ScopedDirectoryLayer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/layers/interning/ScopedInterningLayer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/layers/interning/StringInterningLayer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/AsyncLoadingCacheTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBReverseDirectoryCacheTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpaceDirectoryTest.java
A lot of refactoring required:
- Resolvers now initialize a set of functions that produce the correct subspaces once they have access to a context from the database
- hash code of resolver should be computed in the constructor still, to do this use the `KeySpacePath` rather than the `Subspace` in the calculation
- Requires changes in `hashCode`/`equals` of `KeySpacePath` so that we can compare separate references by value
=> Resolves #261: Remove blocking calls from LocatableResolver constructors

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/AsyncPeekCallbackIterator.java, fdb-extensions/src/main/java/com/apple/foundationdb/async/WrappingAsyncPeekIterator.java, fdb-extensions/src/main/java/com/apple/foundationdb/map/BunchedMap.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ByteScanLimiter.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ExecuteProperties.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ExecuteState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/CursorLimitManager.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTypedRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/KeyValueCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SplitHelper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryPlanWithIndex.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/cursors/CursorLimitManagerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/KeyValueCursorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/FDBRecordStoreByteLimitTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/FDBRecordStoreLimitTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/FDBRecordStoreScanLimitTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/StoreTimerByteCounter.java
This adds a new limit ("the byte scan limit") that's broadly similar to the record scan limit but that counts the number of bytes being scanned instead of the number of key-value pairs. The semantics of the implementation are pretty weak because we can't in general know the number of bytes that a cursor will scan when it asks for permission to continue. However, the implemented limit should still provide some kind of protection against queries that scan a lot of big records.
The implementation itself is pretty straightforward. In reviewing, I think the most important question is whether the tests are strong and comprehensive enough for something that's pretty delicate.
=> Resolves #349: Add limit for number of bytes scanned by a cursor.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/BloomFilterCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/IntersectionCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/IntersectionCursorBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/IntersectionCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/IntersectionMultiCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/KeyedMergeCursorState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursorState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ProbableIntersectionCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ProbableIntersectionCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ProbableIntersectionCursorState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnionCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnionCursorBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnionCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnorderedUnionCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Text.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/TextScan.java, fdb-record-layer-core/src/main/proto/record_cursor.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ProbableIntersectionCursorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java
The work here is separated into three commits that are all related. In particular, each one depends on the next, though in theory, they all do separate things. I think it's easier to review each one separately, though I could be wrong.
This first is a "simple" refactoring of the intersection and union cursors so that their common code can be shared. In particular, I was upset that both cursors had essentially identical `CursorState` classes but one couldn't write functions that operated on either one of them (because Java doesn't support that type of polymorphism). This refactors their common code and I think is easier to manage (it was easier for me to make a new kind of cursor once this was done, at least), though there's kind of a fine line here between "good OO design" and "spaghetti …
=> Resolves #336: Add an unordered variant of the IntersectionCursor

docs/Overview.md
This uses a `Key.Expressions.field` in the sort instead of the erroneous `Query.field` and fixes the method name.
=> Fixes #369: Fix typo and type error in example query

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/proto/record_metadata_options.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataProtoTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStoreTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java, fdb-record-layer-core/src/test/proto/expression_tests.proto, fdb-record-layer-core/src/test/proto/test_records_1_evolved.proto, fdb-record-layer-core/src/test/proto/test_records_3.proto, fdb-record-layer-core/src/test/proto/test_records_import_flat.proto, fdb-record-layer-core/src/test/proto/test_records_marked_unmarked.proto, fdb-record-layer-core/src/test/proto/test_records_no_primary_key.proto, fdb-record-layer-core/src/test/proto/test_records_rank.proto, fdb-record-layer-core/src/test/proto/test_records_text.proto, fdb-record-layer-core/src/test/proto/test_records_two_unions.proto, fdb-record-layer-core/src/test/proto/test_records_union_default_name.proto, fdb-record-layer-core/src/test/proto/test_records_union_missing_record.proto, fdb-record-layer-core/src/test/proto/test_records_union_with_imported_nested.proto, fdb-record-layer-core/src/test/proto/test_records_union_with_nested.proto
(This supersedes #276 and applies Alec's comments)
Storing a record to a record store used to fail, if the record's meta-data was an evolved version of
the record store's meta-data shared using a meta-data store. This change should fix the issue by
passing the evolved meta-data to the builder.
Testing: ran FDBRecordStoreTest and RecordMetaDataBuilderTest
=> Resolves #3: Use evolved meta-data file descriptor to build meta-data

docs/ReleaseNotes.md
This removes the release note for the resolution of issue #3 from the template and places it in the 2.5.42.0 release notes.
=> Fixes #372: Release note was added to the template

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/KeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFilterPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryTypeFilterPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/PlannerRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/PlannerRuleSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/RewritePlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/expressions/LogicalSortExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/expressions/RelationalPlannerExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/CombineFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/FilterWithFieldWithComparisonRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/FilterWithScanRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/ImplementFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/ImplementTypeFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/PushTypeFilterBelowFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/RemoveRedundantTypeFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/SortToIndexRule.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/DualPlannerExtension.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/DualPlannerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCrossRecordQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreNullQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBReturnedRecordLimitQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSortQueryIndexSelectionTest.java
Adds a variety of rules for planning sorts as index scans. With some minor modifications, this also supports pushing down filters that can be satisfied by the same index to the index scan level using the methods in `ScanComparisons`. As a result, a sizeable number of our current planning tests now pass against the experimental planner. Also fix some bugs in the implementation of phasing in the `RewritePlanner`.
I took a major shortcut in implementing this by using the existing `KeyExpression.isPrefixKey()` method rather than writing one that can properly deal with `ExpressionRef`s that aren't `get()`-able (like groups). This is fine for now but we'll have to deal with it at some point (and it's pretty annoying).
Lastly, the `DualPlannerExtension` required some crazy hijinks to make it …
=> Resolves #56: Add rules for planning sort-only queries as index scans.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ExecuteProperties.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ScanProperties.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/ChainedCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpaceDirectory.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/cursors/ChainedCursorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpaceDirectoryTest.java
The `ChainedCursor` was relyig on any cursor that it was wrapping to enfoce
scan limit (that is, if it was even wrapping a cursor at all).  The problem
was that in almost any sane use case, the cursor that it would be wrapping
is going to be asked to read only signle row at a time (see
`KeySpaceDirectory.listAsync` for an example of this), and our cursors have
the policy that they will *always* be able to make some progress.  That is,
they will allways be able to advance one element, regardless of whether
our limits have been reached.  Due to this behavior, the `ChainedCursor`
would never actually stop.  Aditionally, even if it was not wrappping
a cursor that did reads, it would never obey the time limits.
This change promotes `ChainedCursor` up to a `BaseCursor` in that it will
now do …
=> Fixes #358: ChainedCursor does not obey byte/record/time scan limits

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java
Since `CommitCheck` is `STABLE`, it's kept around. I don't feel great about this, since it has a broken contract.
=> Fixes #357: FDBRecordStore.IndexUniquenessCheck.check needs to be async

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/TimeLimitedCursor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/cursors/TimeLimitedCursorTest.java
This makes it so that a `TimeLimitedCursor` first checks to see if the inner cursor has been exhausted before deciding on a `NoNextReason` for its child result. In particular, if the inner cursor's last result is an end continuation, the `TimeLimitedCursor` is itself exhausted and returns `RecordCursor.exhausted()` as its result. Otherwise, it returns an empty result with `TIME_LIMIT_REACHED` as the final result (as before).
I don't think the new `ScanTimeLimiter` has this same pathology as its mechanism for propagating up the scan limit reason is different. I haven't validated this though through experimentation.
=> Fixes #380: TimeLimitedCursor attempts to set a bad NO_NEXT_REASON if exhausted at timeout

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/planning/BooleanNormalizer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/planning/BooleanNormalizerTest.java
Currently, the `RecordQueryPlanner` tries to normalize Boolean predicates into disjunctive normal form. The DNF of some expressions can be exponentially larger than the given form; in the worst case, this can cause out-of-memory errors. This adds a limit to the Boolean normalizer so that it will not attempt to normalize expressions with a DNF size larger than the limit, using methods which determine the size of the DNF without computing it.
I think the main points of potential controversy here are:
- The size metric. I used the common definition of the size of a DNF (i.e., the number of terms in the disjunction). This is convenient because it's cheap to compute and differs from the total number of leafs in the expression tree by at most a factor of the number of literals.
- How the size …
=> Resolves #356: Add limit on the size of the DNF during normalization.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/AsyncLoadingCache.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/AsyncLoadingCacheTest.java
There was a possibility that an exceptionally completing future was added to the cache *after* it's async callback tried to invalidate it. This protects against this by first adding the future to the cache regardless of whether the result is exceptional or not and then adds the callback. This means that the callback gets added to some extra futures (in particular, it get's added to any future that was already in the cache), which is a little unfortunate. There are slightly more sophisticated ways around that that involve checking for done-ness from the future.
This was caught (intermittently) by an existing test, but I added an additional test to more reliably reproduce it.
=> Fixes #395: AsyncLoadingCache can cache exceptional futures

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/FormerIndex.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Index.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Key.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataValidator.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/RecordType.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/RecordTypeBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/TupleTypeUtil.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidatorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataValidatorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/TupleTypeUtilTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBTestBase.java
This creates a new method, `toTupleEquivalentValue`, which converts an object to a canonical form where types with identical `Tuple` serializations are assigned to Java objects where `.equals` and `.hashCode` work correctly. This method is then applied to record type keys and index subspace keys so that if the user assigns, say, the integer 42 to one index and the long 42 to another, meta-data validation fails.
This fixes #394.
=> Fixes #394: Meta-data validation should combine types with identical serialized forms when validating subspace keys

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/RecordTypeBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStoreTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java, fdb-record-layer-core/src/test/proto/test_records_1_evolved_again.proto
This change adds addIndex, dropIndex and updateRecords to FDBMetaDataStore.
Implementing addIndex and dropIndex is fairly straightforward. For updateRecords,
we decided to add the following two functionalities to RecordMetaDataBuilder:
- Add new record types and process extensions for them if user asks for it.
- Update the descriptors of the existing unionFields and record types.
=> Resolves #281: Add some convenience APIs to FDBMetaDataStore

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursorResult.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/AutoContinuingCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/ChainedCursor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/cursors/AutoContinuingCursorTest.java
- Implemented AutoContinuingCursor and AutoContinuingCursorTest
- Added a helper method noNextButHasContinuation in RecordCursorResult
- Fix doc in ChainedCursor
=> Resolves #397: Add AutoContinuingCursor to chain cursors across transactions

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java, fdb-record-layer-core/src/test/java-proto2/com/apple/foundationdb/record/ProtoVersionSupplier.java, fdb-record-layer-core/src/test/java-proto3/com/apple/foundationdb/record/ProtoVersionSupplier.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStoreTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreNullQueryTest.java
This creates a default extension registry that contains the extension options included in `record_metadata_options.proto`. Existing code that used an `FDBMetaDataStore` but did not set an extension registry will (a) in proto3, no longer throw a `NullPointerException` and (b) in proto2, process the `(record).usage` extension, which was not the case before.
For proto2, I think this leads to the following hypothetical situation: a user who had something like two message types defined, one called `RecordTypeUnion` and another called, say, `UnionDescriptor` where they had initially stored the meta-data using the `UnionDescriptor` message (using the `(record).usage = UNION` extension option) and then switched to using the `RecordTypeUnion` message without removing the old extension (and instead …
=> Resolves #352: Set a default extension registry within an FDBMetaDataStore

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Index.java, fdb-record-layer-core/src/main/proto/record_metadata.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStoreTest.java
(This PR has two commits, but I'm opening this PR specifically for the second commit. The first commit is already covered in PR #377. I'm stacking them, because this PR modifies a test introduced in PR #377. Feel free to just review this PR and discard the other one, if you think it's easier for you.  thanks)
This change adds support for using a counter as subspace keys to fulfill
the following two usecases:
- support existing clients, who will have some indexes in .proto and
some indexes via addIndex and will be using the index name as the
subspace key by default.
- support new clients, who will have some indexes in .proto and some
indexes via addIndex and should get small integer subspace keys
automatically.
Previously, index's subspace key was automatically set to the index
name, or …
=>  Resolves #11: assign index subspace keys based on a counter

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/CursorLimitManager.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/FDBRecordStoreByteLimitTest.java
The byte scan limit could return `BYTE_LIMIT_REACHED` without throwing an exception, even when the ExecuteProperties flag for throwing an exception on reaching a scan limit is set to `true`.
I added some tests to check for regressions. Because the byte scan limit would _sometimes_ throw exceptions before this change, they don't always fail without this change. However, there are enough of them that at least one of them usually fails without this change. Of course, they always pass with this change. :)
=> Fixes #421: byte limit doesn't reliably throw limit-reached exceptions.

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/Bindable.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/ExpressionRef.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/PlannerExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/RewritePlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/RewriteRuleCall.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/SingleExpressionRef.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/matchers/AllChildrenMatcher.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/matchers/AnyChildMatcher.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/matchers/ExpressionChildrenMatcher.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/matchers/ExpressionMatcher.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/matchers/ListChildrenMatcher.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/matchers/PlannerBindings.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/matchers/ReferenceMatcher.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/matchers/TypeMatcher.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/temp/matchers/ExpressionMatcherTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/temp/rules/CombineFilterRuleTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/temp/rules/FilterWithScanRuleTest.java
This is a pretty big rework of how planner rule matching works, based on writing a whole bunch of rules (some of which aren't out for review yet). The key things are:
1) It adds a new `ExpressionChildrenMatcher` interface that does the work of
applying some matchers to the children of a planner expression. The "default" `ListChildrenMatcher` implements the current behaviour of matching individual matchers to expression children. However, it's more flexible than that; see the `AllChildrenMatcher` and `AnyChildMatcher`.
2) Pushes more work (such as producing bindings) into the `ExpressionMatcher` and related cases while simplifying the `Bindable` interface. This seemed cleaner to me.
3) Makes most types related to matching, including PlannerBindings, immutable to sidestep
the tricky issue …
=> Resolves #419: Rework ExpressionMatchers for complex child matching.

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/QueryPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIntersectionPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnionPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnionPlanBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/FDBRecordStoreScanLimitTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java
The new interface, `QueryPlan`, has been added. It does not currently do anything except serve as a parent interface to `RecordQueryPlan`. Note that there are no new methods added to the `RecordQueryPlan` interface that do not have default implementations, so this is not a breaking change.
I have the beginnings of an `IndexScanPlan` locally. I considered getting that out prior to this change, but I figured I would ask for a look at this interface first. The most questionable thing (I think) is the `getQueryPlanChildren` method, which is designed to allow the implementor to return information about their children in a way that allows the `RecordQueryPlan` interface to implement it with a default method. But the drawback is this requires returning a wildcard in the return type.
I also …
=> Resolves #364: Add a generic QueryPlan that can return things other than records

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/DirectoryLayerDirectory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ExtendedDirectoryLayer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpace.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpaceDirectory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpacePath.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpacePathImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpacePathWrapper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolver.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ResolvedKeySpacePath.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ScopedDirectoryLayer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/layers/interning/ScopedInterningLayer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBReverseDirectoryCacheTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/DirectoryLayerToInterningLayerReplicaTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ExtendedDirectoryLayerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/InterningLayerToExtendedDirectoryLayerReplicaTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/InterningLayerToInterningLayerReplicaTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpaceDirectoryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolverTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ResolverCreateHooksTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ResolverMappingDigestTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ResolverMappingReplicatorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ScopedDirectoryLayerTest.java
.This change ended up being larger than expected:
- New `ResolvedKeySpacePath` represents a path that has been resolved against
a specific database. It can be turned into a `Tuple` or `Subspace` without
blocking and when logged will log details about the value to which a path
element has been resolved against the database.
- Added `KeySpace.resolveFromKey` to turn a `Tuple` back into a `ResolvedKeySpacePath`
and deprecated the old `KeySpace.pathFromKey`.  Additionally, deprecated the methods
a `KeySpacePath` that used to return additional information about the tuple that
was resolved (e.g.  `hasStoredValue()` and `getStoredValue()`).
- Changed all of the "list" methods to new versions that returned `ResolvedKeySpacePath`.
This means deprecating all of the old list methods and add new …
=> Resolves #402: Add ResolvedKeySpacePath to represent path resolved against a database

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java
There is now an option to log after every successful build of a range, optionally limiting to once every N milliseconds.
=> Resolves #429: OnlineIndexer should log successful progress

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SizeStatisticsCollector.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SubspaceProvider.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SubspaceProviderByKeySpacePath.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SubspaceProviderBySubspace.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpacePath.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpacePathImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpacePathWrapper.java
Removes requirement for FDBRecordContext and instantiation time. Instead methods for retrieving a subspace require an FDBRecordContext to be passed. toString also accepts and FDBRecordContext so that the logging string shows correspondences between logical and resolved names (in the case where the SubspaceProvider is based on a KeySpacePath). Needless to say this is a breaking change for the SubspaceProvider interface.
=> Resolves #338 and #386.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ProbableIntersectionCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnorderedUnionCursor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/FDBRecordStoreLimitTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/FDBRecordStoreScanLimitTest.java
The `UnorderedUnionCursor` now checks to see if things have been completed normally rather than if they are just done. In the exceptional case, this now results in the thing being eventually caught by the `whenAny` function and then propagated up to the user.
We should probably do a more thorough audit of uses of `isDone` within the code base, as a fairly easy way to lose exceptions is something like:
```java
if (myFuture.isDone()) {
return CompletableFuture.completedFuture(thing);
} else {
return myFuture.thenApply(ignore -> thing);
}
```
This was slightly more sophisticated than that, but it's of a similar idea. I also wanted to get this fix out first before doing a more thorough audit in the name of getting things done.
This fixes #437.
=> Fixes #437: UnorderedUnionCursors can loop if there are exceptional children

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
Also, OnlineIndexerTest.run wasn't actually joining, so none of the test code was actually run.
Fixes #436
=> Use ContextRestoringExecutor for FDBDatabaseRunner

examples/src/main/java/com/apple/foundationdb/record/sample/Main.java
Instead of fixing to be `COUNT_NOT_NULL(customer_id) GROUP BY preference_tag`, as #337 does, make it `COUNT(*)`.
The other fix in that PR was handled by #415.
Note that this is against the 2.6 branch.
=> Fix the sample program:

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/MetaDataCache.java
It is now marked EXPERIMENTAL, which I think more accurately reflects the state of that API. In theory, it should actually be UNSTABLE. I think it would also be reasonable to bump it "up" to UNSTABLE once #280 has been completed.
Note that this is against the 2.6 branch rather than master.
=> Resolves #447: Decrease the stability of MetaDataCache

build/Dockerfile.build, build/Dockerfile.fdbserver, build/docker-compose.yaml, docs/ReleaseNotes.md, fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java, fdb-extensions/src/test/java/com/apple/foundationdb/async/RankedSetTest.java, fdb-extensions/src/test/java/com/apple/foundationdb/map/BunchedMapScanTest.java, fdb-extensions/src/test/java/com/apple/foundationdb/map/BunchedMapTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, gradle.properties
In addition to updating the dependency, this also updates the API version. There were not any differences between API versions 520 and 600, but this enforces that clients only versions 6.0 and newer.
This resolves #313.
=> Resolves #313: Update fdb-java to 6.0.15

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
This introduces a new setting on the OnlineIndexer to increase
the limit of records to process in a single transaction after
some successes.
Also, added some javadoc for the two different types of retries.
Resolves #444
=> OnlineIndexer can increase limit after successful range builds

docs/ReleaseNotes.md
It looks like the release notes for that release were placed in the `template` section rather than the `next_release` section. This puts them in the right place
=> Fix 2.5.50.0 release notes

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java
This resolves #474. This is to eventually allow us to remove the method entirely (see #473).
=> Resolves #474: Mark OnlineIndexer::asyncToSync as INTERNAL

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordVersion.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoredRecord.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoredRecordBuilder.java
Note that this is against the 2.6 branch.
Although there were TODO comments about this, the methods being removed weren't annotated in any particular way. So perhaps there should be a gentler multi-stage removal.
Also includes a fix for #476. Some version tests were failing pretty reliably with this branch.
=> Resolves #461: Remove per-record time-to-load

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/KeyValueLogMessage.java
Instead of stripping out single quote, replace double quote with a
single quote.
=> Fixes #472 KeyValueLogMessage sanitizes `'` but quotes with `"`

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/MetaDataProtoEditor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStoreTest.java
This change adds more convenience methods to the FDBMetaDataStore class.
These are mostly methods that require manipulating the proto message itself.
=> Resolves #376: Add more convenience methods to FDBMetaDataStore

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
Resolves #479
This could be a little cleaner if I was willing to change the api
There are also a handful of edge cases that could cause the value to
be off, but it's not worth introducing the kind of checks that would
prevent this being off.
extracted OnlineIndexerTest.setupRunAsync
=> OnlineIndexer progress log includes record counts

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java
This invalidates the cache after the old record has been loaded but prior to when the new record is about to be written. This means that subsequent readers will then see the written value grâce à the RYW cache. There remains a few edge cases related doing things like, say, concurrently modifying a record while reading it. This does not make that problem worse, though, so maybe a more thorough discussion as to what needs to happen is required.
This fixes #494.
=> Fixes #494: Preload cache is not invalidated after a record write

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/MessageBuilderRecordSerializer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTypedRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexMaintainer.java
This resolves #490 by adding documentation on the limits of the `FDBRecordStore`. This also attempts to resolve #492, and it looks better locally, but I kind of would have expected more changes.
As this is a documentation-only change, I didn't update the release notes.
=>  Resolves #490: Document unsafety of opening multiple record stores on the same data in a single transaction

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java
This adds an optional limit on the number of suppressed exceptions that can be added to a given exception. After the limit is reached, we start incrementing a special exception which holds a counter of the number of ignored exceptions that we were supposed to suppress.
The semantics of changing the limit are a bit odd. I didn't want to deal with exceptions that have a different limit, so I ended up permitting a single change from the default (unlimited) value. I don't think that @alecgrieser especially likes this but I think it suffices for most use cases while keeping the suppression-adding code pretty simple.
=> Fixes #512: Put a limit on the number of suppressed exceptions.

docs/ReleaseNotes.md
This removes it from the template and puts it under the appropriate release.
=> Fix release note that was mistakenly added to the template

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/MetaDataProtoEditor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStoreTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java, fdb-record-layer-core/src/test/proto/test_no_union.proto, fdb-record-layer-core/src/test/proto/test_no_union_evolved.proto, fdb-record-layer-core/src/test/proto/test_no_union_evolved_illegal.proto, fdb-record-layer-core/src/test/proto/test_no_union_evolved_renamed_type.proto, fdb-record-layer-core/src/test/proto/test_records_implicit_usage.proto, fdb-record-layer-core/src/test/proto/test_records_implicit_usage_no_union.proto
[Please only review the top commit. I needed the other commit, which has a pending PR already, for testing this. I will merge / rebase later once that's in. Thanks]
This change adds a missing union descriptor to the record meta-data if FDBMetaDataStore is
used. The assumption is the following steps are involved:
- A .proto file is created that has some record types but doesn't have a union.
- The .proto file is saved using FDBMetaDataStore.saveRecordMetaData(). The missing union
is added using saveRecordMetaData before it saves the meta-data into the store.
- Users can continue adding record types to this meta-data, which will add a field to the
now-existing union.
=> Resolves #204: Add a default union descriptor to record meta-data

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/TracedTransaction.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBReverseDirectoryCacheTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolverTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ScopedDirectoryLayerTest.java
Use any provided MDC and restore when logging the leak warning.
Also clean up some tests that didn't close their context but weren't detected in previous runs because they have the wipes-FDB annotation and so don't run by default.
=> Resolves #529: TracedTransaction could give a little more context

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursorState.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ProbableIntersectionCursorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnorderedUnionCursorTest.java
This makes it so that `whenAny` only looks at cursors that might return a next value, so if the cursor has hit a limit, it is now excluded from the list of cursors to investigate. This actually can also cause an infinite loop if there is a cursor that hit a limit and another cursor who has not yet completed in which case it would spin loop waiting for that cursor to complete. Note that this could end up blocking the thread that asked for the future if the other future completed instantaneously.
Hopefully this will stop cursors becoming unstuck in time.
This fixes #526.
=> Fixes #526: ProbableIntersection and UnorderedUnion cursors can become stuck if one child completes with a limit and another an error

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursorState.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ProbableIntersectionCursorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnorderedUnionCursorTest.java
In addition to fixing merge conflicts, this updates the release notes and also changes some `onNext().get()`s to `getNext()`s.
=> Merge 2.5.54.18 into master

fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java, fdb-extensions/src/main/java/com/apple/foundationdb/async/RangeSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/MapPipelinedCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java
Nothing major was found. There were a few instances where we were not using the cached `READY_TRUE` and `READY_FALSE` futures, so I fixed those. A few places, the error was generated, thrown, and then caught, so I instead made it check for normal completion so that propagating the error was a little cheaper. I did not touch the `MapPipelinedCursor` or `FlatMapPipelined` cursor (except for a few comments), though I tried to add tests to exercise some of the code paths that might encounter exceptions. Those were all either directly or later calling `.join()` on the future they were checking, so they should all report errors, though there may be ways to fix those up so that they do not need to throw. I started down that path, then I decided that it was probably better to avoid accidentally …
=> Resolves #441: Audit code for incorrect uses of CompletableFuture::isDone

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
loadRecordStoreStateAsync was static because it used to be called by
different versions of static open methods. However, it's no longer used
that way, and users should really call getRecordStoreState instead. This
change deprecates them and instead introduces a non-static version of
them.
=> Resolves #534: Deprecate static loadRecordStoreStateAsync methods

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ByteScanLimiter.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ExecuteProperties.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordScanLimiter.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/ExecutePropertiesTest.java
This adds getters for the additional limits to the `ExecuteProperties`.
=> Resolves #544: ExecuteProperties should expose the bytes- and record scan-limits

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/AsyncLoadingCache.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/AsyncLoadingCacheTest.java
The `AsyncLoadingCache` is now backed by a `Cache<K, V>` instead of a `Cache<K, CompletableFuture<V>>`, and if the value is not cached, then each caller creates their own future. This produces duplicate work, but it also creates more failure indepdendence (hopefully). The first future to complete is the one whose value is cached, and all completing futures get that value.
Some of the discussion related to this change also suggested removing the deadline. I elected to keep it (in the name of preserving semantics), but it is also now explicitly the case that the caller can provide a deadline of `Long.MAX_VALUE` to indicate that there should be no deadline imposed on the futures.
This resolves #538.
=> Resolves #538: AsyncLoadingCache should cache values instead of futures

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
This change removes the deprecated static methods that could potentially
cause confusion. As a side effect, some of the static methods were also
converted to non-static.
This is a preliminary step toward storing index meta-data in index
subspace key in proto format.
=> Resolves 559: Remove loadRecordStoreStateAsync static methods

docs/ReleaseNotes.md
This was intended to go into 2.7 rather than 2.6, but once it went in, I think it was a better call to just keep the breaking change in 2.6 rather than try and back it out (given how the change should be relatively low impact).
=> Document removal of `loadRecordStoreState` methods in the release notes

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/FilterCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ResolverMappingReplicator.java
This now feeds the executor in properly in a `FilterCursor`. I didn't add a test for this, because I'm not quite sure what the right way to test it is. In theory, one could imagine a test that, like, checked what thread it was in, but I don't know if we have anywhere else that does that. Though maybe doing more of that would be a good idea. I went ahead and looked for all instances of us calling `AsyncUtil.whileTrue(Supplier)` instead of `AsyncUtil.whileTrue(Supplier, Executor)`, and there was only one other instance (in a non-test setting), so I went and fixed that one, too.
This fixes #573.
=> Fixes #573: FilterCursors can shuffle off work to the wrong executor

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/BaseKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/KeyWithValueExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/QueryToKeyMatcher.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/KeyExpressionTest.java
Previously, the `KeyWithValueExpression` returned its whole key as the child, when it should have returned just the part from before the split point (i.e., what ends up in the key).
=> Fixes #455: Make KeyWithValueExpression.getChild() return just the key.

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ProbableIntersectionCursorTest.java
This was somewhat subtle, but there were some tests of the probable intersection cursor that relied on `AsyncUtil.whileTrue(Supplier)`. That will then run its tasks on the default FDB executor (instead of the default Record Layer executor or something like that). That executor, `FDB.DEFAULT_EXECUTOR`, requires the `FDB` class to be initialized, which because of reasons, is the thing that actually loads the native library. So if the native library is not present, then that class initialization fails.
The reason the `prb-sonar` task is passing is that this is only problematic in places where the native library is not installed. The `prb-sonar` task runs within an environment where the native library is present, but the server is not started. Running this test in a place with neither the …
=> Fixes #586: Several ProbableIntersectionCursor tests require FDB but are not marked as such

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java
This adds back a line that was accidentally removed that stopped the `last_update_time` from being updated. It also adds a test to protect against regressions.
This fixes #593.
=> Fixes #593: Update to last_update_time in check version was removed

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
This removes a method that was marked `INTERNAL` in 2.6. We even noted in the Javadoc that this was slated for removal in 2.7, so this is just destiny fulfilled.
This resolves #473. Note that this is against the 2.7 branch.
=> Resolves #473: Remove OnlineIndexer::asyncToSync

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java
The index state space is now excluded from `deleteAllRecords`. This means that the index state information is preserved after all records are deleted. The issue, #399, mentioned that in theory, this was the "right" thing to do for write-only indexes (under the assumption that they are write only just because no one has finished building them, and now that the store is empty, there isn't need to keep them write-only). I decided to keep it simple in this fix and have it just preserve all index states, which is easier to reason about.
@amouehsan, IIRC, I was under that impression that some of the index meta-data changes (in #520?) will end up using a different subspace or something within the Record Store keyspace. I think you'll also need to update this to also exclude that region if I …
=> Fixes #399: FDBRecordStore.deleteAllRecords enables disabled indexes

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBLocalityProvider.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBLocalityUtil.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/MockedLocalityUtil.java
This change adds an interface for the locality API and implements one class that uses FDB's
LocalityUtil and one that fakes locality API by creating random boundaries. The interface is hooked
to FDBDatabase/FDBDatabaseFactory with a default that uses FDB LocalityUtil.
=> Resolves #504: Introduce mocked locality API

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTestBase.java
This arranges the tests so that they all use the `PATH_OBJECTS` defined in one place so that none of them use a prefix of the usual path as their main path.
No release notes added as this is a test-only fix. This fixes #602.
=> Fixes #602: Several tests define potentially overlapping KeySpacePaths

build/update_release_notes.py, docs/ReleaseNotes.md
This moves the release notes template into the python script that updates it. I could see the argument that it should be moved into a different file, but this was faster.
=> Fixes #599: Decrease errors from updating the wrong release notes

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
- Pulled the logic of handling scan limits out of `runAsync`
- Added a separate method `buildAsync` to increase/decrease scan limits and update scanned records count.
=> Fixes #511: OnlineIndexer.buildEndpoints decreases the scan limits on conflicts

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/KeyValueCursor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/KeyValueCursorTest.java
- This fix adds some sanity checks to the KeyValueCursor.build().
- This change ensures that 'subspace' and 'context' are specified when this
method is invoked.
- This guarantees that no KeyValueCursors are instantiated without these two
properties being specified.
=> Fixes #418: Sanity checks in KeyValueCursor.build.

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerTest.java
This adds a new `signal` future that is fired only after the `handle` callback has been added, which I think plugs the gap I found.
I'm not sure I totally like it. I think this is what needs to be done if we don't want to weaken the test by just not checking the `handle` lambda's context.
=> Fixes #580: FDBDatabaseRunnerTest.testRestoreMdc is somewhat flaky

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunner.java
- 'FDBDatabaseRunner.handle' logs the following now:
- Retry count (tries).
- Maximum number of retries.
- Delay between successive retries.
=> Fixes #416: FDBDatabaseRunner logs retry details

build.gradle
This was fixed by telling Javadoc to assume that it was looking at Java 8 source...which it is.
No release notes as this only affects the build system and not the published artifacts. This fixes #616.
=> Fixes #616: Javadoc build on Java 11 fails complaining about modules

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RecordTypeKeyTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/VersionIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBAndQueryToIntersectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCollateQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCoveringIndexQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCrossRecordQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreIndexScanPreferenceTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRepeatedFieldQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRestrictedIndexQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBReturnedRecordLimitQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSortQueryIndexSelectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/match/PlanMatchers.java
- Added 'PlanMatchers.unbounded' thats returns
'Matcher<RecordQueryPlanWithComparisons>'.
- Using this overload in all instances where 'bounds(unbounded())' was used.
- Next commit will simplify 'PlanMatchers.nextScan' usage.
=> Fixes #628: Ergonomic improvements to Hamcrest matchers.

docs/ReleaseNotes.md
I forgot to do this when I made the branch. We should probably have a procedure for this to prevent this kind of tom foolery.
=> Create a section for 2.8 release notes

docs/ReleaseNotes.md, gradle.properties
This updates it to 3.9, which is the most recent release. According to the release notes of that dependency, this is the first version to support Java 11, so if we want the Record Layer to support Java 11, I think this is the version we want. (There were some fixes to the `SystemUtil.IS_JAVA_XX` thing for versions newer than 8, but we weren't using that feature anyway.)
Note that this is against the 2.8 branch instead of master. I think that this might be overkill, as it's not clear if there's anything so different between 3.9 and 3.1 in the dependency (based on its release notes), but I felt like it would be safer so that people who are pinned to a minor release (e.g., 2.7) don't see their dependencies change without notice.
This resolves #606.
=> Resolves #606: Update commons-lang3 version

build/Dockerfile.build, build/Dockerfile.fdbserver, build/docker-compose.yaml, docs/ReleaseNotes.md, fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java, fdb-extensions/src/test/java/com/apple/foundationdb/async/RankedSetTest.java, fdb-extensions/src/test/java/com/apple/foundationdb/map/BunchedMapScanTest.java, fdb-extensions/src/test/java/com/apple/foundationdb/map/BunchedMapTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/TracedTransaction.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpacePath.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpacePathImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/storestate/FDBRecordStoreStateCacheEntry.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/storestate/MetaDataVersionStampStoreStateCache.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/storestate/MetaDataVersionStampStoreStateCacheFactory.java, fdb-record-layer-core/src/main/proto/record_metadata.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/LeaderboardIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/storestate/FDBRecordStoreStateCacheTest.java, gradle.properties
This adds a new implementation of the `FDBRecordStoreStateCache` that caches by the meta-data version-stamp key made available in FDB 6.1. Actually using the new cache requires both setting the database to use the new cache as well as marking any record store whose state should be cached as "cacheable" in its store state.
As this feature requires 6.1, this PR also bumps the FDB version to 6.1 (in a separate commit: 10112f8). This resolves #551. Because the 6.1 client is not compatible with the 6.0 client, this is probably best conceived of as a breaking change.
It kind of seems like this could use more documentation somewhere. I updated the release notes to include the most basic usage, but a more worked out example somewhere might be good.
This resolves #537. Note that this is against …
=> Resolves #537: Invalidate store state caches using the meta-data version key in FDB 6.1

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/AndComponent.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIntersectionPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnionPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnionPlanBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnorderedPrimaryKeyDistinctPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnorderedUnionPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/PlannerRuleSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/expressions/LogicalDistinctExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/expressions/LogicalUnorderedUnionExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/expressions/RelationalPlannerExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/properties/CreatesDuplicatesProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/properties/RecordTypesProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/properties/package-info.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/ImplementDistinctRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/ImplementUnorderedUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/OrToUnorderedUnionRule.java, fdb-record-layer-core/src/test/java-proto2/com/apple/foundationdb/record/provider/foundationdb/MapsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/QueryPlanCursorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/FDBRecordStoreLimitTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRepeatedFieldQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/QueryPlanStructuralInstrumentationTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/planning/RecordQueryPlanEqualityTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/temp/matchers/ExpressionMatcherTest.java
This adds a new logical unordered union expression and then rules to create them from a filter and transform the rule into a union.
Because this rule is the first implemented rule (I think) that might create a plan with duplicates and our tests all eschew setting `removes_duplicates` to true, it also made sense to add a thing to remove duplicates with a primary key distinct plan within this work. This included as a separate commit.
This resolves #359, and this resolves #501.
=> Resolves #359: Plan OR predicates with an unordered union

fdb-extensions/src/main/java/com/apple/foundationdb/async/RankedSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboard.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardDirectory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardSaveSubDirectory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardScoreTrim.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardSubDirectory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardSubDirectoryOperation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardSubDirectoryResult.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/package-info.java, fdb-record-layer-core/src/main/proto/time_window_leaderboard.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/LeaderboardIndexTest.java
Mostly this consists of making the `isHighScoreFirst` asynchronous and based on group.
=> Resolves #636: It should be possible for different time-window leaderboard groups to have different orders

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTraceFormat.java
The `FDBTraceFormat` enum can be used to specify whether the trace logs should be emitted in XML or JSON format. It allows includes a "default" option that follows the system default. This means this change backwards compatible with anyone who has used the `FDB_NETWORK_OPTION_TRACE_FORMAT` environment variable to do the same thing. If both the environment variable and a (non-`DEFAULT`) log format are set through the new interface, the new interface wins.
It's somewhat difficult to write tests for this (and none are checked in), but I did verify locally that setting this option did, in fact, change the format of the log files produced, and I verified that setting it to `DEFAULT` did follow the format set in the `FDB_NETWORK_OPTION_TRACE_FORMAT` variable.
Note that this requires FDB 6.1, so …
=> Resolves #584: Expose trace log format option through FDBDatabaseFactory

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
RecordStoreState is used to keep the store header information and
index states. It is loaded and modified via multiple threads and hence needs to
be guarded against race conditions. This changes aims to do that by
wrapping the record store state in an AtomicReference.
=> Resolves #563: Wrap the RecordStoreState in an AtomicReference

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SplitHelper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/QueryRecordFunctionWithComparison.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryScoreForRankPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseTest.java
This adds a `joinNow` method to `FDBDatabase` and to `FDBRecordContext` (the latter just calling the former). It then piggy backs off of the behavior of the `BlockingInAsyncDetection` specified for the database to also determine the behavior for this new method. I then went through the code base and tried to identify places that might `join`. I think I got all of them where there was a convenient `FDBDatabase` or `FDBRecordContext` lying around, but that might not quite be all of them.
This resolves #641.
=> Resolves #641: Add a "get now" method to blocking in async detection

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/storestate/FDBRecordStoreStateCacheTest.java
This adds the `performNoOp` and its async variants to the `FDBDatabase` class. This also adds events and waits for that which can be instrumented.
The exact no-op thing that is done is to create a new transaction, set its read version, and then attempt to read it. That requires performing no I/O (as verified by trying to run against a fake cluster). It is also harder to test, but if one calls `stopNetwork`, this will catch the fact that the network thread is down. I have not been able to reproduce the network thread just being really, really slow, but alas.
This resolves #650.
=> Resolves #650: Create no-op operation to test network thread liveness/responsiveness

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Key.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/FieldKeyExpression.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/KeyExpressionTest.java
This reverts commit 85b09f13ebe3c5e9c70bb23cc824dda03ebc0111.
This is a temporary fix until all the issues with #647 can be worked through.
=> Revert "Fixes #626: NullStandin should be set in FieldKeyExpression::toProto"

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java
Remove the @Nullable parameter from the capture by taking getting something out of it outside the lambda.
I'm not quite sure why this doesn't happen in Jenkins. But it does locally every time.
=> Fixes #659: SpotBugs bug tickled by leaderboards.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSimpleJoinQueryTest.java
As described in #665, it is very easy to misuse and impossible to use with a continuation. It's not used in very many places, and most of the places where it's used are tests. This change also migrates all the Record Layer's internal uses of this method to the static forms instead.
=> Fixes #665: Deprecate non-static RecordCursor.flatMapPipelinedCursor().

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Key.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/FieldKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/FunctionKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/GroupingKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/KeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/KeyWithValueExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/NestingKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/SplitKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/ThenKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/KeyExpressionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreNullQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSortQueryIndexSelectionTest.java
Restores 85b09f13ebe3c5e9c70bb23cc824dda03ebc0111 and 9f6f5663a4e1484acadf2465badc420b59244d97 to get back to 7401456d855955ab7f439b5a47ea5ea550eda288.
Adds a comparison predicate on `KeyExpression` for the purpose of sort ordering, defaulting to `equals`.
Make the planner use this.
It might be better, as part of the new planner, to rethink how unique nulls are handled as part of the index definition so that key expression comparison could be simpler again.
Also address `planHash` as noted in https://github.com/FoundationDB/fdb-record-layer/pull/647#discussion_r303114366.
=>  Fixes #655: Planner's sort matching needs to understand null interpretation equivalence classes

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Key.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/FieldKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/FunctionKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/GroupingKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/KeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/KeyWithValueExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/NestingKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/SplitKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/ThenKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreNullQueryTest.java
This removes the `NullStandIn` checking in the `.equals` method from the `FieldKeyExpression`. It also removes it from that fields hash code methods, and it removes the `equivalentForSort` method from all key expressions, as it was only used to check for the `NullStandIn` anyway. It references #677 in a few places, which is the issue to move this into meta-data that is stored at the `RecordType` level, as having mixed values for different indexes does not really make sense.
This fixes #682.
=> Fixes #682: Remove NullStandIn checking from the equality check for fields

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexTypes.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexValidator.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/VersionKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutationIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutationIndexMaintainerFactory.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/VersionIndexTest.java
The new `MAX_EVER_VERSION` index type allows for expressions with a `VersionKeyExpression` within it to be tracked. It uses the same machinery as the `MAX_EVER` atomic mutation index, though there is some special casing needed to handle the fact that sometimes, one wants to use the `SET_VERSIONSTAMPED_VALUE` mutation, and sometimes, one wants to use the `BYTES_MAX` expression.
There are two other weird things about this index:
* It does not (at the moment) support read your writes insofar as asking for the max version from the index will not include incomplete versions from the same transaction. The version index also has this property, and the way to solve it is to introduce a new special kind of intersection cursor for scanning those two indexes that reads from the in-memory structure …
=> Resolves #670: Add a MAX_VERSION index type

docs/ReleaseNotes.md
Some headings were moved from &lt;h1/&gt; to &lt;h3/&gt; to match other headers.
This fixes #700.
=> Fixes #700: Some subheadings in our release notes are of the improper level

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBTestBase.java
This adds a "sanitization" step to `FDBRecordContext` before it will set the transaction identifier. If the identifier exceeds 100 characters, it will truncate or drop the string. This operates on the assumption that the ID here is less important to most users than actually executing the operation. I think this assumption is correct, especially as we are currently passing the ID through the MDC rather than as a proper argument. I could see an argument being made that if we exposed the ID as something more like "setTransactionID", then we would want that function to throw an error or something, but this seems like the proper couse of action in this case.
This fixes #705.
=> Fixes #705: Truncate transaction IDs to 100 characters

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextTest.java
This changes the previously private constant to public and adds a Javadoc description.
This resolves #721.
=> Resolves #721: Expose max transaction ID size in FDBRecordContext

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/RecordSerializer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/StoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankedSetIndexHelper.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimerTest.java
- Adds 'logKey()' to StoreTime interface.
- Implements interface for all implementations.
- Overloads for implementation constructors to provide shorter metric key for
logging.
- To exemplify usage, added short logging key to a single metric.
=> Fixes #723: Shorter metric keys for logging.

.idea/gradle.xml, docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/BaseRepeatedField.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/EmptyComparison.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Field.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/OneOfThem.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/OneOfThemText.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/OneOfThemWithComparison.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/OneOfThemWithComponent.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/expressions/QueryExpressionTest.java
This introduces a new boolean parameter to `oneOfThem` and everything else in that path.
Note that no changes are made to the planner, which does not care about the difference, since it only turns query component into index operations in cases as part of a filter expression without anything like `IS UNKNOWN` or `NOT`.
=> Fixes #725: OneOfThemWith{Component,} does not distinguish empty vs null

docs/ReleaseNotes.md
It looks like the release notes were forgotten when that release was cut. This adds a release note with what I think was the only new thing in that version.
=> Updated release notes for 2.6.57.0

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/BaseRepeatedField.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/NestedField.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/NotComponent.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/OneOfThemWithComponent.java
Noticed while fixing missing preservation of empty mode when do need a new one-of-them.
I could be convinced that this should be done somewhere else, but it does not seem like all much extra complexity.
=> Resolves #735: The InExtractor is making duplicates that can easily be avoided

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/CascadesPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/KeyExpressionComparisons.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/PlannerRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/PlannerRuleSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/CombineFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/FilterWithConjunctNestedToNestingContextRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/FilterWithNestedToNestingContextRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/FilterWithOneOfThemToNestingContextRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/FindIndexForComponentWithComparisonRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/FindPossibleIndexForAndComponentRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/FlattenNestedAndComponentRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/FullUnorderedExpressionToScanPlanRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/ImplementDistinctRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/ImplementFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/ImplementTypeFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/ImplementUnorderedUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/LogicalToPhysicalScanRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/OrToUnorderedUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/PushComponentWithComparisonIntoExistingScanRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/PushConjunctComponentWithComparisonIntoExistingScanRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/PushDistinctFilterBelowFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/PushTypeFilterBelowFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/RemoveNestedContextRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/RemoveRedundantTypeFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/SortToIndexRule.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCrossRecordQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRepeatedFieldQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/temp/rules/PushComponentWithComparisonIntoExistingScanRuleTest.java
This finishes up some relatively simple work left over from #716 by adding support for pushing `OneOfThemWithComparison` query components on (non-nested) repeated fields to appropriate index scans.
Commit ebba73d also removes the unused `MadeChanges` return type from the `onMatch()` method which was only used by the (removed) `RewritePlanner`.
Note that most of this code will be replaced with the new "view expression" abstraction soon, so it doesn't need to be reviewed too closely. However, I figured that it was easy enough to break out in a separate PR to keep the other one more focussed.
=> Resolves #745: Add support for OneOfThemWithComparison predicates.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
The configuration paremeters of online indexer used to be passed only in
the beggining of the index build. However, these parameters may change during
long builds and never be picked up by the indexer. This change provides
a way for the indexer to load the config parameters in the beginning of
every transaction.
=> Resolves 731: Reload online indexer's rebuild configuration parameters

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextTest.java
This creates a separate store timer metric for batch priority GRV requests. This switches batch GRV requests to use a totally separate metric in stead of (rather than in addition to) the GRV metric that is timed for regular GRV requests.
This was done by adding a new store timer event, and now batch priority read version requests are instrumented only using the new event. The alternative would be to have introduced _two_ new events, "batch" and "default" priority grv events (and perhaps also a "system immediate" priority grv event) and then all requests get instrumented with the current event and then also with the event specific for their priority. I went with the former rather than the latter as (1) I could see it being confusing to have two metrics for each read version request and (2) …
=> Resolves #752: Add a separate store timer events for batch priority GRV latency

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpression.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpressionTest.java
Previously, serializing certain `LiteralKeyExpression`s (of type`Long` or `byte[]`) would produce a Protobuf that, when deserialized, would not contain a value of a different type (`Float` or `ByteString`, respectively). This fixes #756 and adds some tests that should give us more confidence that the serialization is correct.
=> Fixes #756: Serialization of LiteralKeyExpression can be incorrect.

build.py, fdb-record-layer-spatial/fdb-record-layer-spatial.gradle
This adds publishing for the -pb3 jars for the ICU and spatial index subprojects. The spatial index stuff actually wasn't being published at all, so this fixes that as well.
This fixes #761.
=> Fixes #761: fdb-record-layer-icu-pb3 jar is not published

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTypedRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java
This adds additional methods to the FDBRecordStoreBase interface for add read and write conflicts on records by their primary key. This can be used by advanced users who need additional control over their conflicts for certain operations.
This resolves #767.
=> Resolves #767: Add methods for adding conflict ranges for records

build/Dockerfile.build, build/Dockerfile.fdbserver, build/docker-compose.yaml, docs/ReleaseNotes.md, fdb-extensions/src/test/java/com/apple/foundationdb/FDBTestBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/TracedTransaction.java, gradle.properties
This increases the required FDB client and server version to 6.2, and it updates our build infrastructure to use that newer version. The main feature that this will enable is it will allow us to use the new `getApproximateSize` feature in 6.2, but the work to use this in, say, index builds has not been done.
=> Resolves #702: Increase required FDB version to 6.2

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FunctionKeyIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBFilterCoalescingQueryTest.java
This makes an update to the old planner to support queries with two inequality comparisons on a single range. This extends the `AndWithThenPlanner` to also work on indexes that are actually on a single field, and then it uses that logic in `planAnd`. The alternative would be to duplicate the logic there, which seems wrong. In theory, more code could be condensed to the `AndWithThenPlanner` (which probably needs a new name).
I have some reservations that this might inadvertently change plans (other than the ones it is intended to change). Only one plan in our test suite changed, but that also required a little bit of delicate work on the old planner. As the new planner actually already handles this case correctly, an argument can be made that we do not want this change.
This fixes #765.
=> Fixes #765: Inequality comparisons are not coalesced on single field indexes

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/synchronizedsession/SynchronizedSession.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/synchronizedsession/SynchronizedSessionRunner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/SynchronizedSessionTest.java
~~This PR is depending on https://github.com/FoundationDB/fdb-record-layer/issues/727. I'll add tests after the depended PR is merged.~~
=> Resolves #748: Support forcefully releasing synchronized session locks and stopping ongoing online index builds

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SplitHelper.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java
This fixes a bug that was an interaction between how we store data and how we scan data. In particular, if there were two records with string or byte array fields as part of their primary key, then if the value of one record's primary key was a prefix of another's, and the first character (or byte) of the other record after the common prefix was a zero, then we would read data from the second record if we were asked to read just the first.
Some background: the tuple layer encodes strings (and byte arrays) by (1) appending a type code byte to the beginning (`\x01` for byte arrays and `\x02` for strings), (2) then writing out the contents of byte array or string (UTF-8 encoded) with any zero bytes (or null characters) replaced with the byte sequence `\x00\xff`, and then (3) the zero byte as …
=> Fixes #782: Lookups by primary key can leak into other records in certain circumstances

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
This moves logging the descriptor upon failed record deserialization from `DEBUG` to `TRACE`. This is to help clean up our `DEBUG` level logs.
This resolves #789.
=> Resolves #789: Remove descriptor from debug logs on failed deserialization

fdb-extensions/src/main/java/com/apple/foundationdb/async/RankedSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankedSetIndexHelper.java
Break out the various cases of per-level mutations in `add`, so that they can be individually instrumented.
=> Resolves #792: Could use better detailed metrics in RankedSet.add.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
Revert #794. See detailed explanation from https://github.com/FoundationDB/fdb-record-layer/issues/808.
=> Fixes #808: Potentially lost index entries if two metadata updates happen in different record stores over the same data in the same transaction

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/clientlog/KeySpaceCountTree.java
A regression introduced when `getObject` was made to throw instead of returning `null`.
=> Don't try to resolve a node without an object

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/FunctionKeyExpression.java
This should hopefully make it clearer when there has been a failure to initialize the function key expression registry.
This fixes #826.
=> Fixes #826: Lazily initialize function key expression registry

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/QueryPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryCoveringIndexPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFilterPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryInJoinPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIndexPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIntersectionPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryLoadByKeysPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryPlanWithChild.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryPlanWithChildren.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryScanPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryScoreForRankPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryTextIndexPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryTypeFilterPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnionPlanBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnorderedDistinctPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnorderedPrimaryKeyDistinctPlan.java, fdb-record-layer-spatial/src/main/java/com/apple/foundationdb/record/spatial/geophile/GeophileSpatialObjectQueryPlan.java
I considered making this have a default of `false` for everyone. But that seemed like it might be dangerous in general. So, as a compromise, I made plans _with children_ default this and other similar methods by passing on the each child. I could be convinced not to even do that, or of some more ambitious scheme for general predicate checking over children.
=> Resolves #823: Need a way to tell whether a QueryPlan has a RecordQueryLoadByKeysPlan

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/RankedSet.java, fdb-extensions/src/test/java/com/apple/foundationdb/async/RankedSetTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexOptions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexMaintainerFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankedSetHashFunctions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankedSetIndexHelper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/LeaderboardIndexTest.java
Introduces an index option for `RANK` and `TIME_WINDOW_LEADERBOARD` indexes that controls what hash function is used.
Note that while it is technically safe to change the hash function for existing data, this is not recommended, as it changes the distribution.
=> Resolves #828: RankedSet poorly split for non-random keys 

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ByteScanLimiter.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ByteScanLimiterFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ExecuteProperties.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ExecuteState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordScanLimiter.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordScanLimiterFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/ExecutePropertiesTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/cursors/CursorLimitManagerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/KeyValueCursorTest.java
This includes some efforts to still allow for the use of the
`NO_LIMITS` constant in fashion that should have little overhead
on execution performance.
=> Resolve #835: Expose bytes/records scanned through ExecuteState

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/IndexQueryabilityFilter.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/RecordQuery.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/MetaDataPlanContext.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRestrictedIndexQueryTest.java
Add a new field to `RecordQuery` that allows a user to specify a custom filtering function that determines whether an index should be considered by the planner. This replaces the previous hard-coded check for the value of `IndexOptions.ALLOWED_FOR_QUERY_OPTION`, which remains the default.
This change does not break backwards compatibility.
See #841 for more discussion of why we need this filter.
=> Resolves #841: Add a custom index queryability filter for planning.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/StoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimerTest.java
In addition to the current metrics we have on the number of bytes read, written, and deleted, this also adds aggregates for the number of keys read, written, and deleted (etc.). This can be useful as there are some pathologies that result from lots of small reads, so having something that tracks the number of distinct reads can be useful.
=> Resolves #839: Add aggregate counters for the number of reads and writes

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTransactionContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/synchronizedsession/SynchronizedSessionRunner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextTest.java
I, um, don't quite know how this blew up into ~700 lines added, but alas. The main goal of this change is to allow for the transaction timeout to be specified through the `FDBRecordContext`. In theory, one could always have called `ensureActive` and then set the option manually, but it seemed better to have a real way of doing this without needing to peek at internals.
This is broken into two commits:
1. The first refactors `FDBRecordContext` to take a `Config` object at creation. This is to ameliorate the fact that there was a growing number of essentially optional parameters into the object, so now those are hidden in an object. But that commit shouldn't make any functional changes *except* (because it simplified the implementation considerably), it is now the case that if you …
=> Resolves #848: Allow for setting the FDB transaction timeout on FDBRecordContexts

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/RankedSet.java, fdb-extensions/src/test/java/com/apple/foundationdb/async/RankedSetTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexOptions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexMaintainerFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankedSetIndexHelper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RankIndexTest.java
Note that this doesn't actually introduce a `RankedMultiset` class, because that was hard with the current `InstrumentedRankset` class. It would be possible by creating an interface and making that a wrapper instead of a subclass. But I'm not sure it's worth it.
This moves all the `Rankset` config options, including the recently added hash function, into a separate `Config` class so that the constructors don't continue to get out of hand. At some point (but not in this PR) some of them could presumably be deprecated.
=> Resolves #806: Rank index could have option for how to handle ties

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/clientlog/KeySpaceCountTree.java
These are generated as immediate children of the root with an IP address.
They really don't need to print anything other than that address.
=> Improve printing of key count prefix nodes.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBReverseDirectoryCache.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/DirectoryLayerDirectory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolver.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ExtendedDirectoryLayerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolverTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ResolverMappingDigestTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ScopedDirectoryLayerTest.java
This adds overloads to `LocatableResolver::resolve` that allow a transaction to be passed, and then the resolver uses that transaction's read version when performing reads from the directory layer. In the "usual case" (which should be when a new entry does not need to be created), this transaction won't be committed anyway, so the only loss in efficiency over using the transaction itself is some extra memory (and no extra network requests).
It would probably still be a good idea to do #853 (if we can figure out what we want to do about caching), but this is easier and gets us 99% of the benefit. That being said, there is more cognitive load needed to understand this API, which is perhaps a smell.
This resolves #864.
=> Resolves #864: KeySpacePath resolution should re-use the initiating transaction's read version

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
This configures the read of the index states as part of check version to read all the states using the `WANT_ALL` streaming mode. This should decrease the number of round trips to read all states. Note that we were already waiting for all results to come back anyway, so there is not the downside one sometimes get from using `WANT_ALL` where the time to first byte is lower.
This resolves #881.
=> Resolves #881: Index state reads should happen with a WANT_ALL streaming mode

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/map/BunchedMap.java, fdb-extensions/src/main/java/com/apple/foundationdb/map/BunchedMapIterator.java, fdb-extensions/src/main/java/com/apple/foundationdb/map/BunchedMapMultiIterator.java, fdb-extensions/src/test/java/com/apple/foundationdb/map/BunchedMapScanTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java
The problem here was that the reading and writing of keys from FDB happened far enough away from the store timer logic, etc., that the previous logic was not even trying to look within the BunchedMap. However, quite a few reads and writes could happen as a result of text indexing, so getting the right numbers is fairly important. Note that once #866 is in, this may matter less (as the total reads and writes for the transaction will be more accurate), but doing it this way allows it as well allows it to (1) include the sizes of deleted values and (2) correctly correlate those operations to index updates. For that reason, I think this has value even after that other issue is addressed.
The architecture of this change is as follows:
1. The `BunchedMap` class has some `instrumentX` methods …
=> Fixes #876: TextIndex does not instrument BunchedMap reads and writes

build.py, docs/ReleaseNotes.md, settings.gradle
This disables the build of the `fdb-record-layer-spatial` project until an actual fix to #884 can be achieved. This unblocks the builds of the other projects, though, which is good.
=> Address #884: Geospatial subproject build relies on external files which are no longer available

build.py, docs/ReleaseNotes.md, settings.gradle
This re-enables building and publishing the `fdb-record-layer-spatial` library by reverting #885. However, I think we should leave #884 open for now, as I think there is a desire to make the builds more resilient to these kinds of failures in the future, but there is no reason not to let them continue for now.
=> Revert #885: Re-enable fdb-record-layer-spatial builds

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java
PR #861 added a new transformation to the RecordQueryPlanner that attempts to transform an IN predicate into an equivalent OR of equality predicates when the planner determines that it cannot implement the IN predicate as an IN-join because of an incompatible sort order.
However, the equivalent OR predicate is too complex for the simple normalizer normalizeAndOr() if there are other predicates on the original filter. In this case, the predicates are not normalized and so the union planner is unable to produce the desired union plan.
This change adds a more sophisticated normalizer to handle this case.
=> Fixes #888: IN to OR transformation does not plan with other predicates.

docs/ReleaseNotes.md
This merge 2.8.110.29 into master. The substantive changes were already on master (or they should be), but this cleans up branch history.
=> Merge 2.8.110.29 into master

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerImpl.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolverTest.java
This modifies the behavior of `FDBDatabaseRunner`s so that they will not use the configured WeakReadSemantics on retry. This means that they should only use a cached read version at most once, so if they hit a conflict or if the transaction is too old, then on retry, they will get a chance to try again (rather than possibly using the same cached version). The issue mentions the `LocatableResolver`, which uses an `FDBDatabaseRunner` in a way that could expose this bug if the initiating transaction set the `WeakReadSemantics` to something non-trivial. This adds a test case to show that that issue that was seen through the `LocatableResolver` is also fixed.
Both of the new tests initially failed before the change to the non-testing code was made.
This fixes #905.
=> Fixes #905: LocatableResolver.runAsyncBorrowingReadVersion needs to be careful not to use cached read version on retry

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/QueryRecordFunction.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RankIndexTest.java
This looks like it was a real concurrency bug (one that can lead to the data being corrupt). Essentially, the ranked set does not allow concurrent updates to the same subspace in the same transaction. This is a known issue, and there are real ways to fix it (like implementing some kind of locking abstraction), but it is hard to get right in a way that also does not result in blocking in async threads. The patch here fixes the text index maintainer so that it issues its updates to the same subspace serially, though it can still update unrelated subspaces in parallel.
This fixes #482.
=> Fixes #482: Test failure in RankIndexTest::repeatedRankQuery

.idea/compiler.xml, .idea/misc.xml, build.gradle, build/Dockerfile.build, build/docker-compose.yaml, docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/BlockingInAsyncDetection.java
This updates the JDK version we're using in our build docker, and increases the required JDK version for building the project to 11. AFAIK, there was only one thing we wanted in the build from JDK 11 that didn't require source changes, and it was related to Javadoc links. As a result, this resolves #910 (updating the Java version), and it resolves #325 (fixing some links).
=> Resolves #910: Take build Docker Java version to 11

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedReadTransaction.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedTransaction.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseTest.java
This change allows `FDBDatabaseFactory` to be configured with a supplier which
can decide whether or not assertions are to be enabled within the record layer
API.  This supplier is polled each time an `FDBRecordContext` is created and,
thus, all operations from the context will have assertions checked (or not)
as it is used.  The initial set of assertions are around validating key and
value byte sizes.
=> Resolves #925: Add assertions into record layer

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java
This allows a record store to be opened in `ERROR_IF_NO_INFO_AND_HAS_RECORDS_OR_INDEXES` if the only data it finds is in the `INDEX_BUILD_SPACE`, which is used to hold data for the online indexer. The idea here is that those should be allowed because they contain data that is used by the index build and doesn't contain user data, which is the main place where corruption can happen if a store is opened without a store header.
Note that this is against the 2.8.118 patch branch. This fixes #941.
=> Fixes #941: Record store check for empty stores with system data could exclude the INDEX_BUILD_SPACE

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/clientlog/TupleKeyCountTree.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/clientlog/KeySpaceCountTree.java
Use the prefix's bytes as the unique child key.
=> Fixes #947: TupleKeyCountTree.addPrefixChild only ever adds one child

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/NoOpIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/VersionIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/TerribleIndexMaintainer.java
See background from https://github.com/FoundationDB/fdb-record-layer/issues/901
The main problem fixed by this PR is that: `FDBRecordStore.resolveUniquenessViolation` used to be relied on to delete the last uniqueness violation entry when delete the second last one. But this is not the only way the uniqueness violation is resolved. It doesn't cover the case that the violation is resolved when record is deleted organically. To resolve this problem, now it will delete the last entry as part of deleting records (See `removeUniquenessViolationsAsync`).
This change also tries to consolidate uniqueness logic at `StandardIndexMaintainer` level:
- `FDBRecordStore .addUniquenessCheck`  -> `StandardIndexMaintainer.checkUniqueness`
- `IndexMaintainer.updateUniquenessViolations` -> …
=> Fixes #901: False positive of uniqueness violations prevents building indexes

fdb-record-layer-core/fdb-record-layer-core.gradle, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/TestHelpers.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/SplitHelperTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java, fdb-record-layer-icu/gradle.properties, fdb-record-layer-spatial/gradle.properties, gradle.properties
This updates most of our dependencies to their most recent versions, just to stay current. We'll probably also want to increase the FDB server version to 6.2.19, but I haven't done that yet because it will conflict with #911 in kind of a weird way.
This resolves #900.
=> Resolves #900: Gradle dependency refresh

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SplitHelper.java
This adds more logging details to a variety of `SplitHelper` exceptions to aid debugging. It tries to specify the subspace and key if it knows either.
Ideally, this would set the `key_path_path` based on the `SubspaceProvider`, but that seemed like a bigger change and that adding the keys, etc., would be useful on its own.
This resolves #932.
=> Resolves #932: SplitHelper exceptions should set more logging details

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SplitHelper.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/TestKeySpace.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/VersionIndexTest.java
This changes the local version cache to be keyed by `byte[]` rather than by `Tuple`. Then the exact key (in the database) is used to represent the cache entry rather than the record's primary key. This allows multiple stores to be opened in the same transaction and for them to interact with versioned records with the same primary key in each store without having cache entries from one store pollute the cache entries of the other.
This meant changing the API. The previous API was just wrong, in that there was absolutely no way to protect oneself from the bug identified in #952, so it has just been removed (despite the fact that this violates are claims of API stability). These APIs probably should have been marked `INTERNAL` anyway, but I believe they pre-date the API stability …
=> Fixes #952: Local version cache is keyed only by Tuple (i.e., primary key) not subspace

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursorResult.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/OrElseCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/synthetic/JoinedRecordPlan.java, fdb-record-layer-core/src/main/proto/record_cursor.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java
Use a new structured continuation object and protobuf serialization to record the complete state of the `OrElseCursor`, including which branch was chosen. Rewrite `OrElseCursor`'s logic in a simpler state-machine style, which makes it easy to resume the cursor before it has made a decision about which branch to take.
To avoid problems like we saw with the `FlatMapPipelinedCursor`'s continuations, deprecate the `RecordCursor.orElse()` fluent method and replace it with a static method that interprets the continuation.
Because this changes the continuation format, this is a breaking change.
=> Fixes #974: OrElseCursor doesn't properly support continuations.

docs/ReleaseNotes.md, fdb-record-layer-core/fdb-record-layer-core.gradle, gradle.properties
There is only one breaking change in Guava 29.0 that isn't in 28.2, the previous version, according to its release notes, and it has to do with GWT-RPC code: https://github.com/google/guava/releases/tag/v29.0 We don't use the guava-gwt code directly, so the only people who would be affected would be a consumer of this library who also uses guava-gwt.
No callouts in the proto3 versions since 2.6.0 for Java that I could find that suggest that upgrading to 3.12.2 wouldn't be a good idea. I had thought that this version might allow us to remove the `-PcoreNotStrict` stuff, as I thought I saw some chatter about deprecation warnings being fixed in some newer 3.x protoc versions, but it appears that it's still an issue. I think this is what we're hitting: …
=> Resolves #967: Upgrade guava and protobuf versions for 2.9

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/clientlog/TupleKeyCountTree.java, fdb-extensions/src/main/java/com/apple/foundationdb/tuple/TupleHelpers.java
Add a new TupleHelper that knows about the extra bytes.
=> Fixes #980: Event analysis is fooled by incomplete version stamps

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/QueryableKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/QueryKeyExpressionWithComparison.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/ScanComparisons.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/ScanComparisonsTest.java
The tricky part is threading through a provenance of the comparison operand for the range builder, in order to know whether it's really meant to be spread. Probably there is some type-system-like abstraction missing here. I'm open to suggestions that aren't significantly more disruptive than this is.
=> Resolves #997: Need QueryableKeyExpression with getColumnSize() > 1

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexFunctionHelper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/IntersectionCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/IntersectionCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/IntersectionMultiCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursorState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ProbableIntersectionCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ProbableIntersectionCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnionCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnionCursorBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnionCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnorderedUnionCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/ComposedBitmapIndexAggregate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/ComposedBitmapIndexContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/ComposedBitmapIndexCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/ComposedBitmapIndexQueryPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/package-info.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryCoveringIndexPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/explain/NodeInfo.java, fdb-record-layer-core/src/main/proto/record_cursor.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/BitmapValueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/match/ComposedBitmapIndexMatcher.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/match/PlanMatchers.java
Overall approach:
* Given a set of `BITMAP_VALUE` indexes differing in the finest grouping key.
* Given a query with:
- Equality conditions on the coarser grouping keys.
- A Boolean expression over conditions on the finest keys.
- Optional inequalities on the position value.
* Produce a plan that:
- Does covering index entry scans for each of the sub-conditions.
- Combines the streams of bitmaps from those scans using the bit-wise analogues of the Boolean operators among them.
- Filters out any bitmaps that end up empty (such as for `AND` with no shared positions within the position range of that bitmap) to cut down result size.
Questions for @normen662: 
* Is it correct for `ComposedBitmapIndexQueryPlan` to not have child plans or should `RecordQueryCoveringIndexPlan` really be …
=> Resolves #1012: BITMAP_VALUE index cursors can be bit-wise merged

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerConflictsTest.java
While setting endpoints for indexer, repeating conflicts with other transaction could prevent the job from running.
resolution: Since the store is marked WRITE_ONLY while determining endpoints and reading the records,
is seems safe to ignore conflicts caused by insertion of new records - as the inseration should already
imply valid index entries.
=> Resolves #1019: Avoid repeating index endpoints conflicts

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/GroupExpressionRef.java
This PR synchronizes mutations to the `HashSet` backing the `GroupExpressionRef`.
=> Resolves #1024: synchronize subsitutions to the group references

docs/ReleaseNotes.md
When 2.10 was cut, we didn't create a separate section for 2.10 in the release notes, so new releases of 2.10 were being catalogued in 2.9. This creates a new section to that end.
It also looks like 2.10.138.0 was missing a release note, so I fixed that up, too, while I was there.
=> Fix up 2.10 release notes

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java
This allows the client to enable run-loop profiling. The option was renamed in FDB 6.3 from "slow task profiling" to "run loop profiling". Anticipating this, I named the option based on what it will be called in FDB 6.3 even though this is using the FDB 6.2 Java bindings.
This resolves #1041.
=> Resolves #1041: Expose run loop profiling option

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ExecuteProperties.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/FDBRecordStoreScanLimitTest.java
The issue here is that in the code as it was originally, if the meta-data does not allow split records, then the time limit was enforced on the key value cursor. (If you had split records, then the time limit was removed on the very bottom key value cursor, and then only enforced in the wrapping cursor (the "key value unsplitter").) This meant that if you had versionstamps enabled, it was possible for the limiter to stop midway through, between a record and its version (if the time limit was hit at just the wrong time). Now, this removes the time limit from the key value cursor (always) and instead enforces that limit in the wrapping cursor so that it will always stop after reading a full record. This was already being done for the other kinds of limits, but not the time limit.
This fixes …
=> Fixes #1046: Setting a time limit can lead to "split record without start" error when reading data

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/IndexKeyValueToPartialRecord.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/ComposedBitmapIndexAggregate.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/BitmapValueIndexTest.java, fdb-record-layer-core/src/test/proto/test_records_bitmap.proto
* Don't pick a splice point in the middle of a nested concat.
* Allow for partial record with incomplete repeated field for special case of composed bitmap.
=> Resolves #1057: Composed bitmaps from map-like fields

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java
This happens when check version tries to `rebuildIndexWithNoRecord` but the index was not readable (probably related to reusing index name, also see #794 which was reverted)
There are two things need to be fixed:
1. In such situation it should mark the index to readable regardless
2. In any case, marking index as readable should not block the critical path (`checkVersion`), whose failure can people unable to do anything with the record store.
=> Fixes #1054: "make unbuilt index readable" exception blocks opening a record store

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexOptions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutationIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutationIndexMaintainerFactory.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java
This takes the approach suggested in the comment of making this an optional behavior defaulting to off, for the reasons stated there: it avoids incompatible changes and makes `SUM` and `COUNT` symmetrical.
=> Resolves #737: Count indexes should be cleared when decremented to zero

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexOptions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutationIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutationIndexMaintainerFactory.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java
Resolves #737: Count indexes should be cleared when decremented to zero (#1097)
This takes the approach suggested in the comment of making this an optional behavior defaulting to off, for the reasons stated there: it avoids incompatible changes and makes `SUM` and `COUNT` symmetrical.
=> Backport #1097 to 2.10.48 branch

.idea/compiler.xml
This regenerates the `.idea` configuration for the compiler. This was done by just importing the probject into the IDE and then letting it edit the file. This basically just sets the dependencies, etc., and a few language target things. We may have to regenerate this file again, but this should stop this change from being accidentally included in future PRs.
=> Resolves #1102: Regenerate .idea/compiler.xml

.idea/misc.xml
Changes the `.idea` configuration so that the default nullability annotation is the one that the project actually uses (at least currently). This should help developers out in using the right one.
This resolves #1103.
=> Resolves #1103: Configure default nullability annotations in .idea/misc.xml

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/ComposedBitmapIndexAggregate.java
The `planCoveringAggregateIndex` mini-planner doesn't need to have the same restrictions about repeated fields because they were taken care of when building the index and from the scan we will just reconstitute single-element lists for each unique value.
=> Resolves #1110: Covering aggregate scans and duplicates

docs/Building.md, docs/ReleaseNotes.md
"Building the Record Layer / Configuring IntelliJ" document is not updated with the last IntelliJ for a while, which made the new developers unable to build the project following the instructions. We need to find out the correct process and document it clearly to help developers onboard painlessly.
I've also updated `.idea/compiler.xml` to what I got after the process. 
Tip: it's easier to view the changes in rich diff
=> Fixes #1061: Fix the instruction document of building Record Layer

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/clientlog/DatabaseClientLogEvents.java, fdb-extensions/src/main/java/com/apple/foundationdb/clientlog/FDBClientLogEvents.java, fdb-extensions/src/main/java/com/apple/foundationdb/clientlog/VersionFromTimestamp.java, fdb-extensions/src/main/java/com/apple/foundationdb/system/SystemKeyspace.java, fdb-extensions/src/main/java/com/apple/foundationdb/system/package-info.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBSystemOperations.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBSystemOperationsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBTestBase.java
This creates a new set of constants for the system keys that we care about, and then it changes the instances
that were already referencing system keys, and then I added a new class, `FDBSystemOperations`, that allows
a user to use these features.
I'm not...super happy with this API, though. Unlike many operations, it wasn't sufficient to provide a context
for some of these operations, as you might need to set some extra options. But then to provide the user
a way to provide their own retry policies (and things like a timer, etc.), it felt like the least bad way
to pass that information, though we don't use a runner like this in other contexts.
This resolves #949.
=> Resolves #949: Useful system keys should be exposed through a more useful API

fdb-record-layer-lucene/README.md, fdb-record-layer-lucene/docs/index.md, fdb-record-layer-lucene/fdb-record-layer-lucene.gradle, fdb-record-layer-lucene/gradle.properties, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBLuceneFileReference.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/package-info.java, fdb-record-layer-lucene/src/main/javadoc/overview.html, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryBaseTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInputTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutputTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBLuceneFunctionalityTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBLuceneTestIndex.java, settings.gradle
_Why are we doing this?_
There is a desire for RecordLayer to be able to support FullTextSearch as a core capability.  There have been several attempts to do this in the open source community.  
_What is this?_
The Directory implementation is the abstraction in Lucene above the FileSystem.  This initial commit to full text search only focuses and tests this abstraction.  Forthcoming PRs, will add an IndexMaintainer and other pieces required to handle query processing.
**Implementation:**
An FDBDirectory is created to implement Lucene's Directory interface.  Data is stored into FDB using the following layout.
**Sequence Space** 
_{Directory Bytes}{indexspace}{key=s value={atomic integer}_
This first section stores the atomic integer to make sure temporary files prior to renaming are …
=> Resolve #1120: FDB Lucene Directory Implementation

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java
This restores the behavior prior to #1039. Plans with predicates over primary scans are again treated in a way that they again compete with plans with residual predicates over index scans. The configuration parameter
```
num IndexScanPreference {
/**
* Prefer a full scan over an index scan.
* A full scan does not have to separately fetch the record, but may return records of types that just
* need to be skipped.
*/
PREFER_SCAN,
/**
* Prefer index scan over full scan.
* An index scan always fetches the record separately but is less vulnerable to the addition of records
* of unrelated record types.
*/
PREFER_INDEX,
/**
* Prefer a scan using an index for <em>exactly</em> the primary key.
*/
PREFER_PRIMARY_KEY_INDEX
}
```
should be used as tie-breaker between these plans.
=> Resolves #1130: Adjust costing for primary scans

docs/ReleaseNotes.md
Looks like these two recent changes were missing release notes and/or their release notes were incomplete.
=> Fix release notes for 2.10.155.0 and 2.10.156.0

.gitignore, docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByIndex.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByRecords.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/main/proto/index_build.proto, fdb-record-layer-core/src/main/proto/index_metadata.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java
In the records store:
* an indexing type stamp will ensure that a continuation is only allowed for the same indexing type
* the rangeSet is now used to correlated indexing by index (similarly to indexing by records)
=> Resolve 1107:  Add persistent continuation to 'indexing by index'

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextTest.java, fdb-record-layer-core/src/test/proto/test_records_text.proto, fdb-record-layer-lucene/README.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/DirectoryCommitCheckAsync.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/IndexWriterCommitCheckAsync.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainerFactory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexScanTypes.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexTypes.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/package-info.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryBaseTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
Supports updates/deletes with cursor support (limit, skip, continuations).  
The LuceneIndexMaintainer provides core functionality for scanning Lucene Indexes backed by FoundationDB.
The core scan interface is the existing <a href="https://lucene.apache.org/core/7_7_3/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package.description"> Lucene Query Parser syntax</a>.
=> Resolve #1136: Implement Lucene IndexMaintainer and RecordCursor

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
- Transaction -> FDBRecordContext
- removing reads value from FDBDirectory 
- trivial fixes
Not addressed here: 
- Apply vs ApplyAsync
- tuple to Protobuf
=> fixes #1129: Address follow-up issues in Lucene Index implementation

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/AvailableFields.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCoveringIndexQueryTest.java
I'm not opposed to making these illegal at metadata validation time. But there were already tests that created such indexes, but they weren't ever candidates for covering queries.
=> Fixes #1139: Covering check when chosen index has duplicate fields

docs/ReleaseNotes.md, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/DualPlannerExtension.java
This still doesn't work to make navigating to the test in the IDE work. I don't know whether slightly different formatting could accomplish that.
=> Fixes #1150: @DualPlannerTest does not distinguish tests

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedFieldQueryTest.java
As noted in the comment, this is taking the same approach as one of the special cases that already existed.
Also note that the new planner already did this properly, though I'm not sure we want to wait.
=> Resolves 1140: RecordQueryPlanner.AndWithThenPlanner.planChild does not have a case like planAndWithNesting

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/VersionIndexTest.java
This adds a new `VersionstampSaveBehavior` setting, `IF_PRESENT`, which only saves a version with a record if the provided version is not `null`. This is useful for times when you want to, say, copy the data from one store to another precisely, so the default behavior, where creating a
a version if not set explicitly, isn't desired.
In doing this, I also filed #964 because the test I wrote seemed to expose this. It's possible this behavior is correct "enough", but I'm not super happy with #964 as it is right now.
This resolves #958.
=> Resolves #958: VersionstampSaveBehavior could have option to match version argument precisely

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexFunctionHelper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/QueryRecordFunction.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedFieldQueryTest.java
Since `RANK` as a function is a record operation today (as opposed to some kind of join), need a variant of the function that captures the selection of the nested map entry. This is done in two stages.
1. Allow `QueryRecordFunction` (what `Query.rank` produces) to have an additional `QueryComponent` constraint.
2. When that is asked to `eval` itself, match the component against one of the group keys in the function and turn the condition into values to select from among the (multiple) index entry tuples.
3. Use that selected tuple in place of `evaluateSingleton` (the normal non-repeated case).
=> Resolves #1183: Rank by grouped map-like values

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ExecuteState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/MutableRecordStoreState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordStoreState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/FormerIndex.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Index.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexTypes.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/StoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBIndexedRecord.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTransactionContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/InvalidIndexEntry.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ExtendedDirectoryLayer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolver.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/QueryToKeyMatcher.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIntersectionPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnionPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataProtoTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java
What remains:
* `RecordCursor`, `OrElseCursor` methods (#1189)
* `KeySpace`, `KeySpacePath`, `KeySpacePathImpl`, `KeySpacePathWrapper`, `ScopedDirectoryLayer`, `ScopedInterningLayer`, all around resolved / unresolved paths, which all present challenges in straightforward conversion.
* Override of `@Deprecated` methods from dependencies.
* Some meta-data items, that are deprecated in new code, but may still be present in serialized form and so need to be supported.
=> Resolves #1191: Remove non-controversial deprecated methods

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/OrElseCursor.java
This removes additional deprecated methods from the `RecordCursor` API. These methods should be fairly easy for the user to replace with their non-deprecated variants.
This resolves #1189.
=> Resolves #1189: Remove additional deprecated RecordCursor methods

build.gradle, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/IdentityBiMap.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/MatchInfo.java, gradle/check.gradle, gradle/codequality/spotbugs_exclude.xml
This is less straightforward than the previous branch, due to some incompatible changes. Hence the separate PR.
* The package of the task has changed.
* `excludes` and `sourceSets` are gone.
It is simpler to disable running against the `test` configuration with `spotbugsTest.enabled = false`.
Previously, Protobuf generated files were excluded in three ways:
1. `task.exclude`, which doesn't exist any more.
2. A filter on `task.classes`, which isn't really needed.
3. An `excludeFilter` file, which does everything we need.
The Protobuf exclusions are still needed because:
* `SE_BAD_FIELD`: `Class x defines non-transient non-serializable instance field unknownFields`
* `MS_SHOULD_BE_FINAL`: `PARSER isn't final but should be`
* `UCF_USELESS_CONTROL_FLOW`: `Useless control flow in …
=> Update Spotbugs Gradle plugin.

gradle/wrapper/gradle-wrapper.properties
I think this is the last of the dependency updates for 3.0.
=> Update Gradle itself to 6.8

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/QueryPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryCoveringIndexPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFetchFromPartialRecordPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFilterPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryInParameterJoinPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryInValuesJoinPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIndexPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIntersectionPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryPlanWithChild.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryPredicateFilterPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryScanPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryScoreForRankPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryTypeFilterPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnionPlanBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnorderedDistinctPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnorderedPrimaryKeyDistinctPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/properties/OrderingProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/RemoveSortRule.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBAndQueryToIntersectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedFieldQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSortQueryIndexSelectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryPlanFullySortedTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryPlanHashTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryPlanMaxCardinalityTest.java
Includes #1169 and thereby #1168, since if the planner doesn't use the full key it doesn't have a complete picture of how the index entries are ordered, so it may be simpler to only look at the third (last) commit.
It's possible that there is a more general / forward-looking way of exposing the determination than just as another field in the plan.
=> Resolves #1155: Need a way to tell whether the result of planning a query is only sorted by the requested keys.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBAndQueryToIntersectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedFieldQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSortQueryIndexSelectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryPlanHashTest.java
Fixes #5: Queries with order-preserving filter sorting by primary key will not use index for filter
It's possible that we should be more concerned about unanticipated effects of this change and should have some kind of control switch in the planner options to enable it. (It's never incorrect, but might expose previously hidden bugs.)
=> Resolves #1138: Planner's key from index should include primary keys

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBAndQueryToIntersectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedFieldQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSortQueryIndexSelectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryPlanHashTest.java
Includes #1168 because it was easier to come up with test cases after that change, so it may be simpler to only look at the second (last) commit.
=> Resolves #1154: RecordQueryPlanner.getKeyForMerge can build redundant merge keys

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlannerConfiguration.java
As per comment https://github.com/FoundationDB/fdb-record-layer/pull/1168#discussion_r596494885
It is never _incorrect_ to do this, but it may unexpected affect existing query tests and / or expose bugs in the old planner for which a quick workaround is needed.
=> Add a planner config option for whether to include primary key in value indexes.

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedFieldQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/match/FilterMatcherWithComponent.java
See new test case. Prior to this change, it generates an impossible index scan of all three conditions and no residual filter.
=> Fixes #1209: planNestedFieldChild stop condition isn't quite right

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreCountRecordsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreOpeningTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RecordTypeKeyTest.java
This updates the default value in the check version logic and also in the `UserVersionChecker`'s default implementation of `needRebuildIndex`. It leaves the old method around so that users can opt in to the old behavior by providing a `UserVersionChecker` with that old method around. Javadoc has been added in a few places to tell the user what the point of that method is and what the return value means, and also points them to those existing static utility methods that they can use within their implementations. The `OnlineIndexer` already had a default `IndexStatePrecondition` that was compatible with this change, so I mentioned in the release notes how one can change it if one is using the only incompatible `IndexStatePrecondition`. The other changes are to tests, usually to ones that …
=> Resolves #1213: New indexes should generally begin life as DISABLED instead of WRITE_ONLY if not READABLE

build.gradle, build.py, gradle/publishing.gradle
This adds the artifactory plugin and switches build.py to start using it. This is to try and make progress on #1248, though I don't necessarily think this is going to be the last PR for that, so I'm not marking this as resolving the issue (yet).
=> Adds artifactory publishing logic

build/docker-compose.yaml
We pipe through environment variables from CI to the build docker through the `docker-compose.yaml`. I think previous builds failed because it didn't have publishing configured correctly as a result of missing these environment variables.
Part of #1248.
=> Add missing environment variables to release build

build.gradle, build/docker-compose.yaml, fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle, gradle/publishing.gradle
This removes the bintray publishing logic in favor of the Artifactory publishing that was added in some previous PRs (namely #1249 and #1252). This is in anticipation of Bintray being ended on May 1, 2021.
This resolves #1248.
=> Resolves #1248: Switch from bintray to artifactory for artifact publishing

fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle
I think we published the wrong shadow jar to artifactory based on the file sizes. This switches the publication to the shadow jar, which hopefully is better.
This resolves #1248.
=> Resolves #1248: Switch from bintray to artifactory

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBReverseDirectoryCache.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolverTest.java
This adds a test that simulates a problem that was seen with the reverse directory cache. Essentially, if two transactions picked the same value for a name (with the same scoped), then we could fail that operation with a non-retriable error due to some checks that looked at an in-memory cache. The proposed fix here is to make the exception retriable. I added a test that simulates creating a bunch of entries all with the same transaction, and so probabilistically, some of them should allocate to the same value.
This fixes #1258.
=> Fixes #1258: FDBReverseDirectoryCache::putIfExists can throw if using a shared read version

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java
Introduce `RecordCursor::reduce` tests at the same time.
=> Fixes #1271: introduce a variant of reduce with a stop condition

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTypedRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedReadTransaction.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedTransaction.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreEstimateSizeTest.java
Exposes methods that use the new FDB 6.3 API for estimating the size of a range to estimate the size of a record store and of the records within.
=> Resolves #1229: Expose range size estimate on Record Stores

.idea/compiler.xml, docs/ReleaseNotes.md, gradle.properties
This reverts our `AutoService` dependency to 1.0-rc6, which was the previous version. At that version, the `AutoService` annotation is retained at `SOURCE` only, which means that it is not included in the generated `.class` files, so our downstream dependencies don't need to worry about what version of `AutoService` we're using or even that we're using `AutoService` at all (and are free to use their own version or an alternative mechanism for adding to the service registry entirely). However, with 1.0-rc7, the annotation became a `CLASS` retained object, which means that it would need to start being something our downstream dependencies would need to worry about. To avoid putting that onto our dependencies, this just reverts the upgrade. I'm not excited about us being stuck on this older …
=> Fixes #1281: AutoService missing from Record Layer runtime dependencies

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/QueryableKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/QueryKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/QueryKeyExpressionWithOneOfComparison.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/KeyExpressionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FunctionKeyIndexTest.java
A new `QueryKeyExpressionWithOneOfComparison` is available from `Query.function().oneOf()`. It is handled by the (old) planner like `QueryKeyExpressionComparison`, as `OneOfThemWithComparison` is to `FieldWithComparison`. Planning a `QueryableKeyExpression` is mostly just `equals` matching the index's key with the one inside the query predicate.
=> Resolves #1289: Multi-valued queryable functions

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextTest.java
This adds a configuration option to transactions that allows server request tracing to be enabled for that transaction. The ergonomics at the moment are a little bit weird, as if you set the option and provide a transaction identifier, then there's a single trace log message saying which random trace ID correlates with that transaction ID. However, individual sub-components of the transaction will have their own IDs (partially necessary to support many-to-one relationships between parents and children, which is required to accurately represent the effects of batching within FDB internals), so that only gets you so far. But this is what's required to make what is currently exposed work.
This resolves #1304.
=> Resolves #1304: Expose transaction option setServerRequestTracing in context config

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBQueriedRecord.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/ComposedBitmapIndexQueryPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/QueryResult.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/QueryResultElement.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryCoveringIndexPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFetchFromPartialRecordPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFilterPlanBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryInJoinPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIntersectionPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryLoadByKeysPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryPlanWithIndex.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryScanPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryScoreForRankPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryTypeFilterPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnionPlanBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnorderedDistinctPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUnorderedPrimaryKeyDistinctPlan.java
Resolve #1269: Allow data types other than FDBQueriedRecord to flow from plans and cursors.
1. Create new type (`QueryResult`) that contains a list of results for an execution of a query
2. Create new method (`executePlan`) that returns a `Cursor<QueryResult>` (instead of the existing `execute` that returns `Cursor<M extends Message>`)
3. Create backwards compatible `execute` method that uses `executePlan`
4. Convert existing implementations of `execute` to `executePlan`
=> Resolve #1269 Allow data types other than FDBQueriedRecord to flow from plans and cursors.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreOpeningTest.java
This allows library consumers to create a `UserVersionChecker` that inspects the size of the record store rather than the number of records, which may be useful for stores that don't have a record size index or for whom determing the record count is more work than should be done in a single transaction (see #7). It also makes getting the count or size lazy, and so if the `UserVersionChecker` can determine an index state without needing to read from the database (such as if the index is on new types), it can avoid having to do I/O entirely.
=> Resolves #1239: Use either record count or estimated size when determining IndexStatus in checkVersion

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryBaseTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
This adds some simple instrumentation to the FDBDirectory so that we have some metric visibility into how Lucene is handling operations w.r.t FDB.
=> Adding instrumentation to FDBDirectory

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java
1. Clear build data when index is marked readable
2. For existing record-stores, provide an API to clear this data for all readable indexes.
=> Resolve 1334: Provide a method to clean readable indexes build data

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Index.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexOptions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexValidator.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataValidator.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidatorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreReplaceIndexTest.java
This adds a new index option prefix, `replacedBy`. This then allows the user to use the prefix to specify one or more indexes, and when all of those indexes have been built, the index will be disabled and its data deleted. This allows the user to effectively drop an indexe, though only after when the index has been fully replaced by new indexes. This both allows older unused data to be protected while also protecting the user against removing the index before all of the queries that use it have been redirected to other indexes.
=> Resolves #1315: Allow indexes to be marked as replacing existing indexes

examples/examples.gradle, examples/src/main/java/com/apple/foundationdb/record/sample/Main.java
Addresses: https://github.com/FoundationDB/fdb-record-layer/issues/1347
Runs properly after indexing the DISABLED indices (not WRITE_ONLY ones):
````
2021-07-31 05:08:31,714 [INFO] c.a.f.r.s.Main - Clearing the Record Store ...
2021-07-31 05:08:32,661 [INFO] c.a.f.r.s.Main - Writing Vendor and Item record ...
2021-07-31 05:08:32,777 [INFO] c.a.f.r.p.f.FDBRecordStore - new record store format_version="7" key_space_path="/application:22->'record-layer-sample'/environment:'demo'" meta_data_version="2"
2021-07-31 05:08:32,978 [INFO] c.a.f.r.s.Main - Reading Vendor record with primary key 9375L ...
2021-07-31 05:08:33,008 [INFO] c.a.f.r.s.Main -     Result -> Id: 9375, Name: Acme
2021-07-31 05:08:33,009 [INFO] c.a.f.r.s.Main - Looking for item IDs with vendor ID 9375L ...
2021-07-31 …
```
=> Fix example code.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/CipherPool.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/MappedPool.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializerJCE.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SortedRecordSerializer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlannerConfiguration.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/sorting/RecordQueryPlannerSortConfiguration.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/sorting/RecordQuerySortAdapter.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/sorting/RecordQuerySortKey.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/sorting/RecordQuerySortPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/sorting/package-info.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/FileSortAdapter.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/FileSortCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/FileSortCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/FileSorter.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/MemorySortAdapter.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/MemorySortCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/MemorySortCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/MemorySorter.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/SortEvents.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/SortedFileReader.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/package-info.java, fdb-record-layer-core/src/main/proto/record_sorting.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/cursors/SortCursorTests.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSortQueryIndexSelectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/match/PlanMatchers.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/match/SortMatcher.java
Adds RecordCursor implementations that sort inputs and output in order: either just a few records in memory or spilling out to disk using files.
=> Resolves #1161: Prototype non-index sorting

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
The read pipeline for Lucene will always read the first (already cached) and the last block.  This PR attempts to cache that last block when germane during listAll (always called by directory in Lucene).
=> Resolve #1415: Caches the first and last block (checksum)

.idea/compiler.xml, .idea/misc.xml, build.gradle, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/Bindings.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/RecordTypeKeyComparison.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/AliasMap.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/ComparisonRange.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/Compensation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/Correlated.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/InterestingPropertiesMap.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/expressions/RelationalExpressionWithChildren.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/expressions/SelectExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/properties/OrderingProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/ImplementInUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/InComparisonToExplodeRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/RemoveSortRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/predicates/QueryPredicate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/predicates/ValueComparisonRangePredicate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/predicates/ValuePredicate.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRepeatedFieldQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSortQueryIndexSelectionTest.java
- `Comparison` now implements `Correlated<Comparison>`
- `ComparisonRange` now implements `Correlated<ComparisonRange`
- `ValuePredicate` and `ValueCoparisonRange.Sargable` both defer to the comparisons/comparison range's `rebase()` in their own `rebase()`.
- matching logic in `SelectExpression` can now match even if predicates declared multiple correlations
- `Compensation` logic was extended to also allow for complicated join-like `Compensation` trees including the compensation of join predicates (aka multi-correlated comparisons)
Note that all of this is necessary to allow `IN-to-UNION` an `IN-to-JOIN` to reason about order better and to allow us to generalize these rules to multiple in clauses and proper order property housekeeping.
=> resolves #1461: parameter comparisons should declare their correlations correctly

gradle.properties
This updates the version of log4j used by our tests and example code to 2.16.0, which removes the JNDI logic and thus patches the RCE vulnerability. As noted in the issue, the main library only exposes slf4j, so an adopter is only vulnerable if they are using the log4j logging implementation with a vulnerable version, but our own tests and example logic were technically vulnerable, though neither exposed remote endpoints.
This resolves #1494.
=> Resolves #1494: Update log4j version to avoid RCE vulnerability

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTypedRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexFunctionHelper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/ComposedBitmapIndexAggregate.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/IndexFunctionHelperTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/BitmapValueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRestrictedIndexQueryTest.java
For IndexFunctionHelper and ComposedBitmapIndexAggregate, this change
adds it as a required parameter.
Since FDBRecordStoreBase is MAINTAINED this adds overloads for:
- getSnapshotRecordCountForRecordType
- evaluateAggregateFunction
that take the IndexQueryabilityFilter, using TRUE to maintain
backwards compatibility. The old method is left as a default
method, requiring implementers to add the new method.
=> Resolves #1520: Expose IndexQueryabilityFilter for Aggregate planning

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/properties/RecordLayerPropertyKey.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTestBase.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexQueryPlan.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneScanProperties.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneQueryIntegrationTest.java
Callers will need to be updated to set the context property instead of passing it into the planner constructor.
Note how this changes the property system to allow null default (and therefore actual) values. If that's not desirable, another layer of object could be added.
=> Resolves #1518: Remove ExecutorService from LuceneScanProperties

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStorePerformanceTest.java, fdb-record-layer-core/src/test/resources/standalone.log4j.properties, gradle.properties
Add a separate test for index scan and deferred fetch. This is more or less identical now, but once index+record fetch is optimized should show
the difference.
=> Fix log4j config regressions in performance test.

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/AutoCompleteSuggesterCommitCheckAsync.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/DirectoryCommitCheckAsync.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/IndexWriterCommitCheckAsync.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteResultCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexKeyValueToPartialRecordUtils.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneLoggerInfoStream.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedAnalyzingInfixSuggester.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
This PR is to resolve these issues:
1, Use 1.0 as NoCFSRatio for Lucene segments merging policy, to make sure it always use compound file.
2, Configure a InforSteam to publish log messages to output teams to loggers.
3, Cache the suggester into ```FDBRecordContext``` similarly as the ```indexWriter``` for ordinary search, so it won't be closed until the commit of context. 
4, Fix the partial record build to skip a field if its value is ```null```.
=> A few bug fix and optimizations for Lucene search

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java
Let the functions scrubDanglingIndexEntries and scrubMissingIndexEntries return the count of bad items found instead of void
=> Index scrubber - return the count of bad entries found (#1547)

fdb-record-layer-spatial/fdb-record-layer-spatial.gradle
Change download location for geonames data so it is not subject to the unreliability of download.geonames.org
=> download geonames data from s3

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedIndexInput.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutputTest.java
This removes the calls to `CompletableFuture::join` from non-test code within the fdb-record-layer-lucene subproject and replaces them with calls to `FDBRecordContext::asyncToSync` over the future. This also made a few code improvements that I noticed while I was editing things:
1. There were a few remaining calls to `.thenApplyAsync`, which shuffles work onto the common fork join pool, and therefore doesn't work with the Record Layer threading model
1. The `readBlock` method could be pipelined better so that it didn't block on getting the file reference, but instead composed the file-reference future and the future to read the block
1. The parameteried `FDBLuceneQueryTest` tests were hiding their names
This fixes #1571.
=> Fixes #1571: Lucene subproject calls CompletableFuture::join

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
This restructures the way the `FDBDirectory` handles caching the file name to `FDBLuceneFileReference` map. Previously, there was a cache where entries were probably filled by a call to `listAll()` that would happen when the directory was opened anyway, but now, this keeps a full cache of file names and file reference information in memory for the directory. In theory, this could get too big if there are too many files, but the calling code relies on being able to list all files anyway, so at least for now, that's a problem either way. Note that the calling code sometimes makes multiple `listAll()` calls in the same request, and so this cache can speed up calls after the first one.
This also tweaks the way that the list is read from the database in that it uses the `WANT_ALL` streaming …
=> Resolves #1575: Lucene FDBDirectory could cache listAll results

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundReader.java
This allows the initial lookup for opening input (asynchronous) to occur concurrently with reading the entries (blocking).
=> Make LuceneOptimizedCompoundReader not block on reading entries prior to openingInput

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/ChooseK.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/temp/ChooseKTest.java
This Improves performance of chooseK algorithm by using integer counters for state management instead of Iterator heap objects.
This resolves https://github.com/FoundationDB/fdb-record-layer/issues/1590.
=> Improve performance of ChooseK algorithm

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/KeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/QueryToKeyMatcher.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/UnknownKeyExpression.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreDeleteWhereTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTestUtils.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/QueryToKeyMatcherTest.java
This adjusts the methods used by `canDeleteWhere` on indexes defined on a `GroupingKeyExpression` so that it tries to satisfy the query from the grouping sub key rather than the whole key to limit the number of accepted `deleteRecordsWhere` predicates to more closely align with that is actually possible to safely delete. This includes some regression tests that hit the error, as well as a small amount of refactoring that is to set up #1580.
This fixes #1583.
=> Fixes #1583: Indexes with groups erroneously accept deleteRecordsWhere queries on grouped columns

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java
This resolves the merge skew between #1564 and #1584 to unblock outstanding PRs, though it's possible we'll need a different approach if we want to fix the API-breakage.
This fixes #1598.
=> Fixes #1598: Build broken due to merge skew around EvaluationContext build

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/runners/ExponentialDelay.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/runners/package-info.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/runners/ExponentialDelayTest.java
This introduces a new class `ExponentialDelay` that manages a delay that backs off exponentially, along with a jitter.
This replaces two implementations of the same idea, one in `FDBDatabaseRunnerImpl` and one in `IndexingThrottle`.
This also, fixes #1565 by the fact that the new class does not have that bug, so using it in `FDBDatabaseRunnerImpl` will clean that up.
I also introduced a new `runners` package, for this, because I felt as though the root was getting too bloated. I did not move `FDBDatabaseRunnerImpl` to the new package, although that could be done (it is INTERNAL). Move `FDBDatabaseRunner` would be a breaking change.
=> New ExponentialDelay class, fixes #1565

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
This adds a new `AtomicLong` to the `FDBDirectory` where the file sequence counter is cached. The first time a user tries to get an increment, the value is loaded from the database and put into the cache. All subsequent accesses can use that cache, and the `AtomicLong` guarantees thread safety. Note that the FDB read-your-writes cache was already keeping a cached copy, but this removes the extra JNI hop and requirement to go through the FDB network thread in order to get a new increment.
This resolves #1577.
=> Resolves #1577: Lucene FDBDirectory should cache file counter

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundFormat.java
Adds a prefetch before sequentially loading references and data blocks during the merge process for creating Compound Segment Files.
=> LuceneOptimizedCompoundFormat: Fetch Initial References and Blocks in parallel vs. Sequentially #1621

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
This reduces the time for the merging of segments after commit by pipelining the writes.  On a local machine attempting to write 10K records and committing every 50 records, it reduced the total processing time ~ 20%.
=> Allow writes to pipeline compression in Lucene #1625

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneDocumentFromRecord.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneFunctionKeyExpression.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneFunctionKeyExpressionFactory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneFunctionNames.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexExpressions.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexKeyValueToPartialRecordUtils.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneScanParameters.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneScanQuery.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneScanQueryParameters.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneDocumentFromRecordTest.java
Still does not complete the covering optimization because of lack of appropriate `AvailableFields`.
Still does not do index joining because of the lack of appropriate `PlanOrderingKey`.
This should all that is needed for the Cascades planner to support those, though.
=> Some improvements to handling of Lucene stored fields and sorting

build.gradle
This removes the references to `jcenter()` from our gradle configuration. There was one dependency, one of the plugins, that didn't seem to have an up-to-date version on `mavenCentral()` (which was potentially why we were using `jcenter()` for anything), but they are now in the `gradlePluginsPortal()`, and so I switched those over to using the new gradle plugins format. The two remaining plugins did not seem to have entries in the `gradlePluginsPortal()`, so I left them as is for now.
I was able to redownload the dependencies locally, but a CI run would be good to know to double check that there wasn't accidentally some cache that made the build possible.
This fixes #1643.
=> Fixes #1643: Remove JCenter from build repositories

build/Dockerfile.build, build/Dockerfile.fdbserver, build/docker-compose.yaml, docs/ReleaseNotes.md, docs/Versioning.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedReadTransaction.java, gradle.properties
This increases the FDB Java dependency to FDB 7.1. This keeps the API version at 630 so that the library can still be used to connect to FDB 6.3 and FDB 7.0 clusters, though it would now require using a 7.1 FDB C client as the primary client with the other clients as external clients.
This will allow for additional features to be built on top of FDB 7.1, though we probably want to also complete #1639 so that we can responsibly guard features reliant on 7.1 in environments where the cluster may still be running older FDB server versions.
This also updates the proto3 version to 3.20.1 and along with a few other dependencies. It leaves the guava version at 30.1-jre instead of updating it to 31.1-jre because that causes spotbugs violations regarding nullability problems. I think those errors …
=> Resolves #1636: Increase FDB Java version to FDB 7.1 

gradle/proto.gradle
As suggested in the issue, on macOS Apple Silicon architectures, this reverts to an x86_64 version of the proto2 compiler for compatibility reasons. This will run in emulation on machines with that architecture. Note also that we do not ship protoc with our binaries, nor do we link against it, so there is not a concern that this would cause problems at link time for software compiled for Apple Silicon. The protoc binary is only used during our own compilation to generate Java files from our `.proto` files.
This fixes #1657.
=> Fixes #1657: build error on Apple silicon with PB 2.6

build.gradle, docs/ReleaseNotes.md, fdb-extensions/src/test/java/com/apple/foundationdb/FDBTestBase.java, fdb-record-layer-core/fdb-record-layer-core.gradle, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/APIVersion.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactoryImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTransactionContext.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/APIVersionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBTestBase.java, gradle/scripts/log4j-test.properties, gradle/testing.gradle
This makes the FDB API version configurable through the `FDBDatabaseFactory`.
We'll need some better way of testing this, I think. I've tried running the tests at both the 6.3 and 7.1 API versions, and it passed, but this value cannot be changed after the client has been initiated, which makes this somewhat complex to test with our normal approach. We might be able to use a test-only implementation of `FDBDatabaseFactory` if we wanted to, say, test future work that had feature flags on the API version. Another approach might be to run the tests multiple times, once per API version
This resolves https://github.com/FoundationDB/fdb-record-layer/issues/1639.
=> Resolves #1639: Support a configurable FDB API version

gradle/testing.gradle
This sets a default timeout for JUnit tests in the project. The value that was chosen was supposed to be fairly high, but individual tests could still set their own.
It may be worth it to have a lower timeout (maybe 1 minute or 30 seconds), and then use the `Slow` and `Performance` tags to increase the timeout on some tests. I didn't do that here (yet, at least), because it looked unclear to me whether there was a way to do that with the existing `Tag`s, or if we'd need to do something like switch to using a custom test annotation.
This resolves #1665.
=> Resolves #1665: Set default timeout for unit tests

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/StoreTimer.java
To interface out StoreTimer, but still make use of it, it would be useful if we could create a Subclass of `StoreTimer` that can create and manage it's own `Counter` instances; this PR makes a few of the constructors in `StoreTimer.Counter` public so that they can be instantiated outside the `StoreTimer` class
=> Making the StoreTimer.Counter class have a couple public constructors

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/runners/TransactionalRunner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/runners/TransactionalRunnerTest.java
This existed ot FDBDatabaseRunnerImpl, but not TransactionalRunner, so closing at the same time as calling `run` can cause a ConcurrentModificationException.
=> Fixes #1659: Add a missing synchronized keyword to TransactionalRunner.close

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AccessHint.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AccessHints.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/IndexAccessHint.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PrimaryAccessHint.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/RelationalExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/FullUnorderedScanExpression.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/AccessHintsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCoveringIndexQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSimpleQueryGraphTest.java
* This PR is to support index hint in a query
* Add index info to FullUnorderedScanExpression, then when match candidates, the query can be subsumed by a candidate only when the index is included in the hint indexes.
=> resolves #1671: match index hints in a query

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/TypeRepository.java
In this PR we expose some constructors to make it to extend the type system, we also expose a `Type.Record` builder that accepts an explicit record name, and use `LinkedHashMap` instead of `HashMap` in `TypeRepository` for a stable traversal order (insertion order).
=> Make the type system more extensible

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIndexPlan.java
This fixes the merge skew error caused by #1561 relying on a method that #1629 removed.
This fixes #1672.
=> Fixes #1672: Merge skew causing compilation failure in RecordQueryIndexPlan

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/ValueIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchTest.java
Resolves #1679
Only allow remote fetch for ValureIndexManintainer
Add a few more test cases for in- and out-of- range tests
=> Protect remote fetch from non-value subclasses of IndexMaintainer

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/MapResultCursor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java
This adds a variant to `RecordCursor.map` that allows the caller to adjust the continuations returned by a `RecordCursor`. This would allow, for example, for someone to wrap the continuations with new data, or otherwise adjust the continuations returned.
This resolves #1663.
=> Resolves #1663: Add .map variant to RecordCursor that supports changing a result's continuation

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java, fdb-record-layer-lucene/src/main/java/org/apache/lucene/index/StandardDirectoryReaderOptimization.java, fdb-record-layer-lucene/src/main/java/org/apache/lucene/index/package-info.java
This is an attempt to make the segmentReader opening in parallel vs. sequential to hide latency.
`com.apple.foundationdb.record.lucene.directory.FDBIndexInput.length(FDBIndexInput.java:197) org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:513) org.apache.lucene.codecs.CodecUtil.retrieveChecksum(CodecUtil.java:490) org.apache.lucene.codecs.CodecUtil.retrieveChecksum(CodecUtil.java:509) org.apache.lucene.codecs.blocktree.BlockTreeTermsReader.<init>(BlockTreeTermsReader.java:240) com.apple.foundationdb.record.lucene.codec.LuceneOptimizedPostingsFormat.fieldsProducer(LuceneOptimizedPostingsFormat.java:57) org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:114) org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:83) …
=> Parallelize SegmentReader Creation During IndexReader.open #1684

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java
This removes the `ERROR`-level log on no-op failure. The error was already getting propagated, and that, in practice, should be enough for adopters to detect errors and (if they so desire) log the error. I considered adding logic to include the `cluster` as logging details, but that ended up being a little bit delicate because it only works if the underlying failure is a `LoggableException`, which isn't necessarily the case because we haven't called the error-wrapping logic at that point. So, it was easier to just leave it without that information, and it didn't seem like a huge loss, as the caller should be able to determine that based on the fact that they need an `FDBDatabase` to call this on anyway.
This resolves #1692.
=> Resolves #1692: Remove ERROR level log on failed no-ops

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/common/text/TextSamples.java
I don't _think_ these were deliberately put in a funny place.
=> Unicode combining acute accent follows the base character.

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteResultCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/LuceneOptimizedIndexSearcher.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/package-info.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBLuceneTestIndex.java
Major phases of Lucene Query for data access:
1. IndexSearcher Open
2. Term Weights
3. IndexSearcher Probe
4. Scoring Weighting***
1 Sequential call per Leaf
`com.apple.foundationdb.record.lucene.directory.FDBDirectory.readBlock(FDBDirectory.java:357)
at com.apple.foundationdb.record.lucene.directory.FDBIndexInput.readBlock(FDBIndexInput.java:130)
at com.apple.foundationdb.record.lucene.directory.FDBIndexInput.seek(FDBIndexInput.java:184)
at org.apache.lucene.codecs.lucene84.LuceneOptimizedPostingsReader$BlockDocsEnum.reset(LuceneOptimizedPostingsReader.java:365)
at org.apache.lucene.codecs.lucene84.LuceneOptimizedPostingsReader.postings(LuceneOptimizedPostingsReader.java:250)
at org.apache.lucene.codecs.lucene84.LuceneOptimizedPostingsReader.impacts(LuceneOptimizedPostingsReader.java:269) …
=> Lucene Scoring Weighting Phase: Sequential Database Activity #1697

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/LuceneOptimizedIndexSearcher.java, fdb-record-layer-lucene/src/main/java/org/apache/lucene/search/QueryHelper.java, fdb-record-layer-lucene/src/main/java/org/apache/lucene/search/package-info.java
Major phases of Lucene Query for data access:
1. IndexSearcher Open
2. Term Weights***
3. IndexSearcher Probe
4. Scoring Weighting
Here is the call stack in the code…
`com.apple.foundationdb.record.lucene.directory.FDBIndexInput.readBlock(FDBIndexInput.java:130)
at com.apple.foundationdb.record.lucene.directory.FDBIndexInput.seek(FDBIndexInput.java:184)
at org.apache.lucene.codecs.blocktree.LuceneOptimizedSegmentTermsEnumFrame.loadBlock(LuceneOptimizedSegmentTermsEnumFrame.java:171)
at org.apache.lucene.codecs.blocktree.LuceneOptimizedSegmentTermsEnum.seekExact(LuceneOptimizedSegmentTermsEnum.java:515)
at org.apache.lucene.index.TermStates.loadTermsEnum(TermStates.java:124)
at org.apache.lucene.index.TermStates.build(TermStates.java:109)
at …
=> Lucene Term Weights Phase: Sequential Database Activity #1700

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneNotQuery.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java
At root a new clause class that produces a negated boolean.
But since Lucene represents that as another `Occur`, the clause actually implements set subtraction.
The planner tries to maximize the cases where the subtraction is from a positive query rather than just `*:*`.
Includes #1675 because of conflicts.
=> Resolves #1691: Lucene negative queries

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java
Note that this does not change any generated plans. It just tries to make the logic for excluding vacuous queries more clear and better commented. And adds a couple tests.
=> Resolves #1674: Lucene scans without queries

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreCountRecordsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreOpeningTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreSplitRecordsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java
After #1711, there are some deprecation warnings that are breaking the build. This resolves the deprecation warnings by using the new API and marking the old one as deprecated in test code.
=> Fix deprecation warnings in tests

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexExpansionVisitor.java
When Cascades expands a `Index` into a `KeyExpression`, there is some logic that examines the index's root expression keys and appends any missing primary keys to the end via `concat`. This works as expected for `ThenKeyExpression`.
However if the root expression is `KeyWithValue` such as e.g. (`KeyWithValue({RecordType, A, B} 2)`, where `A` is a primary key), then it will pass the `KeyWithValue` as-is to `concat` causing it to fail, because `concat` thinks there is only a single key to be concatenated (but in our example above, we have two keys: `RecordType` and `A`).
To fix this problem, we check first if the root expression is a `KeyWithValue`, if so, we get its key expression, and proceed with the same logic.
=> Resolve #1725: Reconstruct KeyWithValue expression correctly.

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedReadTransaction.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchTestBase.java
Improve remote fetch store timer counters: Rename SCAN_INDEX_REMOTE_FETCH to SCAN_REMOTE_FETCH_ENTRY and add REMOTE_FETCH.
Modify tests.
=> Resolve #1721: Remote fetch counters

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/CursorLimitManager.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchWithoutSplitRecordsTest.java
Remote fetch was double counting bytes and scanned records in the limit manager.
Fix by giving KeyValueUnsplitter an unlimited limit manager.
=> Resolve #1730: Fix double count

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/FallbackCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIndexPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/cursors/FallbackCursorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchTestBase.java
Improve remote fetch fallback  to allow fallback after a few records have been returned
=> resolve #1727: Allow fallback after records already returned

.idea/compiler.xml, build/Dockerfile.build, build/Dockerfile.fdbserver, build/Dockerfile.standalone-tests, build/docker-compose.yaml, docs/ReleaseNotes.md, gradle.properties
The FDB Java version has been updated to 7.1.10 in this PR. The more important thing is actually that the client (and server) versions be updated to 7.1.10 or 7.1.11 (depending on whether the environments support AVX instructions) to get the recent bug fixes, but this seems like a good signal to send to let our downstream adopters know they should upgrade.
This resolves #1743.
=> Resolves #1743: Update FDB dependency to 7.1.10

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/IndexFetchMethod.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlannerConfiguration.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIndexPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchIndexScanTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchMultiColumnKeyTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchOldVersionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchSplitRecordsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/VersionIndexTest.java
This PR creates a wrapper around index scan method: A new overload of `scanIndexRecords` that takes in an `IndexScanMethod` and delegates to the appropriate method. This is very similar to the work done in the `RecordQueryIndexPlan` (except that in the plan, the regular scan and fallback methods are managed by the plan and are not plain ValueIndex scans).
Added tests are a subset of the `RemoteFetchTests` adjusted for the new method instead of a plan execution.
=> Resolves #1756: Remote fetch index scan wrapper

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanOrderingKey.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanWithOrderingKey.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexQueryPlan.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java
Resolves #1654: Lucene sort by primary key
Resolves #1653: Lucene plans should expose ordering key
=> Further improvements to Lucene sorting

fdb-extensions/fdb-extensions.gradle, fdb-extensions/src/main/java/com/apple/foundationdb/annotation/GenerateVisitorAnnotationProcessor.java
Release 3.2.278 was fine for dependent systems compiled with Gradle.
But adding a `@AutoService(javax.annotation.processing.Processor.class)` means all of its runtime implementation also needs to be `api` so that
IntelliJ IDEA can call some of it (to determine that it isn't something it cares about, presumably).
=> Gradle 7 problems with IntelliJ compilation of client.

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java
readBytes with compression on during reads and a few spots were filePointer is constantly reset.
=> getFilePointer and readBytes hotspots #1780

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchIndexScanTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchTestBase.java
Some counters can be larger than expected - likely due to setup IO.
=> Make RemoteFetchIndexScanTest less flaky: Allow for counters to be larger than expected.

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
Unfortunately we overlooked caching segment files ("segments_)"
=> The checksum on the segment file blocks #1784

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/VersionIndexTest.java
Remove USE_REMOTE_FETCH test for version index for now in order to allow tests to pass when using FDB version < 7.1.10
THis should be enabled again once 7.1.10 gets wider adoption.
=> Resolve #1792: Skip failing tests in dev

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/LuceneOptimizedIndexSearcher.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java
In previous implementation there was a potential for a deadlock which could happen as the following:
- Let's assume we have a `FDBRecordContextConfig` configured with an `ExecutorService` using a thread pool containing 2 threads, (`T1`, `T2`) , execution a `LuceneScanIndex` query starts.
- `LuceneRecordCursor` calls `searchForTopDocs`, this method invokes [`IndexSearcher#search`](https://github.com/apache/lucene/blob/2cf12b8cdcc629617b2d58c0a2a6336679ff9249/lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java#L651) method which will do, among other things, the following:
```java
for (int i = 0; i < leafSlices.length - 1; ++i) {
final LeafReaderContext[] leaves = leafSlices[i].leaves;
final C collector = collectors.get(i);
FutureTask<C> task = new FutureTask<>(() -> { …
```
=> Fix Lucene optimised index searcher

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBReverseDirectoryCache.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ExtendedDirectoryLayer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolver.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ResolverValidator.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ScopedDirectoryLayer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/layers/interning/ScopedInterningLayer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ExtendedDirectoryLayerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolverTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ResolverMappingReplicatorTest.java
This adds arguments to `reverseLookup` to allow a transaction to be included that can be used to get a read version, much like the `resolve` methods.
This resolves #1714.
=> Resolves #1714: LocatableResolver::reverseLookup should support borrowing read versions

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/AvailableFields.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/IndexKeyValueToPartialRecord.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanWithStoredFields.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneFunctionKeyExpression.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneFunctionKeyExpressionFactory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneFunctionNames.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexQueryPlan.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java
Add function key expressions to represent the two built-in sort orders for Lucene searches.
Plumb these through the IndexEntry cursor so that they are available for merging.
For now, do not claim these as part of an intersection / union candidate, as whether they are the same from one search to another is complicated.
=> Refine Lucene sorting keys

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/LuceneOptimizedIndexSearcher.java
This PR made the LuceneOptimizedIndexSearcher, however it mistakenly allowed `CollectionTerminatedException` to be propagated to the outside.
In the original code, that exception was [properly ignored](https://github.com/FoundationDB/fdb-record-layer/commit/e98cf6aa234563acc7c45e57c3a6f19e22af0a1f#diff-f59fd6db59846daffb972ed37a5e1e7352965c1905e97b1b75c418bef7c61275L112) as suggested in Lucene Docs:
> Note: IndexSearcher swallows this exception and never re-throws it. As a consequence, you should not catch it when calling [IndexSearcher.search(org.apache.lucene.search.Query, int)](https://lucene.apache.org/core/7_4_0/core/org/apache/lucene/search/IndexSearcher.html#search-org.apache.lucene.search.Query-int-) as it is unnecessary and might hide misuse of this exception.
This PR attempts to …
=> Ignore CollectionTerminatedException.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/UnsupportedRemoteFetchIndexException.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIndexPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchIndexScanTest.java
When the index type is not supported for remote fetch (e.g. RANK, BITMAP, TEXT), the log message should not be WARN so as not to pollute the logs - this is a case where future development will increasingly support more index types and is not considered an error. 
In the case of `REMOTE_FETCH_WITH_FALLBACK`, the fallback mechanism would perform the scan using the legacy scan and fetch. 
In the case of `USE_REMOTE_FETCH`, the exception thrown (`UnsupportedRemoteFetchIndexException`) should indicate that this is a "not yet implemented" issue.
=> Resolves #1827: Lower log severity for remote fetch when index type is unsupported

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchIndexScanTest.java
In the case of remote fetch with fallback, the check for illegal PK length should fail the remote fetch operation but not the entire operation, so that the scan-and-fetch would still be applicable.
Fixed the tests that were incorrect, as they were incorrectly adapted from the PK expression logic.
=> Resolve #1845: Remove premature test for illegal PK length for remote fetch

docs/GettingStarted.md
This "Getting Started" page didn't work for me and confused. Here are some cleanups:
* Acknowledge we use protobuf3 but syntax is proto2.
* Gradle `--type java-application` creates an 'app' subdir now with its own build.gradle -- so two build.gradles -- which complicates the example (example won't work if you edit the wrong build.properties). Lets do 'basic' to keep things simple.
* Add answers for the questions gradle `init` asks.
* plugins need to be added at the top of the build.gradle -- the example implies the clause can go anywhere -- and our protobuf plugin won't run if no mention of the java plugin.
* Example code was missing the line where we build the RecordMetaData.
=> Fix broke "Getting Started": add note on protobuf versions, use the `basic` gradle type, update dependencies, and mix in some missing info

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexExpressions.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneQueryMultiFieldSearchClause.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/LuceneOptimizedMultiFieldQueryParser.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
Numeric type queries have to be handled specifically in Lucene, using some custom logic in the Parser during lucene query build time. This ensures that the parser does the correct thing for point and range queries
=> Make Lucene parse Numeric type queries correctly

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordTypeValue.java
... so it doesn't clutter pictorial plan representation.
=> implement simple RecordTypeValue.toString

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/PartiallyOrderedSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/TopologicalSort.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/TransitiveClosure.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchInfo.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchedOrderingPart.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Ordering.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/OrderingPart.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/RequestedOrdering.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexLikeMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/WindowedIndexScanMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/GroupByExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/MatchableSortExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/RelationalExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/RelationalExpressionWithChildren.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/SelectExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/OrderingProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/ReferencesAndDependenciesProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/AbstractDataAccessRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementDistinctUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementInJoinRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementInUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PushRequestedOrderingThroughGroupByRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PushRequestedOrderingThroughSortRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/RemoveSortRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/SplitSelectExtractIndependentQuantifiersRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/AbstractValueRuleSet.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/combinatorics/PartiallyOrderedSetTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/OrderingTest.java
- `PartialOrder` -> `PartiallyOrderedSet` -- This is more in line with how this should be named judging from wikipedia and other online sources. There is a class (in spi) of that name though.
- `KeyPart` -> `OrderingPart` -- originally part KeyExpression. The new naming is more indicative of its use. As this is moving from a `KeyExpression` to a Value and whether sorting is ascending or descending, I think we can name this `OrderingPart`.
- `BoundKeyPart` -> `MatchedOrderingPart` -- this is only used for matching purposes
- removal of a lot of `...Key...` from local variable names and parameter names
=> name changes

docs/ReleaseNotes.md, docs/Versioning.md
There are a few places in our docs where we reference the current version. This updates those, as #1855 updated the minor version to 3.3 from 3.2
=> Update documentation for 3.3 version

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/synthetic/JoinedRecordPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordByTypePlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordConcatPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordScanPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticPlanMatchers.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordPlannerTest.java
This comment https://github.com/FoundationDB/fdb-record-layer/pull/1873#discussion_r997918275 suggested that matching on the generated plans would be beneficial. This adds that for all the direct calls to the planner in the test class.
The matchers only go against the generated queries inside the synthetic plan objects. It would be straightforward to extend them to match on other pieces of state, if any are deemed important enough. I felt that while they are, of course, necessary for execution, they weren't. But this wasn't strongly felt.
=> Add Matchers for SyntheticRecordPlanner outputs.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTypedRecordStore.java
Refactor the remote fetch indexEntriesToIndexRecords method to use an internal method, and expose a new buildSingleRecord method externally.
The new method, `buildSingleRecord(@Nonnull FDBIndexedRawRecord indexedRawRecord)`, can now be used externally, for example when one needs to get a record from a remote fetch MappedRange structure (as opposed to the previous method that only returned a cursor).
=> Resolve #1865

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedFieldQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordPlannerTest.java
This adds support to the old planner to address a shortcoming where certain queries were choosing to use less efficient indexes due to a shortcoming with the `AndWithThenPlanner`. Based on the tests in the `NestedFieldQueryTest`, it looks like the new planner was already matching such expressions in this case, and so this shortcoming should only be in the old planner.
This fixes #1876.
=> Fixes #1876: AndWithThenPlanner does not handle OneOfThemWithComponent expressions

build.gradle
This updates the artifactory plugin version to the latest. This should resolve issues with the `build-info` dependency, which previously depended on a version that has since been taken down from maven.
This resolves #1902.
=> Resolves #1902: Update Artifactory Plugin Version

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexScanMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/WindowedIndexScanMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/ValueMatchers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/FieldValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/TransformValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Values.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/CompensateRecordConstructorRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/ComposeFieldValueOverRecordConstructorRule.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/OrderingTest.java
- got rid of parallel arrays in `FieldPath` in favor of `ResolvedAccessor`
=> introduce `ResolvedAccessor`

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/PartiallyOrderedSet.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/OrderingTest.java
When pulling up a `Value` through `Ordering`, it is possible that we do not clean up dependency lineage (found through the transitive closure) correctly if we don't find a dependency target in the pulled up `Value`.
This causes some plan partitions to misrepresent their order causing Cascades to fail to plan some queries due to not being able to satisfy their ordering requirement because of that.
It fixes #1905.
=> Fix pulling up `Value` through `Ordering`

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/IndexEntry.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoredRecord.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoredRecordBuilder.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteResultCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneDocumentFromRecord.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneFunctionKeyExpressionFactory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneFunctionNames.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneHighlightTermsPlan.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexKeyValueToPartialRecordUtils.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneQueryComponent.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneScanQuery.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneScanQueryParameters.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteResultCursorTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneDocumentFromRecordTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenePlanMatchers.java
Follow-up to #1863.
Instead of introducing a new way of intercepting the loading of a record from its index entry, add a new plan operator to do highlighting. This makes changes to `-core` (hopefully) uncontroversial.
Other than that, the changes are intentionally minimal from the earlier PR.
Note that Union plans are different: there is no case of `Union` of `Covering` with deferred `Fetch`. The `Highlight` prevents this. It should be possible to defer the `Highlight` to after the `Fetch` and so allow a union of index entries inside. However, that requires planner support. Moreover, all these plans, including the one in the earlier PR, have a problem when results from two differently shaped searches are combined. The desired outcome is that the record's fields highlight terms from either …
=> Resolves #1862: Lucene search with highlighting the terms

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteResultCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
* More `Query` classes for term extraction.
* String index out of bounds when finding matched terms.
Note that there are still problems with `searchAllMaybeHighlight` regarding `highlightedTextConnector` if an ngram tokenizer is used. The same word will be seen several times from the min ngram up to its length, confusing the `currentPos` count. The result of this is stray ellipses. It seems better to get this in without crashes than wait for @tian-yizuo to be available to review anything more substantial.
=> Some more Lucene highlighting fixes

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/CursorStreamingMode.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/KeyValueCursor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchSplitRecordsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchTestBase.java
Add support for LARGE, MEDIUM, and SMALL cursor streaming modes. These are only used if specifically set by the API users and should not change the default behavior.
=> Resolve #1915: add support for additional cursor streaming modes

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByIndex.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/NoOpIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildGroupedCountIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildRankIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildSumIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildValueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildVersionIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerUniqueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/TerribleIndexMaintainer.java
This adds support for building a non-idempotent target index when indexing from a different source index. This works in a manner that is analogous to the way that this operation works for non-idempotent indexes built by a record scan, except that as the range set contains ranges of index entries from the source index, the maintainer needs to be updated to: (1) check the indexing type stamp and (2) modify the range set check to use the index key instead of the primary key. Then there are some updates to the indexers to adjust logic that assumed the target index type would always be idempotent.
I played around with the tests added in this PR, and I've validated that if I inject a few bugs into the code (like checking the wrong value in the range set) that they fail, so I'm fairly confident …
=> Resolves #1430: Support non-idempotent target indexes while indexing by index

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedFieldQueryTest.java
Another nested sorting test case that worked at 52b44e4af3decafd6c4398dbcb3ae58eae1e98ed but regressed.
Need to account for a multi-column index child that matches the sort once equalities are skipped.
=> More of #1907: Sorting and comparing nested fields get confused

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/visitor/RecordQueryPlannerSubstitutionVisitor.java, fdb-record-layer-core/src/test/proto/test_records_join_index.proto, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexQueryPlan.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneSyntheticPlannerTest.java
* Handle `ListKeyExpression` in primary key when pulling out `Fetch`.
* Handle nested Lucene functions for available fields.
Fixes #1927: Unable to construct a covering plan for a Lucene index over a Synthetic Record Type
=> Fix covering plan for a Lucene index over a Synthetic Record Type

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/ByteArrayContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursorEndContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursorStartContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/ChainedCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/FlatMapPipelinedCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/ListCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/OrElseCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/RangeCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/KeyValueCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/BloomFilterCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ComparatorCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/IntersectionCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnionCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/ComposedBitmapIndexContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQuerySelectorPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/FileSortCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/MemorySortCursorContinuation.java
This updates the logic in the `RecordCursorContinuation` objects to avoid serializing a continuation all the way to a `byte[]` if it is not necessary. For example, when constructing protobuf objects that back continuations, child continuations can be constructed by calling `.toByteString()` on the continuation and passing that to the protobuf builder instead of serializing all the to a `byte[]` and then wrapping it back in a `ByteString`. This also makes sure that (as much as possible) the cursor implementations are more efficient when constructing a `ByteString`. For example, for the proto-based continuations, it should be able to return `.toByteString()` on the protobuf object instead of serializing the _protobuf_ all the way to a `byte[]` and then wrapping it back up, which some …
=> Resolves #1923: Avoid copying continuation byte arrays by using ByteString internally

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/VersionIndexTest.java
This reduces the number of unnecessary clears issued during check version by being more precise about when the legacy version subspace is cleared. It will only clear the range now if (1) the store is not new and (2) the store header suggests that any versions in the old store would have been stored in the old space. It introduces a test that validates that the version is cleared if versions were stored in that old subspace and the meta-data is changed to so that versions are no longer stores. That test valdiates that there are fewer range clears now if the range doesn't have to be cleared, but other than that assert, the test asserts pass both before and after the main code changes.
This resolves #1936.
=> Resolves #1936: Reduce unnecessary clears of legacy version space

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/FDBRecordStoreProperties.java
This changes the default value in the property controlling whether record deletes are unrolled. Adopters can still opt into the old behavior by setting the property value, though most use cases should be fine with the new default. At some point in the future, we can consider deprecating the property and always unrolling record deletes if we wish.
This resolves #1942.
=> Resolves #1942: Make unrolled deletes the default record delete behavior

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordConstructorValue.java
This allows the children accumulators in `RecordConstructorValue` to finalise their group instead of prematurely return `null`, this allows some special accumulator semantics to kick in such as `count()` (which returns `0` instead of `null` in case of empty group).
Fixes #1950.
=> Delegate accumulator finalisation to children in RCV.

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteResultCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneHighlighting.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteResultCursorTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
* Add a test for the missing case.
* Properly extract the term from that class.
* Generalize the auto-complete prefix highlighting to handle this new term.
=> Fixes #1953: LuceneRecordCursor.getTerms missing PrefixQuery

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java
This exception provides the caller extra information about the existing indexing method.
=> Resolve #1961: Indexing: Throw PartlyBuiltException when appropriate

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexPrefetchRangeKeyValueCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/KeyValueCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/KeyValueCursorBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java
This is clearing some technical debt from the original remote fetch implementation. One of the PR comments was to implement a base class for KeyValueCursor and extend it for the base KeyValueCursor and the RemoteFetch variant.
A few other fixes were made in support of SonarQube errors, but the overall logic should not have changed.
=> Resolve  #1957: Create base class for KeyValueCursor and Builder, use with IndexPrefetchRangeKeyValueCursor

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreOpeningTest.java
Adds a boolean flag `VersionChanged` to indicate if the version has been changed while creating/opening a new store. 
When a RecordStore is created via `createOrOpen()`, `create()` or `open()` methods in `FDBRecordStore.Builder`, the `checkVersion()` is called underneath to update the store versions to the newest possible values and returns a boolean value. `VersionChanged` persists this boolean value that can be retrieved from the `Builder` _after_ creating/opening a (new) store. 
The version changed info can therefore be made available anywhere the store is built.
fixes #1965
=> Expose version change info from FDBRecordStore

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedReadTransaction.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimerTest.java
This adds a counter of empty scans that gets incremented during empty range reads. This can then be used to track how many reads are returning zero results from a given workload.
This resolves #1970.
=> Resolves #1970: Add instrumentation of empty scans

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBQueriedRecord.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SortedRecordSerializer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordPlannerTest.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneHighlighting.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java
1. Allow longer field names for Lucene validation.
In effect, any path prefix is accepted.
The fields in the Lucene query component field list sometimes reflect more of the path, particularly with a Lucene join index.
2. Allow highlighting to work on a constituent record from a joined record Lucene index.
For this we need the constituent field name and to adjust the index expression and terms map accordingly.
3. Generalize constituent handling around `FDBQueriedRecord` beyond just `getConstituents`.
Can also get a particular constituent, which requires a little work in the case of covering.
This adds some non-abstract methods, but there doesn't seem any philosophical objection to that.
=> Some improvements for Lucene queries against joined indexes

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/FDBRecordStoreProperties.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SplitHelper.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreOpeningTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreSplitRecordsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/SplitHelperTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
This adds a property-controlled method for reading single records from FDB. It issues multiple single-key gets instead of one scan (for reasons detailed in #1967). This is off by default, because it is expected that this will perform worse on B-tree based storage engines (including the default SSD storage engine), and it is highly experimental. But once in, users can adjust this configuration to configure how reads are orchestrated in their own experiments.
This resolves #1967.
=> Resolves #1967: Consider alternative mechanism of loading records which favors gets over scans

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/GroupByExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/RecordQueryPlanMatchers.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/GroupByTest.java
This fixes compensation logic in `GroupByExpression` such that if the underlying quantifier has any compensation requirements it will return an impossible compensation effectively causing the (aggregate) index match candidate to disqualify if the query has any predicates in the select-where part requiring compensation.
This resolves #1974.
=> Resolves #1974: Cascades Aggregate index plan matching ignores predicates

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/FDBRecordStoreProperties.java
This sets the default value of the `LOAD_RECORD_VIA_GETS` property to false. This reverts the default behavior to match what the behavior prior to 3.3.327.0 when the property was introduced. It was always the intention that this property would be off by default, and then adopters could experiment with it to see if it improved performance, but the default was set incorrectly in the initial commit.
This resolves #1982.
=> Resolves #1982: LOAD_RECORDS_VIA_GETS should default to false

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/TestHelpers.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java
This adds the store timer metrics to the progress log message that is logged during an index build so that we can have insight into what the performance of a build is while it is going on.
This resolves #1984.
=> Resolve #1984: Log store timer metrics during indexer progress log message

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreUniqueIndexTest.java
When clearing out index data, we don't really need to clear out the list of uniqueness violations on non-unique indexes, as that data is only consulted by unique indexes. This skips clearing out that space for those indexes, and it also adjusts the `scan` method to only ask unique indexes for violations.
This resolves #1973.
=> Resolves #1973: Clearing index data can skip uniqueness violations space on non-unique indexes

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/runners/ExponentialDelay.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerTest.java
This adds metrics recording the amount of time that is spent during retries and indexing during delays. There was already a `WAIT_RETRY_DELAY` metric, but nothing that captured the event in asynchronous contexts, so I added `Event`s for `RETRY_DELAY` and `INDEXER_DELAY`, and then added instrumentation for those hooks. I also looked into testing, but testing that these events are hit is actually kind of difficult. I tried to add a test to `FDBDatabaseRunnerTest` that asserted on the metrics, but it was difficult to write one that was both reliable and actually asserted on anything, because the values for the counters can be legitimately zero if there isn't any actual delaying going on. Giving that this is just some metrics, the most important thing would seem to be making sure that it …
=> Resolves #1993: Add store timer metrics for retry and indexing delays

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/RangeSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByIndex.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByRecords.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMultiTargetByRecords.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMutuallyByRecords.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexing/IndexingRangeSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexing/package-info.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreOpeningTest.java
This adds additional metrics for the `RangeSet` class. This refactors access of the class so that it goes through a wrapping object, which associates a `RangeSet` with a particular `FDBRecordContext`. That context is then used to supply the transaction for the range set, but it also is used to instrument operations of this new wrapper class so that we have timing information for `RangeSet` operations during an index build.
This resolves #1995.
=> Resolves #1995: Instrument RangeSet operations during index builds

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedReadTransaction.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimerTest.java
At the end of a range scan, it is legal to call `hasNext()` mutliple times. The old code would allow `hasNext()` to be called multiple times, and then it would increment the `EMPTY_SCANS` counter each time, which could result in the metric appearing the exceed the `RANGE_READS` metric. This also fixes another way in which `RANGE_READS` could be undercounted, as it is legal to start multiple `AsyncIterator`s from one `AsyncIterable`, though I don't think we actually do that within the Record Layer. Those two fixes together should ensure that `EMPTY_SCANS` is never higher than `RANGE_READS`.
This fixes #2002.
=> Fixes #2002: "EMPTY_SCANS" metric double counts empty ranges if hasNext() called multiple times

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/StoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBReverseDirectoryCache.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTransactionContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedReadTransaction.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedTransaction.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/layers/interning/ScopedInterningLayer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStorePerformanceTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreRepairTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBReverseDirectoryCacheTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/VersionIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/ExtendedDirectoryLayerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolverTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/LeaderboardIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/storestate/FDBRecordStoreStateCacheTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordPlannerTest.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
This allows `FDBStoreTimer.Event`s to mark themselves as delayed until commit, in which case the context won't increment/record them initially, and they'll only get added to the base timer once the transaction has successfully committed. This is done by having the record context keep track of two timers, one of which is from the user and is updated immediately and the other of which is created by the context and stores these delayed metrics. Once the commit happens, the data from the delayed timer are added to the other timer.
I'd initially wanted this to be done with a single timer, which would then encapsulate the dispatching between the two timers. I think with a slightly different class hierarchy (such as a single `StoreTimer` interface with various implementations arranged to support …
=> Resolves #1998: Delay publishing commit-dependent metrics until after commit

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMutuallyByRecords.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/main/proto/index_build.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMutualTest.java
Add indexing control flow. Allowing: 
1. Set frequency of checking the indexing stamp (never, always, or minimal time between checks) 
2. Throw an exception of the indexing stamp had changed 
3. Provide a way to query, block, and unblock the indexing stamp
4. Provide an option to unblock during indexing 
5. Provide an option to add a block id during block, that can be used for verification during unblock 
6. Provide a time-to-leave option to the indexing block
=> Resolves #1980: Indexing typestamp: add query + flow control

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java
The bug is in the `IndexingMutuallyByRecords.java` module, using `null` as `additionalLogMessageKeyValues`. But creating a general solution seems to be a good idea.
=> Cont. #1853: Mutual concurrent indexing - null pointer bug fix

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/StoreSubTimer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimerTest.java
This adds an override to the `StoreSubTimer` class so that `.add(StoreTimer)` now adds the metrics from the passed in store timer both to its own counters but also to the counters of the underlying timer. This type of timer is constructed when a `TransactionListener` is specified:
https://github.com/FoundationDB/fdb-record-layer/blob/7677bc45a3aea3b5e11b3c582f2e90ee4788db04/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java#L755-L757
With the old `.add(StoreTimer)` implementation, if such a `StoreSubTimer` was used, then the delayed metrics would get added to the `StoreSubTimer`, but not to its underlying timer, which means that these metrics would appear to be gone from the the underlying timer in their entirety. This change now …
=> Fixes #2010: StoreSubTimer missing add override

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java
To let use external callers make stamp operations, declare the next functions pubic:
queryIndexingStamps
blockIndexBuilds
unblockIndexBuilds
=> Resolve #2027: OnlineIndexer: make stamp operations public

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexExpansionVisitor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCoveringIndexQueryTest.java
This adds a check while adding the primary key fields to the root expression so that if the primary key is entirely contained within the index expression and therefore doesn't need to be added to the key expression. There's a new test of the planner that fails without this fix, as the new planner needs to consider an expression of that kind. The test also runs under the old planner, which succeeded before and after this fix.
This fixes #2015.
=> Fixes #2015: ValueIndexExpansionVisitor does not handle when primary key subsumed by index key

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/RangeSet.java, fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java, fdb-extensions/src/test/java/com/apple/foundationdb/test/MultipleTransactions.java
This adjusts the way that the `RangeSet` adds conflict ranges when listing missing ranges so that it only adds a read conflict range if the range is relevant to the final answer. This means that, for example, disjoint ranges can be modified in concurrent transacitons and all commit. There was already logic that adjusted these ranges in `insertRange`, so only the list method needed to be adjusted.
This fixes #2024.
=> Fixes #2024: Listing missing ranges in a RangeSet has overly large conflict ranges

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexExpressions.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneQueryMultiFieldSearchClause.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneQuerySearchClause.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/ConfigAwareQueryParser.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/LuceneOptimizedMultiFieldQueryParser.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/LuceneOptimizedQueryParser.java
Similar to generating a `Query` based on the field's `PointsConfig` in `LuceneOptimizedMultiFieldQueryParser`, this adds similar functionality to `LuceneOptimizedQueryParser` so we can get more accurate results when performing range queries with integer types for example.
=> Use `PointsConfig` in `LuceneOptimizedQueryParser`

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/query/BitSetQuery.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/query/package-info.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/ConfigAwareQueryParser.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/LuceneOptimizedMultiFieldQueryParser.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/LuceneOptimizedQueryParser.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
Original comment as in #2048:
> This introduces a BITSET_CONTAINS function to the lucene query language:
>
> `flag:BITSET_CONTAINS(mask)`
> This returns true if the mask is wholly contained in flag.
This mainly copies #2046 and #2048 removing all dependencies on parser integration work.
=> Support `bitset_contains` in Lucene query

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAnalyzerRegistry.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAnalyzerRegistryImpl.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexExpressions.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneQueryFieldComparisonClause.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneQueryMultiFieldSearchClause.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneQuerySearchClause.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/exact/ExactTokenAnalyzer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/exact/ExactTokenAnalyzerFactory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/exact/package-info.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneAnalyzerRegistryTest.java
This fixes a problem with potentially parsing a Lucene query field predicate incorrectly if the field is stored or sorted. The issue is caused because the same text analyser, that is specified in the schema by the customer, is used to analyse the RHS of a stored field predicate which could lead to incorrect results.
When dealing with stored and sorted fields, the index maintainer will store their values as-is, therefore, when it is expected that a predicate on these fields gets the same treatments for its operands. This PR addresses this behaviour by doing the following changes:
* Implement a very simple no-op analyser, analyser factory, and tokeniser, that pass-through the analysed terms.
* In `LuceneAnalyzerRegistry`, add a overload of the method `getLuceneAnalyzerCombinationProvider` …
=> Add internal Lucene analysers to store and sorted document fields

.idea/compiler.xml, build.gradle, examples/examples.gradle, fdb-extensions/fdb-extensions.gradle, fdb-record-layer-core/fdb-record-layer-core.gradle, fdb-record-layer-icu/fdb-record-layer-icu.gradle, fdb-record-layer-lucene/fdb-record-layer-lucene.gradle, fdb-record-layer-spatial/fdb-record-layer-spatial.gradle, gradle/proto.gradle, settings.gradle
This updates the build script so that if one runs `./gradlew build` with no other arguments, it will build the proto3-based artifacts. If one sets the `PROTO_VERSION` to 2, it should still build the proto2-based artifacts, so this won't change the published artifacts, but it may affect flows of a developer working on the project.
This resolves #2053.
=> Resolves #2053: Default protoMajorVersion to 3 in build

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreCountRecordsTest.java
This adjusts the logic for handling the record count key so that on new stores, it doesn't have to recount the records. This isn't necessary because with a new store, the store is empty and thus the count key space can be defaulted to having no entries (that is, implicit zeroes for each entry). This also removes an extraneous clear range when the record count key doesn't need to be persisted.
This resolves #2052.
=> Resolves #2052: Unnecessary recount of records on new stores

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java
when evaluating whether canDeleteWhere can be run.
I wasn't able to reproduce the problem in Record Layer precisely, but will keep trying and will add it in when I can get it
=> Allow synthetic types to skip over the parent in the key expression

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneHighlighting.java
First pass with the query analyzer: we find all matches and where they are in the original text
Second pass with the standard analyzer: we extract snippets from the original text
Before this change, we would advance the query analyzer and the standard analyzer respective tokenStream at the same time. The assumption was that the standard analyzer would always be behind the query analyzer because the standard analyzer looks at stop words. 
However, because of an issue with the way synonyms were handled, we ended up with the query analyzer running behind, which could lead to StringIndexOutOfBounds issues.
=> Refactor the highlight code into two passes: find & cut

.gitignore, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneQuerySearchClause.java
We accidentally used the wrong error type in the LuceneQuerySearchClause, so the error was getting replaced with a construction error.
While I was at it, I added some .gitignores to avoid accidentally committing VSCode folders
=> Fix bad error

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCoreArgumentException.java
Not doing this was resulting in an error in the lucene module which was attempting to treat syntax errors as argument exceptions. It's possible that there is a more appropriate error for that within Lucene, but this change will at least mean that we don't lose the wrapped exception by accidentally triggering an "Unbalanced key/value" exception to be thrown at creation time.
=> Adjusting RecordCoreArgumentException so that we can pass wrapped exceptions correctly

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolver.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolverTest.java
New methods have been added to the `LocatableResolver` which accomplish the following:
1. A new "read" method allows the user to look at a mapping without creating one if it doesn't exist.
1. A transaction can be provided to read, create, or save a mapping. These methods have semantics that are more in line with the rest of the Record Layer's APIs.
1. Additional methods to directly read and update the full resolver state have been added. This can be useful if, for example, the user wants to both update the version and lock or unlock a locatable resolver.
These methods together make it possible to use a `LocatableResolver` in situations that are more in line with, say, a `RecordStore`.
This resolves #2062.
=> Resolves #2062: Expose transaction-scoped and read-only APIs from the LocatableResolver

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByRecords.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMultiTargetByRecords.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMutuallyByRecords.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMutualTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java
Implement `anyJumper` 
During the ANY iteration: 
If `throttledRunAsync` gets an exception, the mutual indexer will store it and return quietly 
Then, during the next outer iteration:
If at the same fragment, same range: re-throw (as the problem was not related to a rangeSet conflicts)
If at the same fragment, different range: jump to the next fragment
=> Mutual indexing: smarter ANY iteration - skip fragments that produce rangeSet conflicts

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpression.java, fdb-record-layer-core/src/main/proto/record_metadata.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataProtoTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpressionTest.java
Currently decimal values are treated as `int64`, this could silently change the semantics of an `IndexPredicate` with a `SimpleComparison` that has an operand of type `Integer` as it is widening it into `long`.
This adds support for `int32`, it also adds a unit test that verifies that the serialisation / deserialisation of comparison parameters yield identical results. it fixes #2091 and unblocks https://github.com/FoundationDB/fdb-record-layer/pull/2070.
=> Add support for `int32` in record metadata `Value`

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMutuallyByRecords.java
Changes are: 
1. Apply anyJumper to FULL iteration as well. This is done to prevent the inner loop from repeating indexing attempt when the range set is changing. 
2. Handle potential null fdb error provided to the anyJumper callback. 
3. Force anyJumperSaysBuild to either throw an exception or clear anyJumperEx.
4. Clear anyJumperEx if the new range is null. 
5. Fix a bug in the infinite loop protection.
=> Resolve #2100: A bug in mutual indexing may have cause low performance

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CascadesPlanner.java
in `3.3.368.0` a method in `CascadesPlanner` has been changed from:
```java
public RecordQueryPlan planGraph(@Nonnull Supplier<GroupExpressionRef<RelationalExpression>> expressionRefSupplier,
@Nonnull final Optional<Collection<String>> allowedIndexesOptional,
@Nonnull final IndexQueryabilityFilter indexQueryabilityFilter,
final boolean isSortReverse,
@Nonnull ParameterRelationshipGraph parameterRelationshipGraph)
```
to:
```java
public QueryPlanResult planGraph(@Nonnull Supplier<GroupExpressionRef<RelationalExpression>> expressionRefSupplier,
@Nonnull final Optional<Collection<String>> allowedIndexesOptional,
@Nonnull final IndexQueryabilityFilter indexQueryabilityFilter,
final boolean isSortReverse,
@Nonnull final EvaluationContext evaluationContext)
```
this could break customers still …
=> Restore removed method and mark it for deprecation.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/RecordTypeKeyComparison.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/QueryPlanConstraint.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/IndexPredicateExpansion.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/PredicateWithValueAndRanges.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/RangeConstraints.java
This provides few fixes pertaining filtered indexes:
* Fix for an issue with a flat conjunction not being recognized as a DNF.
* Fix for another issue with the captured constraints of filtered indexes being very strict (solves #2104).
* Finally, it adds `toString` to some of constructs used during filtered index matching, making debugging somewhat easier.
=> Fixes for filtered indexes

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexPredicate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java
FDBRecodStore is currently using a predefined IndexMaintenanceFilter as filter (defaulted to IndexMaintenanceFilter.NORMAL).
With the new Index.predicate field, change the logic to be:
If the user had explicitly set his own IndexMaintenanceFilter, use it.
Else if the index predicate was defined, use it.
Else use IndexMaintenanceFilter.NORMAL.
=> Use Index predicate when appropriate 

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/clientlog/KeySpaceCountTree.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpaceTreeResolver.java
Unfortunately, the diff is a bit hard to read. The basic change is that methods related to resolving that might get subclassed by a more specific layout are on the new class and no longer need an `FDBRecordContext` argument. And the methods that remain on the tree take a resolver instead of a context.
=> Resolves #2121: Refactor KeySpaceTreeResolver out of KeySpaceCountTree

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/SelectExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/ExistsPredicate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/Placeholder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/PredicateWithValueAndRanges.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/QueryPredicate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/RangeConstraints.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/SparseIndexTest.java
If we have a filtered index with a non-tautological filter, this index will be incorrectly considered by Cascades when subsuming a non-filtering select. This provides a fix for this bug and adds a test.
Fixes #2118
=> Avoid choosing filtered index for unfiltered scan

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanStringRepresentation.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/PlanStringRepresentationTest.java
This reverts the plan string for `RecordQueryMapPlan`s, which were accidentally changed as a part of #2119, to their older format to keep plan strings stable.
This fixes #2132.
=> Fixes #2132: Plan string changed for RecordQueryMapPlan

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexExpansionVisitor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ComparisonRange.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchInfo.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchedOrderingPart.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexLikeMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/WindowedIndexScanMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/PredicateWithValueAndRanges.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryAggregateIndexPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/GroupByTest.java
Currently we expose placeholders only in the upper `SelectExpression` of the aggregate index match candidate. This matches well with group-by queries that have a predicate on the grouping column(s) in its upper `SelectExpression`. However this fails to match when the group-by query has a predicate in its underlying select because we do not expose any placeholders in the corresponding `SelectExpression` of the aggregate index plan.
This PR addresses this issues by exposing the _same_ set of placeholders in both `SelectExpressions` of the aggregate index plan. I had to do some adaptations to make this work:
* In `MatchInfo`, when trying to merge the parameter binding map, it is now cognizant to the fact that a binding could be associated with multiple `ComparisonRange`s and it attempts to …
=> Allow placeholders in aggregate index match candidate's underlying SelectExpression

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexQueryPlan.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenePlannerTest.java
This adds an explicit implementation of `toString` to the Lucene query plan that calls the right method of a the plan string representation class in order to simulate the old behavior (which was to inherit its `toString` from `RecordQueryIndexPlan`). The other thing that occurred to me was to update `visitDefault` so that it would do something else if we were in `visitDefault` but had a `RecordQueryIndexPlan`. This could either be specific to a `RecordQueryIndexPlan`, or it could walk up the class hierarchy until it found a plan with a known `visit` implementation. I went with the approach I did because it seemed like this approach gives classes outside of `fdb-record-layer-core` the best ability to chose their own `toString` implementations, but there is some waste. In particular, each …
=> Fixes #2136: Lucene query plan toString results in StackOverflow

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/VersionKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/QueryRecordFunctionWithComparison.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PromoteValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ScanWithFetchMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexExpansionVisitor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/ValueMatchers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PushReferencedFieldsThroughFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PushReferencedFieldsThroughSelectRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/FieldValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordConstructorValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordTypeValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RelOpValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VersionValue.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSimpleQueryGraphTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBVersionsQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/TypeRepositoryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordConstructorValueTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/PlannerRepl.java
Support for record versions and version indexes are added to the Cascades planner. This does a number of things:
1. A new primitive type, `VERSION`, is added to the type system. This type is used to represent an `FDBRecordVersion`, with some promotion rules to allow it to be compared to `byte[]` and `String` types. It is serialized to `bytes` when included as a field in a message (for example, when included as return type field in a QGM).
1. The existing `VersionValue` is modified to be evaluatble. It now takes a quanitifier and evaluates the version on the record backed by the quantifier.
1. Matching on `version` indexes is added to the index/query matching logic. As `version` indexes behave identically to `value` indexes during query time, this re-uses the matching logic for `value` …
=> Resolves #2089: Cascades planner should support queries on record version

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Index.java
This provides an additional copy constructor for the `Index` that takes an additional `IndexPredicate`. This is necessary for cases where we want to enrich the index with an additional predicate that is constructed externally and not e.g. provided directly through the index metadata protobuf.
=> Additional copy constructor for `Index`

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutputTest.java
Moving from 16K to 1k.
Simple write reads 99K of data vs. 570K when block size is reduced.  This is for 10K emails. 
This will require indexes to be rebuilt that were built before to take advantage of the optimization.
Write Execution 16K
`2023-06-07 15:07:56,074 [INFO] c.a.f.r.p.f.FDBRecordStoreTestBase - committing transaction bytes_deleted_count="1814" bytes_fetched_count="570024" bytes_read_count="569910" bytes_written_count="11679" check_version_count="1" check_version_micros="19010" close_context_count="1" commit_count="1" commit_micros="38807" commits_count="1" commits_micros="9549" compress_serialized_record_count="1" compress_serialized_record_micros="354" decompress_serialized_record_count="1" decompress_serialized_record_micros="45" deletes_count="35" …
=> Shrink Lucene Block Size to save in read overhead... #2155

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCodec.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPointsFormat.java
Reading from 10K sample emails "session". 
Read Before:
2023-06-08 16:29:49,873 [INFO] c.a.f.r.p.f.FDBRecordStoreTestBase - committing transaction bytes_fetched_count="151822" bytes_read_count="151726" check_version_count="1" check_version_micros="3009" close_context_count="1" commit_read_only_count="1" commit_read_only_micros="462" commits_count="1" commits_micros="291" empty_scans_count="1" fetches_count="3" fetches_micros="32285" get_read_version_count="1" get_read_version_micros="2040" get_scan_range_raw_first_chunk_count="1" get_scan_range_raw_first_chunk_micros="2888" jni_calls_count="250" load_record_store_index_meta_data_count="1" load_record_store_index_meta_data_micros="2881" load_record_store_info_count="1" load_record_store_info_micros="3001" load_record_store_state_count="1" …
=> Make PointsFormat Codec Lazy to only read when needed for queries #2158

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCodec.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedStoredFieldsFormat.java
Making StoredFieldFormat lazy to reduce the amount of reads needed during a simple write.
=> Make StoredFieldFormat lazy to limit data read during simple insert #2163

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundReader.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java
This removes a read to block 0 for compound files when we do a single row insert.
=> LuceneOptimizedCompoundReader always reads block 0, even when not needed... #2169

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCodec.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedDocValuesFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPostingsFormat.java, fdb-record-layer-lucene/src/main/java/org/apache/lucene/codecs/lucene84/LuceneOptimizedPostingsReader.java
This allows the two implementations to work on a per field basis and to not fetch blocks for positional elements unless they are needed to answer the query.
=> Make DocValues and PostingsFormat PerField Formats Lazy and the PostingsReader Lazy for positional elements #2171

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCodec.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedLiveDocsFormat.java
More lazy reading for the single insert use case.
=> LiveDocsFormat will perform a read of the bit vector in the case where we are doing a simple insert. #2178

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimized60FieldInfosFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCodec.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundReader.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedFieldInfosFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBLuceneFileReference.java, fdb-record-layer-lucene/src/main/proto/lucene_file_system.proto
FieldInfo information will be once per unique entry vs. one per segment in the directory.  As the implementation scales to 100's of segments, we do not want to have to read 100's of entries with the same information in it.  When the index writer is initialized, it has to look at the discrete field infos to make sure it provides correct field ordering.
=> FieldInfosFormat requires each segment to fetch their schema definition #2182

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
The metric was created but an old metric was used for the call. :(
=> Actually use LUCENE_READ_SCHEMA metric #2188

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/idformat/LuceneIndexKeySerializer.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/idformat/LuceneIndexKeySerializerTest.java
- Improve logging for serialization errors: Log as `WARN`, add throttling to reduce floods of log messages
- Reuse the serializer: Make the `key` a parameter to the serialization methods, construct serializer with only format at index maintainer constructor.
The attempt to look at the `oldWriter.deleteDocument` return value will not work since the return value is a `sequenceNumber` and not a count of the found documents. Will have to look for another way to validate the deletion.
=> Resolve #2194: Technical debt from binary point implementation

docs/ReleaseNotes.md, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/DualPlannerExtension.java
When running a parameterised test suite such as `FDBOrQueryToUnionTest`, IntelliJ does not render the name of the parameterised dual-planner test correctly when Cascades is used. Here an example of running `testOrQuery5`:
This makes it difficult to figure out e.g. under which configuration(s) did a test fail.
This provides a fix for that by adding a display name decorator of `TestTemplateInvocationContext` (called `DualPlannerTestInvocationDisplayNameDecorator`) which delegates to the underlying `ParameterizedTestInvocationContext` context by adding either `[cascades]` or `[heuristics]` to test name instead of creating a vanilla `TestInvocationContext` that ignores the (parameterised) test display name completely and displays only `[cascades]` instead.
Here is how IntelliJ now outputs the …
=> Fix parameterized dual-planner test display name

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCodec.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPostingsFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBLuceneFunctionalityTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBLuceneTestIndex.java
This will: 
1. Revert commit 3918fd5b184b222571c34317351a85132340476d (which doesn't work as expected - apparently because often a default constructor is called via the `@AutoService(PostingsFormat.class)`. 
2. Add static var to control `checkIntergrity` +  allow callers to set it for all future transactions
Note to reviewer: the use of a static var is ugly. Please consider that a quick n dirty way to test skipping the checksums test. If it does works we'll find a better way to do it.
=> Lucene skip data integrity static

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundReader.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java
Created new events for Merge and CreateOutput.
Some metrics (delete/rename) have a WAIT event associated with them. The event doesn't always trigger (likely due to the use of context.asynctosync) so a counter event was added for them.
=> Resolve #2210: Add more metrics to Lucene.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTypedRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/storestate/FDBRecordStoreStateCacheTest.java
A new record store configuration parameter is added. It can be configured to instruct `checkVersion` to update the `cacheability` flag. If the store header is alreadyin the desired state, then no update is performed. In addition, this allows the user to skip updating the flag if the store is pre-existing, which was the old behavior, and which is still important during roll outs. In particular, if the same set of instances are configured to operate on the same store, and some of them are configured to set cacheability to `true` while others to set it to `false`, then operations from the one set will always step on operations from the other set. To avoid that, one can first set the parameter to ignore existing stores and then make a second change to start updating existing stores again. …
=> Resolves #2203: Allow for setting the store state cacheability during checkVersion

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByRecords.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingCommon.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java
Decreasing limit, let new value be  0.9 * the number of records scanned during the failure.
=> Resolve #2106: OnlineIndexer: indexingThrottle: limit handling

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java
Example log message
2023-07-12 15:14:32,464 [TRACE] c.a.f.r.l.d.FDBDirectory - readBlock block_number="25" compression_supposed="true" encryption_supposed="false" file_name="_5c.cfs" file_reference="_5c_RLLucene84_0.tim" subspace="Subspace(rawPrefix=\x15>\x15'\x15\x1d\x15\x02\x02Simple$text_suffixes\x00)"
Notice how it shows just not the file "_5c.cfs" but also the file_reference "_5c_RLLucene84_0.tim".
=> Support ReadBlock Tracing not just from the file (.cfs) but to the reference (.fnm, etc.). #2226

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CascadesPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ConstraintsMap.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/GroupExpressionRef.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PlannerRuleSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/explain/NodeInfo.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/LogicalUniqueExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/RelationalExpressionMatchers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/CardinalitiesProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementUniqueRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PredicateToLogicalUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PushReferencedFieldsThroughUniqueRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PushRequestedOrderingThroughUniqueRule.java
This fixes the problem of potentially introducing duplicates when splitting a disjunction into a union as explained in #2230. The fix mainly introduces a new `LogicalUniqueExpression` that sits on top of each union leg and can only be implemented when underlying expression is distinct with primary key. a `LogicalDistinctExpression` is put on of the union expression to make sure we eliminate any duplicates.
This fixes #2230.
=> Avoid introducing duplicates when splitting disjunction to union

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/PipelineOperation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryAbstractDataModificationPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryDeletePlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryInsertPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUpdatePlan.java
The update pipeline is not thread safe and should not use a default size of 10
=> Constrain pipeline size to 1 for UPDATE operations

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedFieldInfosFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java
Make the byte[] schema perform a non-atomic cache population.
Remove the parsed fieldInfo caching (so it always reads from the byte[] cache).
=> Resolve #2234: Fix readSchema deadlock.

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/SemanticException.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VariadicFunctionValue.java
Introduces a new semantic exception that is thrown when a Variadic Function is not defined for a type. This replaces throwing "ARGUMENT_TO_ARITHMETIC_OPERATOR_IS_OF_COMPLEX_TYPE" which was more explicit but used for function values. 
By throwing specific errors, it can be better handled 1-1 in the upstream with their native error codes
=> change error code when function not defined

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
it used supplyAsync, but always called get immediately on the result
=> Resolves #2237: Remove unnecessary async code from writeSchema

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CascadesPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchInfo.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MetaDataPlanContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PrimaryScanMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexScanMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/WindowedIndexScanMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/RecordQueryPlanMatchers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/AbstractDataAccessRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/DataAccessRule.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBModificationQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSimpleQueryGraphTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBVersionsQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/GroupByTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/SparseIndexTest.java
Indexes can be read top down or bottom up. The reverse scan requirement should not come from indexes but from the query itself
=> Get scan order from query rather than indexes

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/FunctionKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/text/TextTokenizerRegistryImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexMaintainerRegistryImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/FunctionCatalog.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/util/ServiceLoaderProvider.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/PlannerRepl.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAnalyzerRegistryImpl.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/LuceneQueryParserFactoryProvider.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/synonym/SynonymMapRegistryImpl.java
This allows the standard Java ServiceLoader to replaced by another one for example a dependency injection aware version of ServiceLoader.
=> Resolve #2265: Provide support for alternative implementations of ServiceLoader for example for Dependency Injection

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java
It might make sense to throw some sort of IOException instead, but for now, sticking with RecordCoreException.
=> Resolves #2291: Throw RecordCoreException if there is no reference

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/TupleFieldsHelper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/IndexKeyValueToPartialRecord.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/IndexKeyValueToPartialRecordTest.java
`FieldCopier.copy` is not thread-safe. This could cause problems in situations where we have multiple threads trying to reuse a physical plan but with slight differences in their record descriptors.
**Setup**
-: We have two threads, `T1` and `T2` and a physical plan that comprises an operator that leverages `IndexKeyValueToPartialRecord` such as `RecordQueryCoveringIndexPlan`.
- `T1` is operating on a version of record store metadata that contains the following record:
```
message R1 {
optional int32 x = 1;
}
```
- `T2` is operating on another record store metadata that contains an _evolved_ version the same record:
```
message R1 {
optional int32 x = 1;
optional int32 y = 2;
}
```
Let's call this message `R1'` for clarity.
Here is a schedule that shows depicts the race-condition (scroll …
=> Make `FieldCopier.copy` thread-safe

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java, fdb-record-layer-lucene/src/main/java/org/apache/lucene/index/StandardDirectoryReaderOptimization.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
Additionally make it robust to running out of executor threads (which will be much less likely with the limit).
Fixes #2309.
=> Limit parallel open of segment readers to settable number of threads.

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/RTree.java, fdb-extensions/src/test/java/com/apple/foundationdb/async/RTreeModificationTest.java, fdb-extensions/src/test/java/com/apple/foundationdb/async/RTreeScanTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/TupleRange.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/DimensionsKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/MultidimensionalIndexScanBounds.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/MultidimensionalIndexScanComparisons.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/MultidimensionalIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/MultidimensionalIndexMaintainerFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanOrderingKey.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/ScanComparisons.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ComparisonRange.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ComparisonRanges.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/RecordQueryPlanMatchers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryAggregateIndexPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIndexPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryPlanWithComparisons.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryScanPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/MultidimensionalIndexTest.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java
- heuristic planner support for multidimensional indexes
- refactored `ScoredPlan` into `ScoredInfo<T>` which forms the base for a _compatible_ new `ScoredPlan` and a new `ScoredMatch` which is now used in place of `ScoredPlan` for the call hierarchy underneath of `planCandidateScan()` (which has been renamed to `matchCandidateScan()`)
- `AndWithThenPlanner` is kept largely identical for regular value indexes
- `MultidimensionalAndWithThenPlanner` for multidimensional indexes
- filter nodes during a scan based on a TupleRange on the suffix key part that is only applied if the R-tree sub tree only contains data using the same point coordinates
- lots of new tests
- tests adapted to also test plans generated by the planner
- dumping of R-tree information across transactions
- fixed a bug in …
=> addressed #2305: multidimensional index planning in the heuristic planner with refactored `ScoredPlan`

docs/ReleaseNotes.md, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchSplitRecordsTest.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LazyCloseable.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LazyOpener.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedDocValuesFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedLiveDocsFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPointsFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPostingsFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedStoredFieldsFormat.java, fdb-record-layer-lucene/src/main/java/org/apache/lucene/codecs/lucene84/LuceneOptimizedPostingsReader.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyOpenerTest.java
We were wrapping them in UncheckedIOException, this creates two new helpers `LuceneOpener` and `LuceneCloseable` that make it easier to unwrap the exception appropriately, and close the lazily opened object correctly.
=> Resolves #2293: Rethrow original IOExceptions in lucene code

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/util/TrieNode.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBModificationQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelperTests.java, fdb-record-layer-core/src/test/proto/test_records_transform.proto
The hash code calculation of the `RecordQueryAbstractDataModificationPlan` is not stable. This is causing discrepancies in the optimiser choosing optimal `UPDATE` plans pseudo-randomly when multiple equivalent alternatives exist and the plan hash code is used as a costing tie-breaker.
This happens because the `MessageHelpers#CoercionTrieNode` class does not override `equals` and `hashCode`, despite it being used in `computeHashCodeWithoutChildren` of `RecordQueryAbstractDataModificationPlan`.
The provided fix implements `hashCode` and `equals` properly for this class, and adds a number of unit tests for equality and hash code calculation for `MessageHelpers#CoercionTrieNode` and `MessageHelpers#TransformationTrieNode`, it also adds an integration test for that examines the stability of …
=> Fix unstable in hash code of `RecordQueryAbstractDataModificationPlan`

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBTieredMergePolicy.java
Add `LUCENE_FIND_MERGES` matric.
=> Resolves #2333: Lucene: add metric to measure Lucene's find merges

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/InsertExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/UpdateExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryAbstractDataModificationPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryInsertPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryUpdatePlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBModificationQueryTest.java
=> mutateRecord in RecordQueryAbstractDataModificationPlan fails when underlying metadata ref changes.

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/LuceneScaleTest.java
1. An option to disable the index, or build it at the start of the test to more quickly create large stores
2. Only update the search words if doing a command that uses them, as this can take quite some time on large accounts
3. Some code to dump a timer into a json file. This isn't currently used, but I wanted it in some profiling investigations I was doing, and figured it would be worth sharing
=> LuceneScaleTest: better support for large stores

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingCommon.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordPlannerTest.java
Now, when we go to index a record of a synthetic type, we only go through the process of generating a plan if there is at least one non-disabled index defined on it. Previously, we would generate the plan if there was any index defined on it, and then we would filter out any types without any non-disabled indexes later. The logic for that later filtering could result in a null pointer exception, though, so this updated approach aligns what gets planned with what is actually necessary to execute. This also can save on planning time if there are disabled indexes.
This fixes #2377.
=> Fixes #2377: NPE during maintenance of synthetic indexes if some types have only disabled indexes

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteQueryClause.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneAutoCompletedMatchesTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
**Motivation**
To auto-complete phrases with stop words in them. Example: "united states of ameri" would need to match "United States of America" with "of" being indexed as a stopword
**Modification** 
Use Lucene parser when parsing the search input into query to preserve the positions of the stopwords and turn them into Lucene gaps for matching.
Plus, some more enhancement to matching when the phrase ends with a stopword
**Results**
The example mentioned works.
=> AUTO-COMPLETE does not complete phrases which contain stop words in them #2380

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanOrderingKey.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java
This adjusts the way the plan ordering key is constructed for unions and intersections so that it can accept additional columns in the order. Effectively, in the case where you have an index on `[a, b, c, d]` with an equality on `a`, a disjunct of equalities on `b`, and a primary key `k` (the hypothetical raised in the original issue), then this will construct an ordered union between multiple scans of the index (one leg for each member of the disjunction on `b`) and will use the comparison key `[c, d, k]` to ensure that the results are processed in an expected order.
This resolves #2336.
=> Resolves #2336: PlanOrderingKey.mergedComparisonKey too strict about fields between requested ordering and primary key

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/DualPlannerExtension.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryPlanFullySortedTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryPlanResultTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/PlanComplexityExceededTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestUtils.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneQueryIntegrationTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneStoredFieldsTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/FDBLuceneHighlightingTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/LuceneScaleTest.java
This updates the `DualPlannerTest` extension so that parameterized tests will run with both planners. This adjusts the work done in #2022 so that the Cascades planner is configured during test execution, which is what was missing with the previous approach. The rest of the changes here are in response to that, mainly fixing up the `FDBOrQueryToUnionTest` so that (1) tests have nice names that are easier to debug and (2) plan assertions that were failing are fixed.
This fixes #2353.
=> Fixes #2353: DualPlannerTests are only running old planner if also marked as parameterized

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanOrderingKey.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlannerConfiguration.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTestBase.java
In order to avoid breaking continuations of plans affected by #2336, this adds a planner configuration flag that allows the user to effectively revert to the old behavior. This property is set to the old behavior by default, letting users to opt-in to the new behavior if they know it is safe for their deployment. This also includes a bit of a revamp of the or query tests to make sure all of the configurations get tested. There were two queries that had their plan hashes updated in #2350 (resolving #2336). The plan hashes in this PR for the legacy mode match the old plan hashes from before #2350 went in.
This fixes #2408.
=> Fixes #2408: Add planner configuration property to control union ordering key behavior

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/LuceneScaleTest.java
Adding test options:
Option 1: Set merge max size
Option 2: Set merge probably - this is meant to emulate accumulation of few required merges before actually performing the merge.
=> Resolve #2410: LuceneScaleTest: Add merge options to test configuration

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePrimaryKeySegmentIndex.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/TestFDBDirectory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
The purpose of this PR is to prevent developers for accidentally misusing the caller context of FDBDirectory.
=> Remove references of caller context to avoid future misuse

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestUtils.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneStoredFieldsTest.java
Lucene stored fields test was flaky when it was expecting documents in segments that were the results of a merge.
Added forced merge and `LUCENE_MERGE_SEGMENTS_PER_TIER` as well as additional fragmentation to the segments such that a merge is forced and the result is predictable.
=> Resolve #2401: Make test less flaky

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneLogMessageKeys.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockFactory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
* Move FIleLock code to FDBDirectoryLock
* FDBDirectoryLock: add test
* AgilityContext: add test
=> Resolve #2415: Lucene: cross transactional merges - extra cleanup

.idea/codeStyles/Project.xml, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/LuceneScaleTest.java
A few improvements to LuceneScaleTest, and a change to make `LucenOnlineIndexingTest.luceneOnlineIndexingTest6` less flaky (saw a failure https://github.com/FoundationDB/fdb-record-layer/pull/2430)
=> Test improvements

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/PermutedMinMaxIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/PermutedMinMaxIndexMaintainerFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexExpansionVisitor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexExpansionVisitor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/FieldValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/NumericAggregationValue.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/PermutedMinMaxIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBPermutedMinMaxQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSimpleQueryGraphTest.java
This does a few things:
1. It defines what index aggregate functions the `PERMUTED_MIN` and `PERMUTED_MAX` functions can evaluate. Effectively, this communicates with consumers that those indexes can be used to satisfy the `min` and `max` function. It also provides corresponding implementations of those functions using the index.
1. The `planCoveringIndex` method in the maintainer is updated to allow for scans over the index that cover the unpermuted grouping columns.
1. Match candidates for the index with the appropriate contents and the appropriate ordering are now generated for consumption by Cascades.
1. Ordering logic is updated so that the ordering keys are matchable for aggregate indexes. For most indexes, this follows the order of the key expression, though the `PERMUTED_MIN` and …
=> Resolves #2418: Integrate the PERMUTED_MIN/_MAX index types into the query planners

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PromoteValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ConstantObjectValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/OfTypeValue.java
This improves the type checking logic done in `OfTypeValue` and `ConstantObjectValue` especially around array type.
This fixes #2440.
=> Fixes for `OfTypeValue` and `ConstantObjectValue`

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ConstantObjectValue.java
The semantic check is not necessary considering the `ConstantObjectValue` can be created with a `Any` type in scenarios where the Java object value can correspond to any binding given by the user. The check for typing is guaranteed to be done anyway in a `OfTypeValue` on top. Therefore, this check is not necessary.
=> `ConstantObjectValue` replace semantic check with verification in case of `null` value

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneCursorContinuation.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java, fdb-record-layer-lucene/src/main/proto/lucene_continuation.proto, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
This update adds support for seamless cross partition Lucene queries with continuation.
=> RESOLVES #2432: Add support for cross partition Lucene queries

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteQueryClause.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
Issue: https://github.com/FoundationDB/fdb-record-layer/issues/2450
=> Fix: Phrase auto-completion with leading stop words does not find expected match 

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedFieldInfosFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FieldInfosStorage.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedFieldInfosFormatTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPointsFormatTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedTermVectorsFormatTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/TestingCodec.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutputTest.java
This resolves three issues:
1. #2455 - If the `FDBDirectory` is wrapped in a `NRTCachingDirectory`, we may end up only writing the output to `NRTCachingDirectory`, and not syncing it to the underlying `FDBDirectory`. This may only be a test issue, but the resolution is to call `sync`, which is a no-op in `FDBDirectory`, so this seems worthwhile.
2. Similar to #2455 there is an issue with not syncing while copying the field infos id to the `.cfe` when creating a compound file. This includes a fix, and adds a seed that reproduces it.
3. #2457 - If Lucene closes an FDBIndexOutput twice it will result in an NPE. We now make sure that doesn't happen. This is brought into this PR, because without this fix, the seed originally noted in #2455 cannot be included, as the test still fails.
=> Resolves #2455 and Resolves #2457: fixes some random Lucene test failures

build.gradle
This configures the Java builds to set the release option to fix the byte code to JDK 11. This will allow us to move our build instance forward to JDK 17 without needing to worry about breaking compatibility with any JDK 11 consumers of the project. This gets us ready for #2360
=> Set release option during Java builds

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneLogMessageKeys.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestUtils.java
- before index merge, partitions are examined for the count of documents they contain. If above a high watermark, the oldest N documents will be moved to an older partition. If no older partition exists, or if the N documents would make the older partition go over the high watermark, a new partition will be create and docs moved there.
- N is configurable via a property. It should be small enough so that the entire move can be performed in a single transaction. It is currently set to 10.
=> RESOLVES #2465: Support rearranging documents between Lucene partitions

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptions.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java
This updates the logic in `FDBExceptions::wrapException` to avoid an error with the message "Unbalanced key/value logging info". This was ultimately caused by a problem where the wrong constructor was being selected when creating the `RecordCoreInterruptedException`, so this adds a cast so that the signature now aligns with the correct constructor.
This fixes #2485.
=> Fixes #2485: FDBExceptions::wrapException incorrectly wraps InterruptedExceptions

docs/ReleaseNotes.md, fdb-extensions/src/test/java/com/apple/test/RandomizedTestUtils.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneLogMessageKeys.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java, gradle/testing.gradle
The main change here is that this uses multiple transactions to move documents between partitions. It also ensures that merge happens on all partitions.
This is a rather simplistic implementation, with a fixed property for how many to move per transaction.
In order to test all the permutations this adds some randomized tests that create a bunch of random data, in a single, most-recent partition and then runs the mergeIndex to move them between partitions.
It also does a few other things:
1. The search used in getOldestNDocuments was not right, and wasn't sorting properly
2. The JOINED index used in tests has the sort added
3. It changes the tuple at the beginnig by doing `groupKey.add()` rather than using a nested tuple.
=> Resolves #2491: Use multiple partitions to perform rebalancing

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexExpressions.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/LuceneLocaleTest.java, gradle/testing.gradle
To help protect us in the future, I also changed it so that if you run with tests.includeRandom it will run with a random locale.
=> Resolves #2503: Use Locale.ROOT when parsing lucene queries

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/synthetic/UnnestStoredRecordPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/UnnestedRecordTypeTest.java
This updates the unnesting plan so that we should not generate records if we don't match all of the constituents. The way that this works is that:
1. There is a tree representing the relationship between each constituent and its child constituents
1. Each node has some stored record value, and then each child is mapped to a list of values (computed by evaluating the nesting expression on the node's record)
1. To get the full set of synthetic records, we need to compute the cross-product of the set of unnested records coming from each node
1. This cross product is computed by keeping iteration state in each node, and then incrementing each child, rolling over to incrementing the next child once we've exhausted each one
This updates the algorithm by:
1. Instead of keeping a map of current …
=> Fixes #2512: Unnested indexes generate an additional element with for null

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreDeleteWhereTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/UnnestedRecordTypeTest.java, fdb-record-layer-core/src/test/proto/test_records_double_nested.proto
When we delete all elements of a type, we need to modify the check so that it will remove all synthetic recorsd that reference the deleted base elements. This means modifying the predicate slightly. In particular, if there's a delete predicate like:
```java
Query.field("foo").equalsValue("bar")
```
And there's an unnested record type where the parent constituent is named `p`, then the correct predicate on the unnested record is:
```java
Query.field("p").matches(Query.field("foo").equalsValue("bar"))
```
This PR makes a few changes:
1. It makes sure that we gather up the indexes on synthetic types to check whether they are valid. This used to not work for cases where we were indexing only a single record type.
1. It validates that it can modify the predicate. For instance, if the index is …
=> Fixes #2502: DeleteRecordsWhere should modify predicate for synthetic record types

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/UnnestedRecordType.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByIndex.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingCommon.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildJoinedIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildRankIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildSumIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildUnnestedIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildValueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildVersionIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTestRecordHandler.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTestSimpleRecordHandler.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/UnnestedRecordTypeTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordPlannerTest.java, fdb-record-layer-core/src/test/proto/test_records_1_evolved_with_map.proto, fdb-record-layer-core/src/test/proto/test_records_join_index.proto, fdb-record-layer-core/src/test/proto/test_records_map.proto
This PR contains the following changes:
1. The main thing is updating how synthetic records are handled by the scrubber so that they handle synthetic records properly. As it turns out, this logic was divorced from the logic in the builder, which is why the scrubbers (and not the builder) had this issue
2. Modify the way that `checkVersion` handles synthetic records. Previously, it could get tricked into thinking a synthetic type had no records as it would scan the primary key space looking for records prefixed by the record type key of the synthetic record type. This modifies the check so that it looks at the underlying stored record types instead
3. Adds a bunch of tests around index builds for synthetic record types. Working on these tests led me to those other two issues. There's also …
=> Fixes #2513: Extra errors being reported by the scrubber for indexes on Unnested Record Types

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/TypeRepository.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/PromoteValue.java, fdb-record-layer-core/src/main/proto/record_query_plan.proto
The logic for handling coercion of `Type.Enum` is missing, this fix adds strict coercion rules for `Enum` type described as the following:
For a given `Enum` `E1`, we can perform the following coercions:
* nullable `E1` to nullable `E1` (enum to itself)
* not nullable `E1` to not nullable `E1` (enum to itself)
* not nullable `E1` to nullable `E1` (this is fine since the nullable `E1`'s domain can accommodate for all elements in `E1`.
It also adds a new promotion rule that accepts promoting `String` type to `Enum` type, this is useful for e.g. enabling the insertion of `Enum` values in an `INSERT` statement as a normal `String` literal.
This fixes #2517 .
=> Fix `Type.Enum` coercion logic

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/UnnestedRecordTypeTest.java
This updates the logic used to build indexes during check version so that it no longer takes the record type list from `getIndexesSince`. This means that the online indexer recalculates the list of record types it needs, which allows it to properly note whether the index is on synthetic records or not. The new test used to fail before this change.
This fixes #2350.
=> Fixes #2530: Synthetic records use wrong configuration if built during checkVersion

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlannerConfiguration.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/RecordQueryPlanMatchers.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedRepeatedQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSortQueryIndexSelectionTest.java
This takes basically the same approach that was taken for #2350, but this time applying it to `InUnion` plans rather than just regular union plans.
This change is guarded behind a planner configuration plan. This is necessary because the new algorithm can choose new ordering keys for the in-union, and so the user needs to be able to control its roll out. This is to mirror what we did with #2408.
This resolves #2493.
=> Resolves #2493: PlanOrderingKey too strict when computing order for In union

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanOrderingKey.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedRepeatedQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTestBase.java
This updates the handling for key expressions in `PlanOrderingKey` so that if the same expression appears multiple times, we only match it once.
This fixes #2462. That work was started in #2453, but it still had some edge cases where if none of the key expressions were in the equality prefix, the logic wasn't quite right.
I also added (in a separate commit) logic that fixes #2469. This is here mainly to avoid too many conflicts from updating the same bit of code, though it's conceptually separate.
=> Fixes #2462: PlanOrderingKey tripped up if the same expression appears multiple times

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/PermutedMinMaxIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/PermutedMinMaxIndexTest.java
The core issue was that there was an early-out in the `PermutedMinMaxIndexMaintainer`'s implementation of `updateIndexKeys`. This updates the loop so that it no longer early outs, and thus all entries will get included in the index. Some care has been taken so that if the same record produces multiple entries in the same group (which can happen if the repeated field is in the grouping key and the same value appears multiple time in the repeated field OR if the repeated field is in the aggregate value), then only the most extreme value for the record is used to determine what new entries to add to the permuted space. All values still get added to the primary index space, though, so that part of the index should behave exactly like a normal value index on the whole key (i.e., ignoring the …
=> Fixes #2543: Permuted min/max indexes on keys producing duplicates only index the first entry

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexExpansionVisitor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Column.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/GraphExpansion.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/KeyExpressionExpansionVisitor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/UpdateExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedRepeatedQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBPermutedMinMaxQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreRepeatedQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSimpleQueryGraphTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/GroupByTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/MessageTransformationTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/ValueSimplificationTest.java
This updates the way that graph expansions get combined during index match candidate generation so that field protobuf indexes are not preserved. This updates the `normalizeFields` logic in `Type.Record` so that if any of the field indexes are unset or contain dupes, then we always set the field indexes (whereas before, we would preserve those indexes if they were there, even if we'd identified duplicate field indexes in the type).
This also introduces a new helper method to make it easier to write `Column`s without needing to repeat the type and uses that new abstraction in some existing code paths.
This fixes #2552.
=> Fixes #2552: Nested fields can preserve field protobuf indexes incorrectly in index expansion

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanOrderingKey.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedFieldQueryTest.java
This reverts #2557 because of the issue alluded to in #2563.
=> Revert #2557: FailedInJoinAsUnion support for unordered distinct

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java
Revert much of e411e1fee4d27d04e03b5acb0dd60b5efd178b32 and instead do it all in the planner. The previously affected test is now unchanged, too.
=> Redo #2557 more safely

fdb-record-layer-lucene/fdb-record-layer-lucene.gradle
Until #2480 is resolved, we don't want to run the lucene framework tests with random seeds, or the nightly ones to avoid the noise.
=> Disconnect lucene framework tests from record layer gradle properties

build.gradle, fdb-record-layer-lucene/fdb-record-layer-lucene.gradle, gradle/testing.gradle
The default test output always uses the name, so you end up with:
```
LuceneHighlighterTest > highlightsSpecialCharacterTerm(String, Analyzer, Analyzer, String) > com.apple.foundationdb.record.lucene.highlight.LuceneHighlighterTest.highlightsSpecialCharacterTerm(String, Analyzer, Analyzer, String)[1] STARTED
LuceneHighlighterTest > highlightsSpecialCharacterTerm(String, Analyzer, Analyzer, String) >
com.apple.foundationdb.record.lucene.highlight.LuceneHighlighterTest.highlightsSpecialCharacterTerm(String, Analyzer,
Analyzer, String)[1] PASSED
```
Which is not great, this adds our own logging that renders the display name. So the above would become something like:
```
LuceneHighlighterTest > highlightsSpecialCharacterTerm(String, Analyzer, Analyzer, String) > AlphaCjk-Synonyms,Ϲ STARTED …
```
=> Display display names in gradle test output

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
- cause: typo in `LucenePartitioner.isNewerThan()`
=> FIXES #2580: from is greater than to in a partition info

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePrimaryKeySegmentIndex.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java
This introduces a test that reproduces the #2573
However, it also found a bunch of other issues:
- #2570
- #2574
- #2575 
It also has some issues because the merge doesn't reliably fail for the ones where it is supposed to. I'm hoping that getting it to fail for those too is just a matter of adjusting constants.
I thought having this in, and disabled would be useful for anyone working on the other issues it is hitting (although those fixes should have more targeted tests)
=> Flaky merge test

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBTieredMergePolicy.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/MergeUtils.java
The existing observability shows us that the exception is in the pre-commit hook, but we don't know why that is being created with NonAgile. Hopefully this will help.
Once we figure this out, we should remove this additional logging.
=> Additional information around when we find merges in a non-agile context

fdb-extensions/src/test/java/com/apple/test/RandomizedTestUtils.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildGroupedCountIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildJoinedIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildRankIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildSumIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildUnnestedIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildValueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildVersionIndexTest.java
The index build tests already largely randomly generated their data. This updates their source of seeds so that they take a random seed as a parameter, and it configures them to run with additional random seeds if randomized tests are enabled.
This resolves #2582.
=> Resolves #2582: Randomize index build tests

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
A quick typo fix for https://github.com/FoundationDB/fdb-record-layer/pull/2594
=> Resolve #2575: Lucene file lock may not be cleaned up in a failed merge

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java
I couldn't figure out how to make a commitable test. The only thing I came up with was to inject some sleep code in `mergeIndexNow`. Namely this:
```diff
private void mergeIndexNow(LuceneAnalyzerWrapper analyzerWrapper, Tuple groupingKey, @Nullable final Integer partitionId) {
final AgilityContext agilityContext = getAgilityContext(true);
final FDBDirectoryWrapper directoryWrapper = getDirectoryWrapper(groupingKey, partitionId, agilityContext);
+        long stopMillis = System.currentTimeMillis() + TimeUnit.SECONDS.toMillis(10);
try {
directoryWrapper.mergeIndex(analyzerWrapper, exceptionAtCreation);
-            agilityContext.flush(); // TODO: remove this flush if directory resource is being closed without delay after merging
+            while (System.currentTimeMillis() < stopMillis) …
```
=> Fixes #2605: Flush the AgileContext before executing the merge

docs/ReleaseNotes.md, fdb-extensions/src/test/java/com/apple/test/TestConfigurationUtils.java, fdb-record-layer-lucene/fdb-record-layer-lucene.gradle, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenePrimaryKeySegmentIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedDocValuesFormatTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedNormsFormatTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPointsFormatTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPostingsFormatTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedStoredFieldsFormatTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedTermVectorsFormatTest.java, gradle/testing.gradle
There are a few things built in this:
1. Change the pipeline so that we aren't trying to merge multiple partitions at once
2. Make sure that we flush the AgilityContext after a merge
3. Create and close the `DirectoryWrapper` used by merges without involving the cache in the `DirectoryManager`
4. Clear AgilityContext state in a finally block
5. Rearrange metadata clear on a delete file so that the metadata won't ever be deleted until the data is deleted
=> Fixes #2600: Failed Lucene merges don't leave the index in a corrupted state

docs/ReleaseNotes.md, fdb-extensions/src/test/java/com/apple/test/RandomizedTestUtils.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/ListKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/RecordTypeKeyComparison.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/UnnestedRecordTypeTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedRepeatedQueryTest.java
…rimary key components incorrectly
This adjusts the way the planner interacts with primary keys using a `ListKeyExpression` to avoid matching them incorrectly during an index scan. There was an additional problem, related to matching the `RecordTypeKeyExpression`, where the physical operator had a bug in that it didn't resolve the record type in a way that handled synthetic record types, and that bug has also been addressed.
This fixes #2587 and this fixes #2588.
=> Fixes #2588: Index planning can match against nested synthetic type primary key components incorrectly

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java
It looks like if the runner fails to open a context or open the store it will result in a NullPointerException
=> Fixes #2609: Avoid NullPointerException in IndexingMerger

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java
1. In an unrelated effort I noticed issue #2618 which this fixes.
2. Inspired by that, I thought I would add some tests for the failure scenarios for accept/apply, and when running the tests, one of them stalled, and so I changed it to release the lock in a finally block (#2619)
3. I did an audit of the usages of the `lock` field and also ensured that if creation of a context failed it would unlock.
=> Cleanup AgilityContext failure logic

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestUtils.java
The current approach of putting the map in as a parameter makes it hard to read when looking at test results. This changes something like:
```
[1] {complex_multi_grouped_with_auto_complete_key=Index {'Complex$text_multiple_grouped_autocomplete', lucene}#2, spellcheck_index_complex_key=Index {'spellcheck_index_complex', lucene}, text_and_boolean_index_key=Index {'text_and_number_idx', lucene}, authoritative_synonym_only_lucene_index_key=Index {'synonym_index', lucene}, simple_text_with_auto_complete_key=Index {'Simple_with_auto_complete', lucene}#3, many_fields_index_key=Index {'many_fields_idx', lucene}, analyzer_chooser_test_lucene_index_key=Index {…, false
```
to:
```
[1] NonSynthetic
```
=> Change LuceneIndexTestUtils.luceneIndexMapParams to use an enum

fdb-extensions/src/test/java/com/apple/test/SuperSlow.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java, gradle/testing.gradle
These tests are mostly slow, and won't run as part of PRB, but add coverage that is otherwise hard to get since lucene is in charge of the merging logic
=> Add tests of lucene validity with many documents

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/test/FDBDatabaseExtension.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
PR #2604 removed the `checkForOpenContexts` method from `FDBRecordStoreTestBase`. Meanwhile, `LuceneIndexMaintenanceTest` added some explicit calls to that method in #2622 in order to validated that the `AgilityContext` did not leak contexts. This fixes the merge skew by exposing the method in the `FDBDatabaseExtension` and then referencing the method in the extension instead of in the super class.
=> Fix merge skew between #2604 and #2622

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneComparisonQuery.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneQueryFieldComparisonClause.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
This update optimizes a given search query that contains a `partition field` predicate, to take advantage of the partition metadata and therefore to direct the searcher to start in the right _partition_ where applicable.
In order for a `partition field` predicate to be considered, the following conditions **must** be true:
1. the predicate's comparison operator is **not** `NOT_EQUALS`
2. Either the predicate is the only one in the filter, **OR** it is the only `partition field` predicate in a conjunction filter
=> RESOLVES #2616: Select Partition based on query filter

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/RecordSerializationValidationException.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/RecordSerializer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializerJCE.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializerTest.java
There is a new method added to `RecordSerializer`, `validateSerialization`. This method takes both a `Message` and a serialized record, and it validates that calling `deserialize` on the bytes returns the original `Message`. In addition, there's a new configuration option on the `TransformedRecordSerializer` that allows it to be configured to validate a sample of serialized records (that sample configurable to "always" or "never") as this serializer has a somewhat more complicated story surrounding what it does to the bytes.
This resolves #2680.
=> Resolves #2680: Allow RecordSerializers to validate serialization

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/clientlog/FDBClientLogEvents.java, fdb-extensions/src/test/java/com/apple/foundationdb/clientlog/DatabaseClientLogEventsTest.java
The client log event format has not been updated since 7.2, so we are safe to update the log event known protocol versions to include FDB 7.3. There's not a great way of testing this without doing a more thorough job of updating our infrastructure to use a 7.3 server version and then run a few one off tests we have that try and parse these values. However, the Python script this is based on has been updated for 7.3 and it didn't need to make any changes from 7.2: https://github.com/apple/foundationdb/commit/321b77d8099f6ab3ec7c277139c0158abd823124
This resolves #2682.
=> Resolves #2682: Support protocol version 7.3 in ClientLogEvents

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializerTest.java
This adds a check to the `decompress` method to validate that the decompressed data coming from a transformed record serializer exactly matches the size encoded in the serialized data frame. This ensures that if there is some kind of error that results in the compressed blob either deserializing into something bigger or smaller than the original size, we notice and get a error right away (rather than, say, a protobuf deserialization error).
This resolves #2689.
=> Resolves #2689: Decompressing deserializer does not validate length of decompressed data

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializerTest.java
We addressed #2691 with #2690. One thing that was left untested was making sure that we could deserialize older data that was written without the checksum. This adds a backwards compatibility test that constructs serialized data that is purposefully written without a checksum, and it validates that it can still deserialize that data into the original record. So, this data won't have the benefit of the checksum, but our current deserializer won't hit problems if we run it against older data.
=> Test for #2691: Compressing serializer does not include checksum

gradle/testing.gradle
Example:
```
2024-04-22T14:02:07.233753Z RangeSetTest > concurrentlyExpandReadRange() STARTED
2024-04-22T14:02:07.357420Z RangeSetTest > concurrentlyExpandReadRange() SUCCESS (123ms)
```
This should make it easier to diagnose if there is a timeout on a build what was happening, and wether the test running at the end took a crazy long time, or if something else took a long time.
=> Add timestamp to test logs

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenePrimaryKeySegmentIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java
Since user operations are waiting for merge to finish over the “file lock” semaphore, the merge operation should not be running in BATCH priority but DEFAULT.
=>  Lucene: merges should run in default transaction priority

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockFactory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockTest.java
Do not assume that the agility context is still active.
=> Lucene lock: treat close as a potential recovery path

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/text/TextCollatorRegistryJRE.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/expressions/CollateFunctionKeyExpressionTest.java, fdb-record-layer-icu/src/main/java/com/apple/foundationdb/record/icu/TextCollatorRegistryICU.java
If unspecified, collation `FunctionKeyExpression`s now set their locale to `Locale.ROOT` instead of the machine's default Locale. This makes the contents of index entries more resilient to users changing their machine's default values. This does mean that users who are running with an incompatible locale will need to update their index definitions to reference the appropriate locale or will need to rebuild any indexes that don't already set a locale.
This fixes #2678. This is a specific instance of #2672.
=> Fixes #2678: Default collation function depends on JVM setting for locale

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/RecordStoreNoInfoAndNotEmptyException.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreOpeningTest.java
The previous logic used to decide what error message to present based on the `storeExistenceCheck`. This is incorrect, because it means we would report that the store would have no record data if the existence check supported opening stores with no header and no recods, but we should instead only report that if the store actually has no records. So now the error message is based on the data we actually find.
This fixes #2715.
=> Fixes #2715: Error message for stores with missing header can be misleading

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneLockFailureTest.java
Fix an issue with the Lucene exception wrapping where an update of a document in a partitioned index didn't get wrapped  properly.
=> Resolve #2725 Wrap exception for partitioned index

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/AlphanumericCjkAnalyzer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/AlphanumericLengthFilterFactory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/AutoCompleteAnalyzer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/EmailCjkSynonymAnalyzer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/EmailCjkSynonymAnalyzerFactory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteHelpers.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteQueryClause.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/filter/AlphanumericLengthFilter.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/filter/CjkUnigramFilter.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/filter/package-info.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneAutoCompletedMatchesTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestUtils.java
**Motivation**
Fix handling of CJK autocomplete. 
**Modifications**
- Make a new autocomplete analyzer that can understand CJK to analyze the input for phrase construction, and also for matching of autocompleted text.
- Added more tests around CJK autocomplete and CJK autocomplete matching
- Created `CJKUnigramFilter` and a new `AlphanumericLengthFilter` that works with the `CJKUnigramFilter`
- Added a new `EmailCjkSynonymAnalyzer`, mostly for testing
=> Properly handle autocompletion with CJK using CJKUnigram filter #2712

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildSumIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildUnnestedIndexTest.java
This updates the logic within the index builder tests so that it uses `BigInteger`s when splitting up the range. This is necessary because we can sometimes get large enough ranges between the `start` and `end` that intermediate steps may not be handled using 64-bit precision. These tests may be unnecessary as we mature the other parallel index build infrastructure and tests, but for now, this should unblock those hitting these flaky tests.
This fixes #2741.
=> Fixes #2741: Inverted range from tests that run non-overlapping parallel builds

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/TypeRepositoryTest.java
This resolves #2737, by setting the nullability of the element type to be consistently false when creating Types out of the message descriptor irrespective of what the original nullability was (which is anyway not stored in the descriptor).
=> Resolves #2737: Inconsistent nullability status for Array's element type

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CorrelationIdentifier.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ArithmeticValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/CountValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/IndexOnlyAggregateValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/NumericAggregationValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VariadicFunctionValue.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidatorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/Commands.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/DebuggerWithSymbolTables.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/PlannerRepl.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/Processors.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/LuceneHighlighterTest.java
This updates a few calls to `toUpperCase()` and `toLowerCase()` to specify `Locale.ROOT` instead of `Locale.getDefault()`. This fixes an issue where different handling of `"i".toUpperCase()` or `"I".toLowerCase()` were resulting in the `ArithmeticValue` to not successfully encapsulate multiplication. For the record, it turns out we're already using a PMD rule that forces the user to specify a `Locale`, but it only checks that a locale was specified, not that the `Locale` is a specific value. Also, the PMD checks don't run on test code, which is why those classes in test logic were not specifying a locale at all.
This fixes #2750.
=> Fixes #2750: Some calls to toUpperCase and toLowerCase are missing fixed Locale

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockFactory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneLockFailureTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockTest.java
Resolves #2747 by validating and updating the filelock on every transaction commit. This allows a much shorter timeout of around 20 seconds instead of 10 minutes.
=> Resolves #2747: Validate filelock on every transaction to reduce ttl

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
Allow Lucene block cache size to be configured.
Use the cache's native get(provider) to allow stats.
Add cache removal counter.
=> Resolve #2749: Allow Lucene block cache size to be configured.

fdb-extensions/src/main/java/com/apple/foundationdb/async/rtree/RTree.java
Changes the default storage to BY_NODE and not to use secondary node slot index
=> Change RTree defaults

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockFactory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockTest.java
Previously, if the context that was clearing the lock was flushed, the commit check would fail because the lock is missing. It now protects against this.
This also means that LuceneIndexMaintenanceTest.flakyMerge is no longer flaky.
=> Resolves #2754: FDBDirectoryLock won't fail if flushed in close

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
a 0% failure rate doesn't really make sense for this test
=> Resolves #2759: Don't run mergeLosesLockTest with 0% failure rate

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingCommon.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationBaseBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationConfig.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java
As a code cleanup, and following PR #2788, move the sync session parameters to OnlineIndexOperationConfig.
=> Resolve #2794: OnlineIndexer / OnlineIndexScrubber: move the sync ses sion lease length to Config

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/AvailableFields.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/IndexKeyValueToPartialRecord.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexScanMatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/WindowedIndexScanMatchCandidate.java, fdb-record-layer-core/src/main/proto/record_query_plan.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/IndexKeyValueToPartialRecordTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrderingQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/PlanStringRepresentationTest.java
This is complete for the heuristic planner. For Cascades, it adds the necessary partial record support, but more work in `tryFetchCoveringIndexScan` is needed, depending on how precisely function index keys are represented in `Value`s.
=> Resolves #2801: Covering optimization with invertible index fields

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
Due to #2813 this test can, occasionally, run forever, so add a timeout so that it doesn't.
=> Add a time limit that's less than 1 hour to LuceneIndexMaintenanceTest.concurrentStoreTest

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ArithmeticValue.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/ArithmeticValueTest.java
This overrides the implementation of `equalsWithoutChildren` on the `ArithmeticValue` so that it looks at the operator. This corrects the method, as `semanticEquals` was already considering the left and right children.
This fixes #2819.
=> Fixes #2819: ArithmeticValue's semantic equals does not include operator

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java
These initial new tests focus on retries and limit management for repartitioning.
=> Add a couple tests of OnlineIndexer.mergeIndex that don't use lucene

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java, fdb-extensions/src/test/java/com/apple/foundationdb/async/MoreAsyncUtilTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/storestate/FDBRecordStoreStateCacheEntry.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
Loading the metadata version key does not seem to throw Batch GRV rate limit exceeded, while other operations on the same transaciton do. Instead it stalls forever, and the tests end up timing out at the junit level.
This change introduces a new combine that will fail when the loading the record store state fails, instead of waiting forever for the metadata version to be loaded.
=> Fixes #2813: Fail fast when Batch GRV Rate Limit Exceeded

fdb-extensions/src/test/java/com/apple/test/SuperSlow.java
Even for our most expensive tests that we have right now, anything more than 20 minutes is a bug.
=> Decrease the timeout on @SuperSlow from 1 hour to 20 minutes

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
To help investigate #2842
I'm hoping that something will timeout that isn't the test, and that will give us a good starting point.
=> Add asyncToSyncTimeout for LuceneIndexMaintenanceTest

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
The idea here being that the tests cause enough load on the fdb cluster that it can't handle anything else. Adding a 1 second sleep in between may allow it to recover and proceed to the next set of tests in a healthy state.
=> Add some sleep between tests in LuceneIndexMaintenanceTest

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneGetMetadataInfo.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneMetadataInfo.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexDataModel.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexGetMetadataInfoTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestDataModel.java
This returns the partition metadata information, and, optionally, some metadata from the IndexWriter.
In order to create a new test fixture for this behavior, felt it would be valuable to extract some shared code out of `LuceneIndexMaintainerTest`, so that's what the first few commits are. This allows the new fixture to easily toggle on/off grouping and partitioning.
=> Resolves #2826: Add new LuceneGetMetadataInfo operation

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchPartition.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/Processors.java
* Add a `toString` for `MatchPartition`, which is printed as the `bindable`; hopefully it doesn't get too long.
* Add a `Processor` for `InsertIntoMemo` events; otherwise that line is blank in `events` output.
=> Minor additions to the Cascades Debugger:

gradle/testing.gradle
Not having them makes it a bit harder to read.
I thought about using `Duration.ofMillis` but the `toString` on that is like PT0.234 or PT1.4098 which I, personally find hard to parse visually.
=> Add commas to test durations

build.gradle, examples/src/main/java/com/apple/foundationdb/record/sample/Main.java, fdb-extensions/src/main/java/com/apple/foundationdb/async/rtree/AbstractChangeSet.java, fdb-extensions/src/main/java/com/apple/foundationdb/async/rtree/ChildSlot.java, fdb-extensions/src/main/java/com/apple/foundationdb/async/rtree/Node.java, fdb-extensions/src/main/java/com/apple/foundationdb/map/BunchedMap.java, fdb-extensions/src/main/java/com/apple/foundationdb/map/BunchedMapException.java, fdb-extensions/src/main/java/com/apple/foundationdb/map/BunchedSerializationException.java, fdb-extensions/src/main/java/com/apple/foundationdb/tuple/ByteArrayUtil2.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/KeyValueLogMessage.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/DynamicMessageRecordSerializer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactoryImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingCommon.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMutuallyByRecords.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/storestate/PassThroughRecordStoreStateCache.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/synchronizedsession/package-info.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/DeleteExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/InsertExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/PrimaryScanExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/UpdateExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/CardinalitiesProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/DerivationsProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/planning/BooleanNormalizer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAnalyzerRegistryImpl.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/ConfigAwareQueryParser.java, gradle/check.gradle, gradle/codequality/spotbugs_exclude.xml
This makes updates to the code base in order to prepare for updating to JDK 17. Contained within this is:
1. A bunch of Javadoc warnings became errors. For the most part, these were warnings about methods or classes that were entirely missing. I began updating some of those, but ultimately, there's a bit too much, so I added a flag to loosen up the Javadoc requirements.
1. SpotBugs needed to be updated in order to handle class files generated at the newer JDK. Some of the rules changed, and in particular, the newer version is more persnickety about retunring mutable values, and it doesn't like exceptions being thrown in the constructor. Some of those will be harder to address than others, so I've excluded some of the new rules and fixed up a few other things that were caught by spotbugs.
=> Prep #2360: Ensure code compiles on JDK 17

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptions.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneExceptions.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockFactory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/search/LuceneOptimizedIndexSearcher.java
Wrap and Unwrap Lucene exceptions:
- Create and throw Lucene-style transaction-too-old exception
- generalize and use LuceneException utility to wrap and unwrap exceptions thrown through the Lucene stack
-
=> Resolves #2850: handle Lucene exceptions

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementUnorderedUnionRule.java
The `LogicalUnionExpression` implementation rule requires that each union leg streams a stored record, this is too strict, and prevents the implementation to work for cases where e.g. a leg is a streaming aggregate.
This fixes https://github.com/FoundationDB/fdb-record-layer/issues/2856
=> Relax unordered union implementation rule pre-condition

gradle/testing.gradle
This is an attempt to investigate Issue #2842 in a remote environment. The theory is that the cluster is in a state where it is rejecting all transactions, but the hope is that it is in a state where status works, and will tell us what is wrong.
This is resiliant to not having `fdbcli` on your path or if you are using `fdb-environment.properties` instead of the default cluster file, but it will just print errors that it could not get the status.
=> Log fdbcli status after failed test

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
This effectively reverts: #2860, but that was based off #2844 and I don't want to add that back.
=> Remove LuceneIndexMaintenanceTest.rest

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexExpansionVisitor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/MatchCandidate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/IndexOnlyAggregateValue.java, fdb-record-layer-core/src/main/proto/record_query_plan.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedRepeatedQueryTest.java
At the moment, Cascades is able to deal with `LONG`-based versions of `MIN_EVER` and `MAX_EVER` indexes. There is a variation of these indexes that internally works with FDB `Tuple`. That variation however, is not exposed to Cascades and therefore is not considered when planning a query.
Since these two variations (`LONG`-based and `TUPLE`-based) mainly differ in their storage structure, we could expose their respective match candidates exactly the same way allowing the planner to pick the right one based on the requested input/output of the index aggregate function.
This fixes #2874 .
=> Expose `Tuple`-based `MIN_EVER` and `MAX_EVER` indexes to Cascades

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java
1. Since the rebalance code is executed by two nested runners, force the inner runner's "maxAttempts" to one. The outer runner is called by the online indexer and its retry limit can be set by the external caller.
2. Add debug log messages to the rebalance code to help finding  a performance issue.
=> Resolve #2878: Lucene partition balancing: reduce the number of retries

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
This will result in more descriptive failure, rather than the test timing out.
=> LuceneIndexMaintenanceTest: Reduce infinite joins

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBPermutedMinMaxQueryTest.java
The logic to calculate the `Ordering` of aggregate queries has been augmented to include all values, not just the values even when there are repeated fields. This should be acceptable because with aggregate indexes, repeated fields don't change the cardinality in the same way that they do with `Value` indexes. (The value index logic may also consider tweaking how it works a bit, but that's not something this change attempts to handle.) The test suite for the permuted min/max indexes have been augmented to include more tests with repeated keys, including ones that would produce results that get incorrectly de-duplicated with previous `Ordering` logic.
This fixes #2901.
=> Fixes #2901: In-unions on aggregate indexes can be planned with insufficient comparison keys in the presence of repeated fields

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexUniquenessCommitCheck.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreUniqueIndexTest.java
The two new tests both fail without the change.
=> Fixes #2919: scope the IndexUniquenessCommitCheck by subpsace

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/MinimumTupleSizeKeyChecker.java
It is called from another `synchronized` method, but also from `close`. This probably indicates a problem elsewhere, as a `Transaction` is being used after / during `close`; but avoid `ConcurrentModificationException` here.
=> Make `checkPrefixesCount` `synchronized`.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePrimaryKeySegmentIndexV1.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePrimaryKeySegmentIndexV2.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/LuceneScaleTest.java
The existing implementation of context AsyncToSync allows exceptions to be mapped to other exceptions. In order to be able to reason about the errors throws by futures when relalized by AsyncToSync this PR creates a new version of AsyncToSync, to be used by Lucene code, so that exception mapping is no longer taking place.
This is the first step in handling Lucene exceptions, the others being mapping to -and from- IOExceptions on Lucene code boundaries.
=> Resolves #2923: Create a new version of AsyncToSync

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMutualTest.java
This change should allow speeding up an indexing session with insufficient performance by converting it to mutual session without loosing all the progress that was already made.
=> Resolve #2917: Allow converting a single/multi target indexing session to mutual one

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java
There were a handful of places in the `FDBRecordStore` class that were were logging but didn't include the subspace provider as context. This means that we couldn't tell what store the logs were trying to log about, which made it hard to correlate with other operations to the store. This resolves that by adding in the missing information to the missing logs.
This fixes #2936.
=> Fixes #2936: Missing subspace provider in FDBRecordStore logs

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Ordering.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PartialMatch.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/RequestedOrdering.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/RequestedOrderingConstraint.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/GroupByExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/LogicalSortExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/AbstractDataAccessRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementDistinctUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementInJoinRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PushRequestedOrderingThroughGroupByRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PushRequestedOrderingThroughSortRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PushRequestedOrderingThroughUnionRule.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/OrderingTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/OrderingValueSimplificationTest.java
Do not plan intersections during data access that do not have a chance of contributing an improving factor:
1. Do not plan an intersection of n accesses if the intersection's equality-bound keys and ordering are the same as any intersection of (n-1) accesses, that is the smaller intersection has the same cardinality and order as the current intersection that is being planned.
2. Do not plan an intersection if there is some other intersection of a true superset of accesses that is not redundant as to point 1.
3. Do not plan an intersection if one of the accesses participating in the intersection has a max cardinality of `0` or `1`.
=> resolved #2940: do not plan redundant/useless intersections

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanStringRepresentation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexExpansionVisitor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PlannerRuleSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Quantifier.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Quantifiers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/explain/PlannerGraph.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/RelationalExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/QuantifierMatchers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/CardinalitiesProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/DerivationsProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/DistinctRecordsProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/OrderingProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/PrimaryKeyProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/StoredRecordProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementNestedLoopJoinRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementSimpleSelectRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PullUpNullOnEmptyRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/SelectDataAccessRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryDefaultOnEmptyPlan.java, fdb-record-layer-core/src/main/proto/record_query_plan.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/serialization/PlanSerializationTest.java
Aggregate plans currently do not return the expected results as defined by SQL standard; as per SQL standard section 4.16.4 (Aggregate functions):
> If no row qualifies, then the result of COUNT is 0 (zero), and the result of any other aggregate function is the null value.
However, when the table is empty [*], no rows are returned, i.e.:
```sql
create table t1(col1 int);
select count(*) from t1; -- returns nothing, instead of 0
select sum(col1) from t1; -- returns nothing, instead of null
```
To fix this behaviour, we would like to expand the semantics of `ForEach` quantifiers and make them reactive of the emptiness of the underlying quantified expression, making them able to return `null` if the underlying expression is not returning any rows.
This fixes #2930 .
___
[*] an "empty" table …
=> Expand semantics of `ForEach` quantifier.

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java
The test was using ThreadLocalRandom, and now it does not. I didn't go through the effort of adding more randomness, but found some seeds that reproduce the issue reliably. This also fixes the underlying issue, which was an issue with the sorting that the validator does.
=> Fixes #2948: Make LuceneIndexTest.simplePartitionConsolidationTest not flaky

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/MapPipelinedCursor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java
The underlying issue is that multiple threads are interacting with the (non-thread-safe) queue at the same time, in complex ways. We could add `synchronized` to a `close` and `onNext`, (or some part of onNext), but instead I changed the cleanup around so that it only interacts with the pipeline in a single chain of futures.
The other change is the introduction of the `nextFuture` field, which removes the code that assumes that the pipeline will be non-empty, this seems like a good change to have, even if the other change makes it unnecessary.
I tried to do some trickery around how it interacts with the queue to make sure it handles an empty queue correctly, but since `ArrayDeque` is not thread safe, that resulted in `close` getting into an infinite loop with an-emptyable queue. I left the …
=> Fixes #548: Fix concurrency issues with MapPipelinedCursor.close

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java, fdb-extensions/src/test/java/com/apple/foundationdb/async/MoreAsyncUtilTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/AsyncLoadingCache.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTransactionContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/runners/ExponentialDelay.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/storestate/ReadVersionRecordStoreStateCache.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/AsyncLoadingCacheTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/BlockingInAsyncDetectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreUniqueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolverTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/runners/ExponentialDelayTest.java
The methods in `MoreAsyncUtil` that interact with delayed futures now take a `ScheduledExecutorService` as an argument. The old static thread pool is preserved but now is the default scheduled executor, exposed as a new static method. The `FDBDatabaseFactory` can now be configured with a different scheduled executor, and then that configuration property is propagated to the various databases it creates.
This resolves #2929.
=> Resolves #2929: Allow user to specify scheduled executor service for constructing delayed futures

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/text/DefaultTextTokenizer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/common/text/TextTokenizerTest.java
This has two changes:
1. Change the test to use `@ParameterizedTest` instead of having tests that iterate over a bunch of things. This shouldn't change the tests that actually happen. Also, switch from `Arrays.asList` to `List.of` because intelliJ complained about some of them.
2. Fix the issue by changing `DefaultTextTokenizer` to use `Locale.ROOT` for the underlying `BreakIterator`
=> Fixes #2966: Change DefaultTextTokenizer to use Locale.ROOT

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedFieldInfosFormat.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedFieldInfosFormatTest.java
This way when we compare the FieldInfo in the global FieldInfos it will come back the same, even if the Map has a different ordering
=> Fixes #2968: Sort FieldInfos attributes before serializing

fdb-extensions/src/test/java/com/apple/foundationdb/async/MoreAsyncUtilTest.java
As was done in #2972, this updates the assertions for some tests in `MoreAsyncUtilTest` that were designed to make sure that the wrong thread pool wasn't accidentally being used for callbacks on delayed futures. The test neglected the fact that the calling thread could also end up executing the callback if the future completed quickly (or if there were a delay between when the future is created and the callback added). This can happen in certain environments, including during some of our nightly CI builds, though it's not the only place it has been noticed.
This fixes #2975.
=> Fixes #2975: Test failure in MoreAsyncUtilTest.executeDelayedCallbackOnExecutor

fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java, fdb-extensions/src/test/java/com/apple/foundationdb/clientlog/ClientLogEventCounterTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Key.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutationIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/QueryPlanCursorTest.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneSpellCheckRecordCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/filter/CjkUnigramFilter.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedDocValuesFormatTest.java, gradle/check.gradle, gradle/wrapper/gradle-wrapper.properties
* Update wrapper to newest Gradle 7 release.
* Specify memory size for Checkstyle task now that it uses workers.
Fixes #2977 .
* Upgrade Checkstyle tool version.
* Fix `checkstyleAll` failures with the new version.
=> Upgrade Gradle to 7.6 and deal with Checkstyle consequences

fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/FlatMapPipelinedCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/MapPipelinedCursor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java
- [Add MoreAsyncUtil.ALREADY_CANCELLED](https://github.com/FoundationDB/fdb-record-layer/commit/aaf4ebd4796ff08a6795b9fc87f749a2e1fc49cd)
MapPipelineCursor and FlatMapPipelinedCursor had a version of this,
so reducing duplication.
- [Test concurrent closing with a non-singleton inner cursor](https://github.com/FoundationDB/fdb-record-layer/commit/d489748fcf00bfcf7352620f0a372a1688d89437)
=> Some followup from PR #2954

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/LeaderboardIndexTest.java
This modifies the `TimeWindowRankAndEntry` struct to allow the returned `rank` to be empty. This represents the case where a record was not found in one of the leaderboards and so a `null` rank is returned. Note that this returns us to the state of the world prior to #2834, which is what introduced the struct (with its non-null `rank` field). Prior to that PR, the rank could be `null`, and so any code that worked prior to that commit (which is also the most recent change as of writing) should be able to be trivially adapted to this new version.
This fixes #2986.
=> Fixes #2986: TimeWindowLeaderboardIndex throws NPE on null ranks

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestDataModel.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java
This adds a new test that does concurrent updates to different records in lucene.
The test references two specific issues:
- #2989
- #2990 
And configures itself so as to avoid hitting those issues, but as those are fixed, we can expand the test to include coverage for those issues.
=> Add a test that does concurrent lucene updates

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestDataModel.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneScanAllEntriesTest.java
There was only one usage of this that wasn't already creating a `LuceneIndexTestDataModel`, this changes `concurrentStoreTest` so that it can just use the model and then removes the static methods.
Removing the static methods will allow us to more easily maintain state, without having to add more and more parameters to the `saveRecord` method.
Resolves: #3002
=> Remove static LuceneIndexTestDataModel methods

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestDataModel.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java
This adds 3 additional tests to `LuceneIndexMaintenanceTest` that do modifications concurrently in the same transaction.
In order to support for deletes, I changed the `updateRecords` map to be a map of `RecordUnderTest`, and encapsulated it.
In order to support inserts, I made the root `saveRecord` method be asynchronous.
I also had to make more of the data model thread-safe.
I also added a `validate` method to the data model which calls `LuceneIndexTestValidator` with the appropriate arguments.
I'm not super attached to this coupling, but it seemed to cleanup a few lines elsewhere.
=> Add Lucene tests that do deletes & inserts concurrently in the same transaction

fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/QueryVisitor.java, yaml-tests/src/test/resources/aggregate-empty-table.yamsql, yaml-tests/src/test/resources/aggregate-index-tests-count-empty.yamsql, yaml-tests/src/test/resources/aggregate-index-tests-count.yamsql, yaml-tests/src/test/resources/aggregate-index-tests.yamsql, yaml-tests/src/test/resources/union-empty-tables.yamsql, yaml-tests/src/test/resources/union.yamsql
Aggregate plans currently do not return the expected results as defined by SQL standard; as per SQL standard section 4.16.4 (Aggregate functions):
> If no row qualifies, then the result of COUNT is 0 (zero), and the result of any other aggregate function is the null value.
However, when the table is empty [*], no rows are returned, i.e.:
```sql
create table t1(col1 int);
select count(*) from t1; -- returns nothing, instead of 0
select sum(col1) from t1; -- returns nothing, instead of null
```
This mostly consumes a previous [fix](https://github.com/FoundationDB/fdb-record-layer/pull/2931) that expands the semantics of `ForEach` quantifier, it adapts the plan generation making the group by quantifier cognizant to empty results case, effectively fixing the issues above.
___
[*] an "empty" …
=> Align aggregate query behaviour on empty tables more towards SQL standard

docs/ReleaseNotes.md, fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/exceptions/ErrorCode.java, fdb-relational-core/README.md, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/AstNormalizer.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperators.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/ParseHelpers.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/SemanticAnalyzer.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/BaseVisitor.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/QueryVisitor.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/util/MemoizedFunction.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/PlanGenerationStackTest.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/util/MemoizedFunctionTest.java, yaml-tests/src/test/java/YamlIntegrationTests.java, yaml-tests/src/test/resources/cte.yamsql, yaml-tests/src/test/resources/recursive-cte.yamsql
This adds SQL support to Recursive CTEs, building on top #2981 which added planning and runtime support to recursive union plans.
Some relatively complex logic is added to the semantic analyzer to allow proper resolution of the recursive CTE type and effectively understand which branches are recursive (relative to the current query block) and which are not, as this is required to build the recursive union plan and the underlying temporary table buffers correctly. This logic can be, arguably, streamlined in a better way if we had a dedicated semantic analysis phase. That is one of the reasons the analysis is not _that_ advanced, and fails for certain types of valid recursive CTEs (see newly added test cases in `PlanGenerationStackTest` for more information).
Example query (more examples …
=> Introduce SQL support to Recursive CTEs

build.gradle, yaml-tests/yaml-tests.gradle
This changes the yaml tests to download the latest release available.
The tests that actually take advantage of this are still disabled.
=> Change yaml-tests to download latest released server

scripts/YAML-SQL.xml, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/CustomYamlConstructor.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/MultiServerConnectionFactory.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlExecutionContext.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlRunner.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/Block.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/ConnectedBlock.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/FileOptions.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/SetupBlock.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/TestBlock.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/RunExternalServerExtension.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/package-info.java, yaml-tests/src/test/java/EmbeddedYamlIntegrationTests.java, yaml-tests/src/test/java/JDBCExternalYamlIntegrationTests.java, yaml-tests/src/test/java/JDBCInProcessYamlIntegrationTests.java, yaml-tests/src/test/java/MultiServerJDBCYamlTests.java
With the new mixed-mode tests being run as part of PRB, we'll need a way to say that a test should not run against old versions. This adds support for disabling an entire yaml file. Future steps would be to allow disabling a specific query, providing a specific supported version, and also having the build update the `!current_version` to the version being released.
=> Ability to prevent yamsql tests from running against old versions.

yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/SemanticVersion.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/package-info.java, yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/server/SemanticVersionTest.java, yaml-tests/yaml-tests.gradle
This introduces a class for parsing and comparing versions of the Record Layer. 
This can be combined with the work in https://github.com/FoundationDB/fdb-record-layer/pull/3031 to control what versions a yaml test will run against.
=> Add a class for comparing versions of the record layer

yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/RunExternalServerExtension.java, yaml-tests/src/test/java/JDBCYamlIntegrationTests.java, yaml-tests/src/test/java/MultiServerJDBCYamlTests.java
Enable yaml tests that were disabled before, now that the gaps have been filled.
=> Enable multi version tests

docs/ReleaseNotes.md, fdb-java-annotations/src/main/java/com/apple/foundationdb/annotation/GenerateVisitorAnnotationHelper.java, fdb-java-annotations/src/main/java/com/apple/foundationdb/annotation/GenerateVisitorAnnotationProcessor.java
This allows service loading all annotation processors and even determining that this one does not apply, without having javapoet in the classpath.
=> Break out a helper class from GenerateVisitor annotation processor.

docs/ReleaseNotes.md, fdb-java-annotations/src/main/java/com/apple/foundationdb/annotation/GenerateVisitorAnnotationHelper.java, fdb-java-annotations/src/main/java/com/apple/foundationdb/annotation/GenerateVisitorAnnotationProcessor.java
Break out a helper class from GenerateVisitor annotation processor. This allows service loading all annotation processors and even determining that this one does not apply, without having javapoet in the classpath.
=> Break out a helper class from GenerateVisitor annotation processor. (backport #3060)

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/QueryPlanInfo.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/QueryPlanInfoKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CascadesPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/Debugger.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/Stats.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/StatsMaps.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/QueryPlanInfoTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/DebuggerWithSymbolTables.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/PlannerRepl.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/State.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/QueryPlan.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/ExplainTests.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryConfig.java
```
RelationalStructMetaData(
FieldDescription.primitive("TASK_COUNT", Types.BIGINT, DatabaseMetaData.columnNoNulls),
FieldDescription.primitive("TASK_TOTAL_TIME_NS", Types.BIGINT, DatabaseMetaData.columnNoNulls),
FieldDescription.primitive("TRANSFORM_COUNT", Types.BIGINT, DatabaseMetaData.columnNoNulls),
FieldDescription.primitive("TRANSFORM_TIME_NS", Types.BIGINT, DatabaseMetaData.columnNoNulls),
FieldDescription.primitive("TRANSFORM_YIELD_COUNT", Types.BIGINT, DatabaseMetaData.columnNoNulls),
FieldDescription.primitive("INSERT_TIME_NS", Types.BIGINT, DatabaseMetaData.columnNoNulls),
FieldDescription.primitive("INSERT_NEW_COUNT", Types.BIGINT, DatabaseMetaData.columnNoNulls),
FieldDescription.primitive("INSERT_REUSED_COUNT", Types.BIGINT, DatabaseMetaData.columnNoNulls), ...)
```
Most …
=> make explain return planner metrics as separate column

build.gradle, build/commit_yamsql_updates.py, yaml-tests/src/test/resources/showcasing-tests.yamsql
This adds the necessary tooling to update the `.yamsql` files, replacing `!current_version` with the version being released. I validated that it does the replacement correctly, locally. In order to support having a comment about `!current_version` in `showcasing-tests.yamsql`, I have it leave it alone if it is immediately surrounded by quotes. This seemed like a good compromise that avoided me having to get too much into yaml parsing, although something about whether the whole line is a comment could also work.
To be extra safe, the commit script validates that it's not trying to update anything other than `.yamsql` files.
I thought about adding the commit code to the gradle build also, but I couldn't figure out a way to have the dependencies be enforced so that committing always ran …
=> Auto update supported_version in yamsql files

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexGetMetadataInfoTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestDataModel.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneScanAllEntriesTest.java
This makes some improvements to the `LuceneIndexTestDataModel`:
1. Remove the confusing `start` parameter
2. Support for saving records older than existing records. This allows a new test that saving old records will create older partitions without re-partitioning
3. Add support for isSynthetic to recordsUnderTest. This allows expanding the concurrency tests to run against synthetic too
4. Add support for sampling recordsUnderTest. This allows a test that deletes every other record in each group. This behavior is pretty well covered already, but this adds a version using `LuceneIndexTestDataModel`, which seems valuable to me.
My primary reason for making these changes was to support the tests required for: https://github.com/FoundationDB/fdb-record-layer/pull/3009 but I also wanted to …
=> Improve LuceneIndexTestDataModel

build/commit_yamsql_updates.py
This changes commit_yamsql_updates.py from using `capture_output=True` to the equivalent: `stdout=subprocess.PIPE, stderr=subprocess.PIPE`
=> Switch from using capture_output to stdout=subprocess.PIPE

build/commit_yamsql_updates.py
Instead of `text`, in `subprocess.run` use `universal_newlines` The former is an alias for the latter.
=> In commit_yamsql_updates switch away from text parameter

yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/MultiServerConnectionFactory.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/RunExternalServerExtension.java, yaml-tests/src/test/java/MultiServerConnectionFactoryTest.java
This fixes an issue with the connection factory where YAML tests with a single statement always ended up using the same connection number.
=> Implement global (within factory) state for alternating connections.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/aggregate/AggregateCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/aggregate/StreamGrouping.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryDefaultOnEmptyPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryStreamingAggregationPlan.java, fdb-record-layer-core/src/main/proto/record_query_plan.proto, yaml-tests/src/test/resources/aggregate-empty-table.yamsql
- remove default `...ON_EMPTY` behavior that previously was part of `RecordQueryStreamingAggregationPlan`
- have `RecordQueryDefaultOnEmptyPlan` enforce and adjust skips and limits correctly
=> infinite continuations when NULL_ON_EMPTY is in the plan

gradle/libs.versions.toml
This updates the download plugin to the latest version. It looks like this is used to download the geonames.
=> Upgrade de.undercouch.download gradle plugin

.github/workflows/pull_request.yml, actions/gradle-test/action.yml
A recent 4.0.559 build (#3108) didn't run in PRB. This should allow us to get PRB on that branch.
=> Backport PRB to 4.0.559 branch

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/aggregate/AggregateCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryStreamingAggregationPlan.java, fdb-record-layer-core/src/main/proto/record_query_plan.proto
Cherry picks the cursor code from #3092 onto the 4.0.559 branch. That PR adapts the behavior of the `AggregateCursor` so that it no longer produces an incorrect "BEGIN" continuation in association with the final element of an empty aggregate. Such a continuation can produce an infinite loop if the continuation is then used to re-issue the query from the beginning (or throw an error if passed to `EXECUTE CONTINUATION`).
Because the fix changes the behavior of `AggregateCursor`, there would normally be some danger when continuing a plan from that version on older versions and vice versa To prevent this, the code in #3092 only goes to the new behavior if there is a flag set in the serialized continuation (so it will continue with the older semantics when deserializing an older continuation). …
=> preparing for up-level DEFAULTS_ON_EMPTY changes

gradle/libs.versions.toml
Seems to still work, I ran `./gradlew dependencyUpdates` and it printed out a whole bunch of up-to-date dependencies and dependencies that need updating.
=> Upgrade the versions gradle plugin from 0.38.0 to 0.52.0

.gitignore, gradle/antlr.gradle
This adds two fixes:
- Puts the generated files in a directory that corresponds to their set package.
- Creates a post-`generateGrammarSource` task which copies all `*.token` files next to the grammar and lexer files in `src/main/antlr`. These files are added to `.gitignore` to avoid checking them in by mistake.
These effectively enable the IDE to correctly parse and present the grammar files as well as the generated files, before it was showing hundreds of errors due to file location mismatch and the inability to link the grammar file with the respective tokens array.
=> Fixes for Gradle tasks for Antlr

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryRecursiveUnionPlan.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/Matchers.java, yaml-tests/src/test/resources/cte.yamsql, yaml-tests/src/test/resources/recursive-cte.yamsql
This sets the `limit` and `skip` (if any) on the recursive union cursor correctly. It also includes a number of small fixes to the YAML test framework error reporting in case of result mismatches, and a small optimization of handling unordered result matching.
This fixes #3100.
=> set skip and limit for the recursive union cursor correctly.

.github/workflows/patch_release.yml, .github/workflows/release.yml
This updates our release and patch release workflows to use a deploy key to get around branch protections when pushing back updates to the repository. This is used for things like updating the artifact version, the release notes, and the yamsql version.
=> Use deploy key to allow release build to write back to repo

build.gradle, fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle, gradle/publishing.gradle
There was a problem in the last release job where the shaded jars weren't able to be published. That's because we were actually publishing both a "library" and a "shadow" publication for that build, and the second publication's artifacts were attemping to override the artifacts from the first. So, this removes the library publication for that subproject. It also fixes up some task dependency problems to remove those warnings.
=> Fix publication of shaded jars

fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle
The shadow jar currently includes some information from transitive dependencies (particularly Guava) that it shouldn't. This was confusing tooling like the GitHub package and suggesting that the description coming from Guava was actually a description of our own package. Fix that up by removing the transitive maven information from the build.
=> Exclude transitive maven information in shaded jar

.github/workflows/pull_request.yml, actions/gradle-test/action.yml, gradle/testing.gradle
The test-summary action takes the xml files produced by the tests, but our xml files in the nightly action get too large for the action to load them as a string (~540mb), due to all the logging.
This replaces the test-summary action with built-in steps that print to `GITHUB_STEP_SUMMARY`. They use the listener to gather the test results and exceptions.
You can see two examples of PRBs with the resulting output. Both of these disable many of the tests so that I could iterate more quickly:
- A successful run: https://github.com/ScottDugas/fdb-record-layer/actions/runs/13246744981
- A run with some failures: https://github.com/ScottDugas/fdb-record-layer/actions/runs/13246749305
I think there's two followups that could be nice, but decided not to do them right now:
1. It would probably make …
=> Replace test-summary action with custom action code

actions/release-build-publish/action.yml
Fix a SHA for the create-pull-request action to avoid it accidentally changing.
=> Use fixed SHA for create-pull-request action

.github/workflows/nightly.yml
This summary fails with:
```
Error: Cannot create a string longer than 0x1fffffe8 characters
```
This was supposed to be fixed with: #3119 but I forgot to update the nightly workflow.
=> Remove test-summary action from the nightly workflow

yaml-tests/yaml-tests.gradle
yaml-tests resolveOtherServer had settings to override the caching settings. I think this was to override something that was otherwise removed.
=> Remove caching settings when downloading old server

yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlExecutionContext.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlRunner.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlTestConfigFilters.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/ConfigWithOptions.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/CorrectExplains.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/CorrectExplainsAndMetrics.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/CorrectMetrics.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/EmbeddedConfig.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/ForceContinuations.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/JDBCInProcessConfig.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/ShowPlanOnDiff.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/YamlTestConfig.java, yaml-tests/src/test/java/SupportedVersionTest.java
Pay technical debt from https://github.com/FoundationDB/fdb-record-layer/pull/3075: make context options type safe.
The options are now a simplified version of similar option implementations: An Option class and a wrapper around a map of the options allows us to remove the type cast when getting options. This was done this way (as opposed to a specific class with getters) in order to support the merging of options in ConfigWithOptions.
=> Change context options to a type-safe option with generics.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/IndexState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexScrubbing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMutualTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerUniqueIndexTest.java
Indexes in `READABLE_UNIQUE_PENDING` state are fully built, and hence can be scrubbed.
If uniqueness violation will ever become a scrubbing feature (not likely), distinguishing the two states should be handled by the relevant `IndexScrubbingTool` implementation.
=> Resolve #3135: Allow scrubbing of indexes in READABLE_UNIQUE_PENDING state

.github/release.yml
This introduces a spec for how to categorize PRs into release notes.
I'm fairly certain, this doesn't do anything without someone creating the release notes using the `--generate-notes` option.
I couldn't figure out how to test this without merging, or creating a new branch on FoundationDB or creating a whole new repo with a whole bunch of test PRs.
=> Initial attempt at automatic GitHub release notes

yaml-tests/src/test/resources/recursive-cte.yamsql
Two tests now fail on Main. The tests had a `supported_version` that was enabled once a release was cut but a plan hash change now make them fail when they are run on multi-server config.
This PR reintroduces the `!current_version` for the tests such that these will not run in multi-server mode
=> Fix broken build in Main

.github/workflows/patch_release.yml, .github/workflows/release.yml, actions/release-build-publish/action.yml, build.gradle, fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle, gradle/libs.versions.toml, gradle/publishing.gradle
This should complete our maven central automation. It configures artifact signing (required for maven central upload), and it makes use of the nexus publishing plugin to upload artifacts to maven central to a staging repository, close the staging repository (which validates the expected invariants from maven central), and then release the artifacts it just uploaded. Once the final step has happened, the new artifacts should be available for maven central download (modulo the time it takes for CDNs to be updated).
This resolves #1288.
=> Resolves #1288: Automatically publish to maven central

yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlTestExtension.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/MultiServerConfig.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/ExternalServer.java
This enables the execution of multi-version tests against various server versions. Assuming the availability of multiple server versions, this PR achieves the following:
- Reuses servers across different configurations, ensuring each version is run only once.
- Starts all servers located in the download directory.
- Runs all multi-server tests with all available servers.
=> Support multiple server versions in multi-version tests

.github/workflows/pull_request.yml, .github/workflows/pull_request_comments.yml
The `pull_request` attribute is empty in this case. So use an artifact between workflows.
=> Another try at getting pull-request number through from a forked PR.

build.gradle
The [release for 4.1.5.0](https://github.com/FoundationDB/fdb-record-layer/actions/runs/13327676640/job/37224445663) failed due to the signing key not being configured correctly:
```
Cannot perform signing task ':fdb-extensions:signLibraryPublication' because it has no configured signatory
```
I tracked it down, and it's because the signing is done in the wrong place in `build.gradle`. We have a section in `allprojects` where we were previously attempting to configure the signing key information. I've now updated that location with the new method, and I've validated that signing locally works. I've also double checked that the secrets in the build were populated, so it should be configured to use the right keys, but we haven't tested that in CI (yet).
=> Fixes signing configuration location

.github/workflows/nightly.yml
It is currently running nightly on all forks (unless the developer disabled actions), this limits it to this repository.
=> Restrict repository of nightly workflow

docs/ReleaseNotes.md, fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/FRL.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/EmbeddedConfig.java
I discovered that running a lot of YamlTestConfigs against the same Embedded server can result in exhausting a heap of 512MB. The main cause (at least 300mb) was the plan cache, but there was no way to control the size, so this passes those options along when running `FRL`.
`TransactionBoundEmbeddedRelationalEngine` already passes these options along.
A limit of 10 should cover any tests we have, and any short-term parallesim, or tests with multiple schema templates.
=> Resolves #3155: FRL respects PLAN_CACHE_*_MAX_ENTRIES

actions/release-build-publish/action.yml
This typo resulted in the 4.1.6.0 tag being titled just "Release " instead of "Release 4.1.6.0". :cry:
=> Fix typo in action output reference

fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/TypeConversion.java, fdb-relational-grpc/src/main/proto/grpc/relational/jdbc/v1/column.proto, fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/FRL.java
Backport parts of PR #3116 in order to allow prepared statement multi-version tests to run against the 4.0.459 release.
This only takes in the JDBC server pieces that are required to allow prepared statement to run on JDBC, so that newer versions of the project can test against this server to prove backwards compatibility.
The original PR had additional changes to the client side that are not required for this purpose and so were left out of this PR.
=> Backport prepared statement changes to the patch release

yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlTestExtension.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/ExternalServer.java
This adds a static constructor that will find all processes matching the directory for external servers and kill them.
This is most important when running/debugging locally, if you stop the debugger, or SIGKILL, there will be a bunch of processes left behind. This changes it so that we will kill them the next time you run the test.
=> Kill abandoned external servers started during Yaml Tests

.github/workflows/pr_labels.yml, build/release-notes-config.json
This reads the release notes config to generate a list of expected labels. It then compares the list of labels set on the PR and checks to make sure the PR has one of the labels provided.
Not in this PR: in theory, there are some GraphQL queries we could run so that if we have an associated issue, we could try and guess the label from the issue. This keeps it simple, though, and just makes sure that the label has been set. If the check fails, it should be a pretty straightforward and fast thing to fix.
=> Enforce all PRs are labeled for Release Note generation

yaml-tests/src/test/java/YamlIntegrationTests.java
Testing with forced continuations between `main` and 4.0.559.6 showed that some tests that were excluded because of `FORCED_CONTINUATIONS` can now be enabled. 
The tests that were enabled pass on the main -> `4.1.6.0` mixed-mode tests, though they do fail when run against `4.0.559.6`. This is how we want it, since it would flag them as needing attention.
=> Enable a few tests where the force continuation option does not fail anymore

yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/MultiServerConnectionFactory.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/SimpleYamlConnection.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlConnection.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlConnectionFactory.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlExecutionContext.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlRunner.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/ConnectedBlock.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/SetupBlock.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/TestBlock.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/Command.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryCommand.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryConfig.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryExecutor.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/SkippedCommand.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/ConfigWithOptions.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/EmbeddedConfig.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/JDBCInProcessConfig.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/MultiServerConfig.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/YamlTestConfig.java, yaml-tests/src/test/java/MultiServerConnectionFactoryTest.java, yaml-tests/src/test/java/SupportedVersionTest.java
This does the following:
1. It introduces a `YamlConnection` interface that wraps the underlying connection.
2. This makes it easier to have the connection expose what versions it is testing against
The issue we found is that when running in mixed-mode it runs the same query multiple times in parallel (as intended, I just didn't realize). This makes it incredibly hard to tell if a failing test is failing because it fails when going from the old version to the new version, or vice-versa.
=> Add version information to yaml test exceptions

gradle/scripts/log4j-test.properties
netty is really quite noisy at debug level making it hard to read the output of yaml tests
=> Change netty logs to INFO when running tests

.github/workflows/pr_labels.yml
This makes sure the PR label check is run every time the commit changes on a PR. Strictly speaking, this seems like it shouldn't be necessary, but if it isn't added, then the check may not be applied to the final commit in a PR, which in turn means that the check won't be there to block a PR missing an appropriate label.
=> Run the PR label check whenever the HEAD commit changes to ensure it is applied to the final commit of each PR

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryStreamingAggregationPlan.java, yaml-tests/src/test/java/YamlIntegrationTests.java, yaml-tests/src/test/resources/aggregate-index-tests.yamsql
There is missing state that was introduced to the `AggregateCursor` and its accompanying plan in #3092. However, this state was not added to the continuation, which results in unexpected behavior when we try to deserialize the plan's continuation (effectively, it reverts to the old behavior of the plan operator). We were already correctly _de_serializing this information, so the upshot is that any plan that is started after this current version should exhibit the correct behavior, but we get incorrect behavior when a plan is started on an older version.
This fixes #3096. I was able to get test coverage of this part of the code by enabling `FORCE_CONTINUATIONS` mode on `aggregateIndexTests`.
=> Serialize missing field `createDefaultIfEmpty` into streaming aggregate plan continuations

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryStreamingAggregationPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBStreamAggregationTest.java, yaml-tests/src/test/java/YamlIntegrationTests.java, yaml-tests/src/test/resources/aggregate-index-tests-count.yamsql
The error we were seeing was that for certain plans, we were getting errors trying to deserialize the elements of a `FDBStreamingAggregatePlan` continuation. In particular, we were seeing the type's reference before the type's definition. This was because the serialization and deserialization of the plan happened in different orders, which meant that at deserialization time, we were no longer guaranteed to come across the definition first. I've kept the order of serialization the same, and then updated the deserialization code path to align it with existing continuations that are out in the wild.
This fixes #3214. I've enabled FORCE_CONTINUATIONS mode on that test, though it mostly just works on the embedded vs. current configuration (which is enough to surface the bug). More test …
=> Fix continuation deserialization errors by deserializing streaming aggregate plans in the correct order

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java, yaml-tests/src/test/java/YamlIntegrationTests.java, yaml-tests/src/test/resources/boolean.yamsql, yaml-tests/src/test/resources/functions.yamsql
Resolves #3218
This fixes an issue where the continuation for NULL literals is failing to execute since the hash code for the NULL literal is unstable. The tests now pass (and so enabled) for configurations other than forced continuations against older versions.
=> Fix unstable hash for NULL literal

fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/Options.java, fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/FRL.java
This introduces a new `Option` for setting `asyncToSyncTimeout` to avoiding blocking forever on futures that may never return. An example of such future is waiting for `getReadVersion` JNI call to comeback against an unreachable FDB instance.
This fixes #3213.
=> Introduce a new `Option` to set `asyncToSync` timeout.

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
Since synchronized lock is optional, it would be nice to test concurrent indexing sessions (by records and by source index) that  do not use this lock. These indexing sessions will be getting many conflicts, but the index' integrity is expected to be maintained.
Resolve #3199
=> Test concurrent indexing sessions without sync lock

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryExplodePlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/plans/ExplodePlanTest.java
The `RecordQueryExplodePlan` plan is, so far, only used internally to represent a transposition of constant arrays such as e.g. `in` values as a leg of an in-join plan, and as long as the upper operator honors the skip and limit requirements it was probably ok to have this operator ignore these parameters internally. In fact, it is somewhat common for the upper operator to remove these requirements before proceeding to execute the inner operator.
I came across this issue when implementing table-functions, one example of these functions is to directly select from `values` that translates to a projection from this operator at runtime. In other words, it suddenly became a top-level operator, and therefore, it must respect skip and limit to align with the execution behavior of other …
=> `RecordQueryExplodePlan` plan adheres to `skip` and `limit` requirements

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/FutureCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFirstOrDefaultPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/storage/BackingLocatableResolverStore.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/storage/BackingLocatableResolverStoreTest.java, yaml-tests/src/test/java/YamlIntegrationTests.java, yaml-tests/src/test/resources/join-tests.yamsql, yaml-tests/src/test/resources/select-a-star.metrics.binpb, yaml-tests/src/test/resources/select-a-star.metrics.yaml, yaml-tests/src/test/resources/select-a-star.yamsql
The `RecordQueryFirstOrDefaultPlan` constructs a special cursor which has cardinality at most one. The continuation it returns back to the user is not based on the inner cursor but only on whether the cursor has returned any data. Previously, we were taking the `FutureCursor`'s continuation (which is always `\x00`) and giving it back to the `inner` plan, which would generally result in the plan resuming from the beginning. That is not the appropriate way to interpret the continuation, so this updates the logic to instead skip creating the inner cursor if we get a non-beginning continuation, which is in line with what the `FutureCursor`'s continuation means.
This fixes #3219.
=> `EXISTS` queries now honor continuation from previous runs to avoid infinite loops

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/PatternForLikeValue.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/LikeOperatorValueTest.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/CustomYamlConstructor.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/Block.java, yaml-tests/src/test/java/YamlIntegrationTests.java, yaml-tests/src/test/resources/like.yamsql
Previously, it would parse the query pattern as the escape character, making continuations useless.
i.e. `LIKE 'XYZ' ESCAPE 'XYZ'`, regardless of what the original query had for the escape character, if it had one.
Because I was curious what happens if the query pattern was a single character, I added some additional tests, and ran them with the old code to see if it would break in different ways. It didn't, I think in part because: `LIKE 'Z' ESCAPE 'Z'` is the same as `LIKE 'Z'`. I don't know if that is correct behavior, but it is what we do.
Even though these tests didn't expose other issues, I felt like they were worth keeping.
This Resolves: #3099
=> Fix deserialization of continuations for queries that contain LIKE

README.md
This was moved as part of the switch to sphinx, but the link was not updated.
=> Fix path to FDB logo in README.md

actions/run-gradle/action.yml, gradle/publishing.gradle
I ran the gradle tasks with `--warning-mode all` and found the following warnings, and resolved them:
- Remove `-b ./build.gradle` from our actions. This has been deprecated, and seems unnecessary.
- Replace `jarTask.archiveName` with `jarTask.archiveFileName` because `archiveName` has been deprecated
=> Fix gradle warnings in prb

actions/run-gradle/action.yml
I have done this for prb, and fixed the issues it found, now we need to expand it to other jobs, namely nightly and release.
This is part of the work to upgrade to gradle 8: #3242
=> Add --warning-mode all to all our builds

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboard.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardWindowUpdate.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/LeaderboardIndexTest.java
Resolves: #3240
I am opting not to add a control to drop the allTime leaderboard at this time, and instead just change the `deleteBefore` behavior.
=> Do not drop AllTime leaderboard if deleteBefore is Long.Max_VALUE

yaml-tests/src/test/java/SupportedVersionTest.java, yaml-tests/src/test/resources/supported-version/illegal-version-at-block.yamsql, yaml-tests/src/test/resources/supported-version/illegal-version-at-file.yamsql, yaml-tests/src/test/resources/supported-version/illegal-version-at-query.yamsql
This resolves #3238
Adding a few tests that include illegal version clauses to the end-to-end YAML SupportedVersionTest
=> Add illegal version tests to SupportedVersionTest

fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/metadata/SchemaTemplateSerDeTests.java
com.ibm.icu.impl.Pair does not have a toString implementation which does not make it conducive to parameterized test arguments.
I did a search for other references to that Pair class, and did not find anything.
This will help us understand what arguments are being provided for: #3247 that cause it to fail.
=> SchemaTemplateSerDeTests: Replace ibm's Pair with our NonnullPair

fdb-record-layer-jmh/fdb-record-layer-jmh.gradle, fdb-relational-cli/fdb-relational-cli.gradle
The JMH one is a little surprising to me, as that is just a plugin.
I basically just followed what gradle printed in the warnings. Also, I validated this locally running each task with a clean, e.g. ./gradlew clean :fdb-relational-cli:jar --warning-mode all on main, it fails because files don't exst, but on this branch they succeed.
This is part of the work to allow upgrading to gradle 8: https://github.com/FoundationDB/fdb-record-layer/issues/3242
=> Add missing explicit dependencies for gradle tasks

actions/run-gradle/action.yml
This has been deprecated because it creates code that violates the JVM specification:
https://bugs.openjdk.org/browse/JDK-8214731
=> Remove -Xverify:none from build

build.gradle, fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle, gradle/libs.versions.toml, gradle/publishing.gradle
We no longer need the artifactory publishing logic that we used to use for publishing in the gradle build as new releases are no longer being published there. This removes the now dead code from the build, which means we no longer need to include the artficatory plugin in our build-time dependencies, which is nice.
There are a few other build files that appear to be dead code that we can remove, but this is more targeted. I've validated that I can still publish to maven local with this change, and all of the logic seems to be pretty specific to actually running an artifactory build, so this shouldn't disrupt our other build procedures, but I guess one never knows.
This resolves #3249.
=> Remove Artifactory publishing logic from gradle build

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VersionValue.java, gradle.properties
In #2943, a new serialization of the `VersionValue` was introduced, though we had to modify it in #3179 so to avoid deserialization problems when serializing and deserializing continuations across 4.0 and 4.1. With 4.2, we want to start using the new serialization path to serialize `VersionValue` children more completely.
The mixed mode testing in PRB validate this change is compatible with 4.1.9.0. I've also run the full mixed mode battery for the `versionsTest` tests, and the serialization is compatible between this change and all 4.1 versions, as well as all 4.0 versions after 4.0.562.0, which is in line with what we'd expect.
This resolves #3203.
=> Queries using versions now use a serialization that requires 4.1

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidatorTestV3.java, fdb-relational-server/src/test/java/com/apple/foundationdb/relational/server/RelationalServerTest.java, yaml-tests/yaml-tests.gradle
Address some small incompatibilities between Protobuf 3 and Protobuf 4, attempting to have code that will compile against both.
* `Descriptors.FileDescriptor.getSyntax`, which was deprecated, is now removed. Use `DescriptorProtos.FileDescriptorProto.getSyntax`.
* `TextFormat.shortDebugString` is deprecated. Remove newlines manually for now (only in test failure codepath).
* guava is no longer a transitive dependency; add it explicitly where needed.
=> Prepare for upgrade to Protobuf 4 by removing deprecated or removed calls

fdb-relational-api/src/main/java/com/apple/foundationdb/relational/util/Assert.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/metadata/SchemaTemplateSerDeTests.java
The Assert utility used for checking conditions and throwing exceptions was using the default locale, causing the message to change based on the default locale for the JVM.
This caused SchemaTemplateSerDeTests to fail in the nightly build.
This resolves: #3247
=> Change some error messages to format with Locale.ROOT

fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalDatabaseMetaData.java, fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalDriver.java, fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalPreparedStatement.java, fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalResultSet.java, fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalResultSetMetaData.java, fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalStatement.java, fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/SqlTypeNamesSupport.java, fdb-relational-api/src/main/java/com/apple/foundationdb/relational/util/Assert.java, fdb-relational-cli/src/main/java/com/apple/foundationdb/relational/cli/sqlline/Customize.java, fdb-relational-cli/src/main/java/sqlline/SetSchema.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/ProtobufDataBuilder.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/metrics/NoOpMetricRegistry.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/EmbeddedRelationalConnection.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ErrorCapturingResultSet.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/catalog/systables/SystemTableRegistry.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ddl/RecordLayerMetadataOperationsFactory.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ddl/RecordLayerSetStoreStateConstantAction.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/cache/MultiStageCache.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/cache/RelationalPlanCache.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/memory/InMemorySchemaTemplateCatalog.java, fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalResultSetFacade.java, fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalResultSetMetaDataFacade.java, fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/JDBCRelationalConnection.java, fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/JDBCRelationalStatement.java, fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/RelationalServer.java
This marks a bunch of methods to be included in our code coverage report.
I went through all the references, and I believe I left 3 categories of things that are excluded:
1. Methods that are simply some variant of throw OperationNotSupported. We have a lot of these, because we override parts of JDBC, but haven't implemented all of it yet.
2. There's a handful of Hollow or NoOp classes. I want to investigate these further, and validate whether we should (a) remove them or (b) at least have tests that have them where there supposed to go
3. `PlannerDebuggerCommandHandler` -- I believe this command starts the planner repl, so that you can step through the cascades planner execution. Given that the planner repl is entirely internal, and interactive, I feel like this is ok.
4. `LaunchSQLLine` …
=> Remove a bunch of references to @ExcludeFromJacocoGeneratedReport

build/release-notes-config.json
I created a PR to cleanup some whitespace, and there was no good label for it. I saw that we already had a https://github.com/FoundationDB/fdb-record-layer/labels/cleanup label, so adding that to the Build/Test/Documentation group in the release notes seems like a good idea to me.
The description for https://github.com/FoundationDB/fdb-record-layer/labels/cleanup is `Stylistic code cleanup`, but I'm not sure if we should have a more descriptive label, to avoid other types of cleanup, such as deleting unused, private code.
=> Add cleanup to list of potential labels for PRs

fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/ddl/NoOpQueryFactory.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/HollowTransactionManager.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ddl/NoOpMetadataOperationsFactory.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/transactionbound/catalog/HollowSchemaTemplateCatalog.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/transactionbound/catalog/HollowStoreCatalog.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/api/ddl/AbstractMetadataOperationsFactory.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/api/ddl/AbstractQueryFactory.java
This removes the annotation from the Hollow* and NoOp* classes that were previously annotated.
Since AbstractMetadataOperationsFactory and AbstractQueryFactory are only used by tests I moved them there.
This is a continuation of #3269
=> Remove more @ExcludeFromJacocoGeneratedReport

docs/sphinx/source/ReleaseNotes.md
`4.2.1.0` was not published, so we should remove its entry in the release note and merge it with the `4.2.2.0` section
=> Fix release note since 4.2.1.0 release did not get published to maven central

.github/workflows/release.yml
PR #3275 removed the usage of this, but didn't remove the step itself, so I'm removing it.
If I search for `get_old_version` in `release.yml` now, it doesn't find anything, so I'm pretty confident there are no dangling references.
=> Remove get_old_version step from release build

gradle/sphinx.gradle
I was seeing in the release:
```
> Task :sphinxDocs
2025-03-28T19:10:22.0800951Z Running Sphinx v8.1.3
2025-03-28T19:10:22.0802497Z loading translations [en]... done
2025-03-28T19:10:22.0812351Z WARNING: html_static_path entry '_static' does not exist
```
I tried running:
```
./gradlew clean documentationSite  -PreleaseBuild=true --warning-mode=all
```
locally after this change, and it did not appear to have that warning, but it did when run without this change.
=> Fix warning from sphinxDocs about missing _static directory.

yaml-tests/yaml-tests.gradle
This decreases the maximum number of builds we will compare during mixed mode testing from 50 to 10. (Note that we didn't actually have 50 versions that were mixed-mode testing compatible as it required 4.0.559.0, but we do have more than 10.) This is in response to release build failures (see: https://github.com/FoundationDB/fdb-record-layer/actions/runs/14217433940 and https://github.com/FoundationDB/fdb-record-layer/actions/runs/14222485395). Those appear to have been caused by the mixed mode test job running out of resources, as it started experiencing timeouts and didn't fail locally. The hope is that decreasing this number makes the run able to complete.
We may need to consider adjusting this in the future to be smarter (e.g., comparing the most recent version to all versions in the …
=> Decrease the number of builds compared during mixed mode to the most recent 10

docs/sphinx/source/ReleaseNotes.md
This brings the release notes in from 4.2.2.1 which were committed to the 4.2.2-release branch.
I tried to cherry-pick 0c0703a56 but git could not figure out that 4.2.2.1 should be inserted after 4.2.2.0, and so, instead, it intermingled the notes from 4.2.2.1 with the notes from 4.2.3.0 and 4.2.4.0, so I just copied the notes in.
=> Updating release notes for 4.2.2.1

yaml-tests/yaml-tests.gradle
The 4.2.3.0 release did not do a mixed-mode test against 4.2.2.0 because that was released less than 24 hours before. This changes it so that it refreshes the dynamic version after 10 minutes. This does mean that builds will have to fetch the latest version metadata more often, including for developers running locally.
If this becomes a burden, we could try to add something to our release process to ensure that after a release we force an update to the cached version, but that seems trickier to manage, and we'd only really be able to test it by doing releases within 24 hours of each other.
=> When downloading old servers, only cache latest version for 10 minutes

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexBuildState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexScrubbing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingSubspaces.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationBaseBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexing/IndexingRangeSet.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreOpeningTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java
Resolve #3297
To allow users run different types of index scrubbing sessions, we should add the next items to the scrubbing policy:
- scrubbing range reset: This will force the scrubber to start from scratch (default is false)
- scrubbing range id: user can request to use another range set, not to disturb existing one (default, backward compatible, is range 0)
- new scrubbing API function `eraseAllIndexingScrubbingData` can be used to delete all scrubbing data. This can be used as a scrubbing state cleanup.
=> Index scrubbing should support range id & range reset

yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/SimpleYamlConnection.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/JDBCInProcessConfig.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/JDBCMultiServerConfig.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/EmbeddedYamlConnectionFactory.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/JDBCInProcessYamlConnectionFactory.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/MultiServerConnectionFactory.java
While testing in YAML framework, I realized that a multiserver config like `MultiServer (4.0.575.0 then Embedded)` is actually connecting to 4.0.575.0 external server and JDBC in-process !current_version (instead of Embedded). This PR fixes this naming so as to avoid ambiguity. 
Also, `MultiServerConnection`s, while alternating their connections, logs operations like `Sending operation createStatement to connection 0` meaning, it is sending the current request to first (default, index 0) connection which is not super clear when debugging issues related to compatibility. This PR changes that log to explicitly specify the connection name.
=> Fix connection name in Multiserver configs in YAML-tests

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexScrubbing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingSubspaces.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java
Resolve #3305
1. Make `INDEX_SCRUBBED_INDEX_RANGES` unique (bug fix)
2. Make the constructor of `ScrubbingPolicy` private (it was never meant to be public)
3. Rename new `ScrubbingPolicy.getRangeId` to `getScrubbingRangeId`
4. Rename new `ScrubbingPolicy.isRangeReset` to `isScrubbingRangeReset`
=> Make INDEX_SCRUBBED_INDEX_RANGES unique + more

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreFormatVersionTest.java
FDBRecordStore.Builder.setFormatVersion takes an integer, but only a limited set are supported, we should prevent setting it to a value that is unsupported.
Resolves: #3308
=> Prevent setting the format version to an unsupported version

docs/sphinx/source/ReleaseNotes.md
The 4.2.7.0 build failed to publish artifacts (see: https://github.com/FoundationDB/fdb-record-layer/actions/runs/14863133315 and https://github.com/FoundationDB/fdb-record-layer/actions/runs/14864688455). As a result, it should not be included in our release notes document. This combines the release notes information from 4.2.8.0 and 4.2.7.0 into one larger release note for the two combined (catalogued under 4.2.8.0).
=> Remove 4.2.7.0 release notes as build was never published

fdb-extensions/src/test/java/com/apple/foundationdb/async/MoreAsyncUtilTest.java, fdb-extensions/src/test/java/com/apple/test/BooleanArguments.java, fdb-extensions/src/test/java/com/apple/test/BooleanArgumentsProvider.java, fdb-extensions/src/test/java/com/apple/test/BooleanSource.java, fdb-extensions/src/test/java/com/apple/test/ParameterizedTestUtils.java, fdb-extensions/src/test/java/com/apple/test/ParameterizedTestUtilsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/APIVersionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreUniqueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/runners/TransactionalRunnerTest.java
This adds a couple utilities to our testing frameworks:
1. An optional name for `@BooleanSource`, so that it doesn't just appear as `true` / `false`
2. Methods for producing similar named boolean streams for use in a `@MethodSource`
3. A method to produce the cartesian product of a bunch of streams, instead of having to chain a whole bunch of `flatMap`s.
Below is a screenshot of the test results after this change, for `FDBRecordStoreUniqueIndexTest` that takes full advantage of the new `@BooleanSource` functionality
vs the old way:
vs if you don't have the `name=` on all the tests
(Note: `removeUniquenessConstraintDuringTransactionWithNewDuplications` was taking `removeUniquenessConstraintArguments` but only actually used one of the parameters, causing it to run twice as many times as …
=> ParameterizedTest utilities

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerImpl.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/runners/FutureAutoClose.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/runners/FutureManagerRunner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/runners/TransactionalRunner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/runners/FutureAutoCloseTest.java
This refactoring moves the future management (completing of futures once the runner closes) out of the FDBDatabaseRunnerImpl into a subclass of TransactionalRunner. 
This allows the new subclass of TransactionalRunner to be used (e.g in the case where we want another throttling implementation).
Resolves #3346
=> Create FutureManagerRunner and convert FDBDatabaseRunnerImpl to use it.

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Quantifier.java
Not memoizing this set caused massive performance problems downstream.
=> Reenable memoization of correlated-to sets

fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/QueryLoggingTest.java
This PR adds a test to verify that `RelationalConnection.setOption(LOG_QUERY, true)`, on an existing connection, works as expected. That is, we can put it `true` before executing a statement and set it to `false` to disable logging afterwards.
=> Add a test to verify setOption LOG_QUERY works per statement

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ExpressionPartition.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ExpressionPartitions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ExpressionPropertiesMap.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/FindExpressionVisitor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/LinkedIdentityMap.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PlanPartition.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PlanPartitions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PlanPropertiesMap.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PlannerStage.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Reference.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/ExpressionsPartitionMatchers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/DistinctRecordsProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/OrderingProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/PrimaryKeyProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/SelectCountProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/StoredRecordProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/FinalizeExpressionsRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementDeleteRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementDistinctRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementDistinctUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementInJoinRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementInUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementIntersectionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementStreamingAggregationRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementTypeFilterRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementUniqueRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementUpdateRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/RemoveSortRule.java
This PR provides a distinction among the properties that are being maintained for `References`. Before this PR, all properties were only used to derive `ExpressionPartition`s, i.e. they would define a set of properties all plans in the reference could be partitioned by. There are, however, also other properties which should be maintained in the same way but should be accessible individually for each expression in the reference.
=> (non)-partitioning properties for `Reference`s

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTypedRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/recordrepair/RecordVersionValidator.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RecordsUpdateLockTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/recordrepair/RecordValidateAndRepairTest.java
Create a version of the `saveRecordAsync` that allows bypassing the new store update lock.
We could have made this more complicated by creating a framework for rules around when can a certain kind of lock be bypassed and for what "reason" (e.g. "repair"), but this seems like an overkill so I opted for the straightforward way of a single boolean and an `if (override)` in the base `saveRecordAsync` implementation.
Resolves #3391
=> Allow version repair to operate while the store is locked

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/MultiMatcher.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/ConstantFoldingMultiConstraintPredicateRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/ConstantFoldingRuleSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/ConstantPredicateFoldingUtil.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/QueryPredicateSimplificationRule.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/RuleTestHelper.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/rules/QueryPredicateSimplificationRuleTest.java
This introduces a new planner rewrite rule called `QueryPredicateSimplificationRule`, it matches `SelectExpression`s with at least one predicate, and attempts to simplify the conjunction of the predicates through the `QueryPredicate` simplification engine and rules (which were introduced in #3404).
If the predicate was simplified, it proceeds to create a new `SelectExpression` with that simplified predicate, and if the predicate is a conjunction, it breaks it apart, and supply its terms to the `SelectExpression` to align with the way the `SelectExpression` is constructed where its predicates are heavily preprocessed.
This PR also introduces a new `QueryPredicate` simplification rule called `ConstantFoldingMultiConstraintPredicateRule` that, as the name suggests, attempt to simplify a …
=> Planner rewrite rule for simplifying `SelectExpression` predicates

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/EvaluatesToValue.java, fdb-record-layer-core/src/main/proto/record_query_plan.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/ConstantFoldingTestUtils.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/values/EvaluatesToValueTest.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/MutablePlanGenerationContext.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/QueryPlan.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/cache/ConstraintValidityTests.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/cache/RelationalPlanCacheTests.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/cache/ValueSpecificConstraintTests.java
This introduces new set of value-specific constraints to be added to the plan cache keys, the constraints are created for the following:
* Explicit boolean values (true, false).
* Explicit null values.
* Whether a literal is not null.
Implementing these constraints is crucial to prevent the use of physical plans generated based on assumptions about literal values that may not hold true during subsequent query executions. This can occur when the actual literal values differ from those initially assumed.
Therefore, the plan generator should analyze the literals and generate necessary constraints about their values according to the above rules to be used in the plan cache key.
This resolves #3412
=> Introduce value-specific plan cache constraints

yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlTestExtension.java
If you have a MaintainYamlTestConfig set, that should work correctly when running with quickTest, i.e. it should run the maintenance.
Previously it would fail because it would have an empty stream, and this should result in a better developer experience.
=> Allow MaintainYamlTestConfig with quickTest

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
If store state is initialized inline, preserve the state of the `allowUniquePending` parameter.
=> Address case where `markIndexReadable` could ignore `allowUniquePending` parameter

.github/workflows/pull_request.yml
I was looking through recent PRB runs, and it seemed like the time to run other-tests was now around twice the time to run the core-tests. Most of the time seemed to be coming from lucene-tests, so I wanted to experiment with separating those out. This hopefully should decrease our total PRB time
=> Separate out Lucene tests so they run separately in PRB

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CascadesPlanner.java
A sanity check to validate the traversal integrity was recently added in #3435. That check alone seems to almost double the total time it takes to run the `core-tests` during PRB from around 15 minutes to around 30 minutes. It's a useful check, but it is probably running too often. We should be able to get away with only running it occaisionally and then only enabling it more stringently if the need arises.
=> Run expensive `Traversal` verification sanity check less often

.github/workflows/release.yml
This modifies the release build workflow so that we increment the version of local code before we go to run the tests. This makes it so that we correctly distinguish between the latest external version (which should have a version less than `!current_version`) and the current code version. This is necessary to unblock the release build, which is failing currently due to certain tests failing when run in mixed mode against the lateset published version due to expected differences.
Overall, I think this is a better set-up for our tests, as the version that will actually run the tests is now closer to version that we will actually end up publishing. The only difference should be the release number, which _shouldn't_ matter, but it's good to be sure.
This fixes #3449.
=> Update code version before running tests in release build

.github/workflows/release.yml, build.gradle, docs/sphinx/source/ReleaseNotes.md
The service we were using to publish to Maven Central was sunset. There is a legacy API that allows us to continue to use our old publising gradle platform, and so I've updated the configuration so that it follows the advice available on their website: https://github.com/gradle-nexus/publish-plugin?tab=readme-ov-file#publishing-to-maven-central-via-sonatype-central
This is advertised to be pretty straightforward. The two main steps are (1) update the publishing URL to one that uses a bridge API and (2) modify the credentials to ones generated by the new portal. I've done that (and already updated the secrets on the repo with the new credentials). So we should be able to get a new build published through the new gateway once this is in.
I've also gone ahead and removed the release notes …
=> Update the Maven Central publishing URL to avoid sunset service

fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/AbstractEmbeddedStatement.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/EmbeddedRelationalConnection.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/EmbeddedRelationalStatement.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/RecordLayerResultSet.java
As a follow up correction to https://github.com/FoundationDB/fdb-record-layer/pull/3429, rename this function back.
=> Rename shouldCommit back to canCommit

fdb-extensions/src/main/java/com/apple/foundationdb/tuple/ByteArrayUtil2.java, fdb-extensions/src/test/java/com/apple/foundationdb/tuple/ByteArrayUtil2Test.java, fdb-extensions/src/test/java/com/apple/foundationdb/tuple/TupleTest.java
The ' (single quote) character can confuse log parsers. This PR escapes this character when used within a log message.
This change alters the serialized representation of the byte array as a string. Any usage of this representation would be therefore modified. Searching the codebase showed usage within Exception messages and logging, which is likely OK, but care should be taken to verify that no ill impact is exposed.
Resolves #3461
=> Escape the ' character in the loggable method to help with log parser frameworks.

fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/RecordTypeTable.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/SimpleDirectAccessInsertionTests.java
This PR adds support for inserting structs with NULL typed fields into the table via `ExecuteInsert` in the Direct Access API. Also adds a test for the same. 
This bug was introduced by https://github.com/FoundationDB/fdb-record-layer/pull/3484, which essentially shifts the Relational-layer from using Sql Type codes for internal operations to relying on Relational DataTypes for getting a richer information. 
Fixes: https://github.com/FoundationDB/fdb-record-layer/issues/3491
=> Add support for NULL type fields in ExecuteInsert

gradle/testing.gradle
I ran two tests that had exceptions deep in lucene code, with suppressions and causes, and this omission reduced the 768 lines / 76,114 bytes to 183 lines / 16,946 bytes.
GitHub has a limit of 1024k for the summary, so this should help keep us below the limit, and make it easier for developers to diagnose why a test failed.
There are probably some other situations that it won't catch, and maybe the formatting could be a little cleaner, but I think this gets the job done, and don't feel like it's worth spending a bunch of dedicated time on it right now.
Here is a sample after it is cleaned up:
<details>
<summary> ❌ FDBLuceneIndexFailureTest > basicGroupedPartitionedTest(boolean) > [2] true</summary>
(23ms)
```
java.lang.RuntimeException
at …
```
=> Omit portions of stack trace that are just junit in test summary

fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/metadata/DataType.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/metadata/DataTypeUtils.java, fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/TypeConversion.java
This PR (1) adds the missing support in `DataType` and gRPC-related classes for the future UUID type. This is needed to maintain compatibility in mixed-mode testing with the future full-support version.
It is relatively difficult to test this on the `main` as we cannot bring in the support in the current PR. However, here is the PR for re-introducing the full support: https://github.com/FoundationDB/fdb-record-layer/pull/3510 (2). I have tested that (2) is backward compatible with fixes in (1). Hence, if (1) releases first, and then we bring in (2) we will maintain compatibility to "older" version JDBC servers.
=> Interpret full-supported UUID type correctly in JDBC server 

.github/workflows/teamscale_upload.yml
Use hash instead of version number
=> Fully qualify teamscale action

yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlExecutionContext.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryConfig.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryExecutor.java, yaml-tests/src/main/proto/planner_metrics.proto, yaml-tests/src/test/java/TransactionSetupTest.java, yaml-tests/src/test/resources/transaction-setup/shouldPass/double-query-metrics.metrics.binpb, yaml-tests/src/test/resources/transaction-setup/shouldPass/double-query-metrics.metrics.yaml, yaml-tests/src/test/resources/transaction-setup/shouldPass/double-query-metrics.yamsql
Planner metrics previously assumed that it was only reasonable to have a query once within a single block. Having setup can make this more complicated, so this changes the keys for the metrics to have the setup too.
There were a couple unrelated cleanups along the way:
1. `markDirty()` was annotated `@Nullable`, but is `void`
2. `putMetrics` took `isDirectyMetrics`, but that parameter was never used, so I removed it.
=> Handle metrics for the same query but with different setups

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/PromoteValue.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/TableWithEnumTest.java, fdb-relational-core/src/testFixtures/java/com/apple/foundationdb/relational/utils/ArrayAssert.java, fdb-relational-core/src/testFixtures/java/com/apple/foundationdb/relational/utils/ResultSetAssert.java, fdb-relational-core/src/testFixtures/java/com/apple/foundationdb/relational/utils/TestSchemas.java
This PR fixes a minor bug that prevented the insertion of 
1. `struct with enum`: This was because of the fact that target `enum` descriptor was not getting propagated rightly during the message coercion.   
2. `array of struct with enum`: This was because of the fact that the array of structs was restricted to do promotion of struct, if needed.
=> Fix insertion of Struct with Enum

fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/metrics/RelationalMetric.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/PlanGenerator.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/metric/RecordLayerMetricCollectorTest.java
This PR adds a new metric to measure stats about obtaining a physical plan from the continuation. This pathway is not currently accounted for and hence, we do not have visibility of the time spent in "planning" a query but not in "looking up in cache". `EXECUTE CONTINUATION ...` follows this code path and accounts for all the requests that register the `GET_PLAN` event but does not register `CACHE_LOOKUP` event.
=> Add a metric to measure generate continued plan

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/MockedFDBDirectory.java
The source of the leaking data blocks has been found and fixed.
Added more tests to verify the leakage was fixed directly as well as an addition to the `LuceneIndexTestValidator` to get some additional coverage "for free" whenever we use it in other tests.
Resolves #3550
=> Fix for Lucene block leaks on file deletion

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationBaseBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildJoinedIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildRankIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildSumIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildUnnestedIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildValueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildVersionIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java
Deprecate `OnlineIndexer.stopOngoingOnlineIndexBuilds` and variants in favor of `blockIndexBuilds`
Resolves #3548
=> Deprecate synchronized indexing controls

fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/QueryPlan.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/ExplainTests.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/storage/BackingLocatableResolverStoreTest.java, fdb-relational-core/src/testFixtures/java/com/apple/foundationdb/relational/utils/ResultSetAssert.java
This PR adds two new columns, `PLAN_HASH` and `SERIALIZED_PLAN_COMPLEXITY`, to the `PLAN_CONTINUATION` struct in the result from EXPLAIN which contain the plan hash stored in the continuation and the complexity of the plan serialized within the continuation (if the continuation contains a compiled statement )respectively . 
The new columns are populated for EXPLAINs on an `EXECUTE CONTINUATION` statement and a regular SELECT statement that uses the `WITH CONTINUATION` clause.
=> Add serialized plan complexity and hash to the continuation info in EXPLAIN

.github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/teamscale_upload.yml, actions/teamscale-upload/action.yml
Add new jobs to the nightly flow to run standard tests and mixed-mode tests. This is primarily there so that we can upload coverage to teamscale. 
These new teamscale steps are set to continue-on-error, to make sure they are working correctly before impacting the nightly build.
I also extracted the teamscale upload into a separate action to decrease repetition, this is the biggest risk; if I messed this up, it could impact the post-pr teamscale upload.
=> Upload coverage from nightly builds

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByIndex.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingCommon.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingSubspaces.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationBaseBuilder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationConfig.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexing/IndexingHeartbeat.java, fdb-record-layer-core/src/main/proto/index_build.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMutualTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexingHeartbeatTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexing/IndexingHeartbeatLowLevelTest.java, gradle.properties
Each indexing session, for each index, will create a key-value heartbeat of the format:
```        [prefix, xid] -> [indexing-type, genesis time, heartbeat time] ```
Indexing session that are expected to be exclusive will throw an exception if another, active, session exists.
Motivation:
1. Represent the heartbeat in every index during multi target indexing (currently - only the master index has a sync lock)
2. Keep a heartbeat during mutual indexing, which can allow better automatic decision making
3. Decide about exclusiveness according to the indexing method (currently - user input)
With this change, the equivalent of a sync lock will be determined by the indexing type and cannot be set by the users. The index configuration function `setUseSynchronizedSession` will have no effect on …
=> Online Indexer: replace the synchronized runner with a heartbeat

.github/workflows/metrics_analysis.yml, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/GitMetricsFileFinder.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/MetricsDiffAnalyzer.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/MetricsInfo.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/MetricsStatistics.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlExecutionContext.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/queryconfigs/CheckExplainConfig.java, yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/MetricsDiffAnalyzerTest.java, yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/MetricsDiffIntegrationTest.java, yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/MetricsStatisticsTest.java, yaml-tests/src/test/resources/metrics-diff/metrics-diff-test-base.metrics.yaml, yaml-tests/src/test/resources/metrics-diff/metrics-diff-test-head.metrics.yaml, yaml-tests/src/test/resources/metrics-diff/metrics-outlier-test-base.metrics.yaml, yaml-tests/src/test/resources/metrics-diff/metrics-outlier-test-head.metrics.yaml, yaml-tests/src/test/resources/metrics-diff/test-base.metrics.yaml, yaml-tests/src/test/resources/metrics-diff/test-head.metrics.yaml, yaml-tests/src/test/resources/metrics-diff/test-new-queries.metrics.yaml, yaml-tests/yaml-tests.gradle
This adds an automatic tool to review metrics files. It should run as part of PRB and post back the results of computing the diff.
You can see a version of its sample output here: https://github.com/FoundationDB/fdb-record-layer/actions/runs/17975684135?pr=3620 That particular version was modified so that it would use `4.5.10.0` as the base branch. The extra queries there account for why there were so many identified in the analysis.
The basic structure of the report is:
1. A basic summary of the number of queries added, dropped, and changed
2. The number of new queries (per file)
3. A list of dropped queries
4. Statistics for query metric changes for queries that have modified their plans, along with a list of outlier queries with large regressions
5. The same for queries where only the …
=> Create tool to automate reviews of metrics files

.github/workflows/metrics_analysis.yml
This should be `pull`, singular, instead of `pulls`, plural. This is actually another thing I had correct in my test repo but that got copied over incorrectly in my haste.
I want to say that this is it, but of course, I thought that the last time as well.
=> Use reference name "pull/PR_NUMBER/head" to get PR head reference

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializerJCE.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializerTest.java
This fixes a regression that was introduced in https://github.com/FoundationDB/fdb-record-layer/pull/3522, which prevented an instance of `TransformedRecordSerializerJCE.Builder<>` to be reused if it was used to build an instance of a serializer with an encryption key provided instead of a `SerializationKeyManager`.
=> Allow TransformedRecordSerializerJCE.Builder to be reused

fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/Options.java, fdb-relational-api/src/testFixtures/java/com/apple/foundationdb/relational/utils/OptionsTestHelper.java, fdb-relational-core/src/main/antlr/RelationalParser.g4, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/AstNormalizer.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/OptionsUtils.java, fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/QueryPlan.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/JoinWithLimitTest.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/ExplainTests.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/ForceContinuationQueryTests.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/GroupByQueryTests.java, fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/QueryWithContinuationTest.java, fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/TypeConversion.java
This PR does a couple of things:
- removes the usage of `CONTINUATION_CONTAINS_COMPILED_STATEMENT` option in Connection and as a query option. 
- The option was, by default, set to true and is now true for all the requests to the engine.
- We still support `SELECT ... WITH CONTINUATION ...`, which could be removed separately after this work. Hence, it could happen that a query started with a non-serialized continuation, but has now on serialised continuation.
- JDBC driver still supports the option, for backward compatilibility. However, the current change always sets that to `TRUE` and rejects connections that have it set to `FALSE`. Once this is rolled out, we should probably stop failing on false and mark the option as deprecated in proto. Finally, we can stop setting the option and …
=> remove CONTINUATION_CONTAINS_COMPILED_STATEMENT usage

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/CompressedAndEncryptedSerializerState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializerState.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/properties/RecordLayerPropertyStorage.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/LuceneSerializer.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneSerializerTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryFailuresTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
… using the same serialization key manager as record serialization.
=> Make Lucene serialization able to encrypt, … 
