FoundationDB/fdb-record-layer

fdb-extensions/fdb-extensions.gradle, fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle, fdb-record-layer-core/fdb-record-layer-core.gradle, gradle/publishing.gradle
This takes the fix for #305 into master. It was added to the 2.4.35 branch in order to make sure we could publish from that branch, so now it's being taken into master as well.
=> Merge 2.4.35 branch into master

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolverTest.java
The idea behind this test is that it allocates a mapping from the directory layer, attempts to set a mapping with a different value, sees that it fails, then verifies that the forward and backwards mappings read are not modified from their original values. The failures came from the last assertion, we were assuming that the if we mapped `key -> value` that there would not be no reverse mapping from `value + 1` to anything. But for some runs the prefix string for the reverse directory cache happened to get mapped to `value + 1`. The fix is to now consider both cases we assert that either the reverse mapping does not exist OR it maps to some other key.
=> Fix flaky setMapping test

build.gradle, fdb-record-layer-core/fdb-record-layer-core.gradle, gradle/wrapper/gradle-wrapper.properties
From 4.8 to 5.2
* Missing `testAnnotationProcessor`.
* Need newer spotbugs plugin.
=> Resolves #252: Upgrade Gradle wrapper

docs/ReleaseNotes.md
=> Fixes #391: Release 2.5.44.0 missing release notes

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/RankedSet.java, fdb-extensions/src/test/java/com/apple/foundationdb/async/RankedSetTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/FunctionNames.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankedSetIndexHelper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RankIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/LeaderboardIndexTest.java
Resolves #425: RankedSet operation to return rank for values even when not present
Resolves #426: Aggregate functions to return rank for values
=> Ranked set additions for getting rank for values not present in the set

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java
ReleaseNotes conflicted. I went with the version for 2.5.44.0 notes that was in master, rather than the
one I added on the 2.5.44 branch.
Also, had to undo the change to gradle.properties
=> Merge 2.5.44

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/MergeCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/ProbableIntersectionCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnorderedUnionCursor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/FDBRecordStoreLimitTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/limits/FDBRecordStoreScanLimitTest.java
This gets the fix for #437 onto master and tidies up the release notes.
=> Merge 2.5.44.15 into master

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java
This just exposes it in the simplest way.
=> Resolves #485: There is no way to add a FormerIndex directly

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
Resolves #480
This adds a new @Nullable parameter that can be provided to runAsync
that will get included in "Retrying FDB Exception" or
"Lessening limit of online index build"
=> OnlineIndexer logs what it was trying to build on commit failure

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java
This picks up the change in #513.
=> Merge 2.5.54 patch branch into master.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java
=> Add FDBRecordStore.getAllIndexStates

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java
Since there might be existing stores in this state, also need checkVersion to properly recognize them.
=> Fixes #565: A new store with metaDataVersion = 0 doesn't save that

docs/ReleaseNotes.md
Sorry, I forgot to add a release note in #574
=> Add release note for fixing #573

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/SizeStatisticsCollectorCursor.java
=> Avoid caching outer class state in SizeStatisticsCollectorCursorContinuation

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Key.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/FieldKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/KeyExpressionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreNullQueryTest.java
Merge the changes from #653 into master.
From the original PR against the 2.7.73 release branch:
> This reverts commit 85b09f1.
> This is a temporary fix until all the issues with #647 can be worked through.
=> Merge 2.7.73.20 into master

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/SizeStatisticsCollectorCursor.java
This includes the fix for #656, which was placed on to the 2.7.73 branch. This ensures master now has this fix as well.
=> Merge 2.7.73.21 into master

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/StoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoredSizes.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SplitHelper.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseTest.java, fdb-record-layer-core/src/test/resources/log4j2-test.properties
This merges the changes from version 2.7.73.22 into master. This is mostly #672 and #673.
=> Merge 2.7.73.22 into master

gradle.properties
It appears that we were not using anything that was removed, as everything seems to still be working. I have updated the version, but I have not used any new features.
This resolves #714.
=> Resolves #714: Upgrade to JUnit 5.5

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Field.java
Also fix release notes, which had the prior signature.
=> New enum needs to be public.

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RecordTypeKeyTest.java
This adds test to demonstrate a deficiency in the planner pointed out in #744. The failing tests are disabled here so that they do not break the build but so that (a) there is a record in the code of the kind of cases that are broken here and (b) once the problem is fixed that PR can just enable these tests. This also makes the RecordTypeKeyTest extend from `RecordQueryTestBase` so that the `@DualPlannerTest` annotations can be applied, though it does not actually make any tests use the new planner (as they appear to not work yet with the way the planner is on master).
I'm not actually sure this should be merged, but I thought getting my tests for #744 out there would be useful (ish).
=> Does not fix #744: Record Type comparison not included as able to satisfy a sort

.idea/checkstyle-idea.xml
Due to https://github.com/jshiell/checkstyle-idea/commit/e313ae32c44a2b47b787499a591fcc81a9de4738
=> Switch from PRJ_DIR to PROJECT_DIR

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/text/DefaultTextTokenizer.java
Small fix to reuse the Pattern and attempt to reset the matcher vs. creating new for each iteration.
=> Fixes: #845: Make Regex Pattern Static and reuse matcher in DefaultTextTokenizer

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java
This should be harmless enough even if it turns out not to be needed.
=> Split out an advanced form of planCoveringAggregateIndex

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/clientlog/KeySpaceCountTree.java
Needs to be moved into `IndexMaintainerFactory`, but good enough for most types now.
=> Quick and dirty index field resolution.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlannerConfiguration.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/planning/InExtractor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/RecordQueryPlannerConfigurationTest.java
This merges the changes on the 2.8.102 patch branch onto the 2.8.104 patch branch.
=> Merge 2.8.102.24 into 2.8.104

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlannerConfiguration.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/planning/InExtractor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/RecordQueryPlannerConfigurationTest.java
This gets master up to date with the 2.8.102 and 2.8.104 branches.
=> Merge 2.8.104.25 into master

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/async/RankedSet.java, fdb-extensions/src/test/java/com/apple/foundationdb/async/RankedSetTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexOptions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexMaintainerFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankedSetIndexHelper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RankIndexTest.java
=> Ranked multiset backport

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankedSetHashFunctions.java
=> Resolves #869: Expose random hash as an index option

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java
This merges the changes on the 2.8.102 patch branch onto the 2.8.104 patch branch.
=> Merge 2.8.102.27 to 2.8.104

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java
This merges the changes on the 2.8.102.26 and 2.8.104.28 patch releases into `master`.
=> Merge 2.8.104.28 to master

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java
This merges the changes on the 2.8.104 patch branch onto the 2.8.110 patch branch.
=> Merge 2.8.104.28 to 2.8.110

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreOpeningTest.java
This merges in the fix for #941 from the 2.8.118 branch onto master as well as fixes up the release notes, etc.
=> Merge 2.8.118.30 into master

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
Hotspots while updating 3K records.
=> Fixes #960 Meta Conflict Range Additions hotspot during large operations.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/FunctionNames.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexOptions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/IndexTypes.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/BitmapValueIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/BitmapValueIndexMaintainerFactory.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/BitmapValueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/RankIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/VersionIndexTest.java
Also moves a couple of index-type-specific tests into the child package, since I was adding another one there in the main commit.
=> Resolves #1010: Bitmap value indexes

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/visitor/FilterVisitor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCoveringIndexQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSortQueryIndexSelectionTest.java
Includes update to a existing test that now does the filter from the covering index.
=> Resolves #1030: FilterVisitor could support NestedField

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpression.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryHashTest.java
=> Resolve #1066

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/CascadesCostModel.java
=> Resolve #1148

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FunctionKeyIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/BitmapValueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBAndQueryToIntersectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCoveringIndexQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCrossRecordQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBFilterCoalescingQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBFullTextQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBMultiFieldIndexSelectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedFieldQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRepeatedFieldQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRestrictedIndexQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBReturnedRecordLimitQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSortQueryIndexSelectionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryPlanHashTest.java
=> Resolve #1141

docs/ReleaseNotes.md, fdb-record-layer-core/fdb-record-layer-core.gradle, gradle.properties
Updates dependency versions to be more modern.
=> Resolves #1193: Dependency updates for 3.0

build.gradle, gradle/coverage.gradle, gradle/proto.gradle, gradle/testing.gradle, settings.gradle
Fix errors from --warning-mode=all.
This is to prepare for Gradle 6.
=> Update gradle plugin versions.

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/QueryPlanInfo.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/QueryPlanResult.java
=> Resolve #1207 - add toString to `QueryPlanResult`

fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/KeyRange.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/IllegalContinuationAccessChecker.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Key.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/text/DefaultTextTokenizer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/KeySpacePath.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/QueryPlanInfoKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/AliasMap.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/ExpansionVisitor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/ExpressionRefTraversal.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/MessageValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/debug/package-info.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/predicates/AndPredicate.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/predicates/package-info.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/util/HashUtils.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/common/text/PrefixTextTokenizer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerConflictsTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/QueryPlanCursorTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreIndexScanPreferenceTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/predicates/match/PredicateMatchers.java, fdb-record-layer-spatial/src/test/java/com/apple/foundationdb/record/spatial/geophile/GeophileQueryTest.java, gradle/check.gradle, gradle/codequality/checkstyle-mandatory.xml, gradle/codequality/checkstyle.xml
This upgrades checkstyle to the newest version, and then makes fixes to the checkstyle configuration files as well as fixes rules violations that the checker now finds.
This resolves #1225.
=> Resolves #1225: Upgrade Checkstyle to 8.41

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlannableIndexTypes.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexQueryPlan.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
- Nested fields
- hasDuplicates
- plan merging
- expansion of fdb components into complex Lucene strings 
- record cursor fix for primary key component positions
- record cursor handling of nested fields.
=> adding nested fields to lucene indexing functionality

build/Dockerfile.build, build/Dockerfile.fdbserver, build/docker-compose.yaml, docs/ReleaseNotes.md, fdb-extensions/src/test/java/com/apple/foundationdb/FDBTestBase.java, fdb-extensions/src/test/java/com/apple/foundationdb/map/BunchedMapScanTest.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedReadTransaction.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedTransaction.java, gradle.properties
This is a RecordLayer 3.0 version of PR #1202
=> Upgrade FDB to 6.3.12 in RecordLayer 3.0

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseFactory.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java
Record Layer 3.0 version of PR #1202
=> Enable Multi-threaded client for RecordLayer 3

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpression.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryHashTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryPlanHashTest.java
Ignore value for planHash and queryHash in LiteralKeyExpression
=> Resolves #1273

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/StoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexMaintainer.java
a RecordLayer 3.0 version of PR #1261
=> Instrument FDB calls for RecordLayer 3

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlannerConfiguration.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/ScanComparisons.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/planning/InExtractor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryInUnionPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/explain/NodeInfo.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/matchers/RecordQueryPlanMatchers.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java
Not supported by new planner yet.
=> Resolves #1286: IN join with Union instead of concat

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/DataAccessRule.java
Fixes #1324 
Typo in DataAccessRule.comparisonKey
=> Fixes #1324

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java
Made some changes in scrubbingPolicy
=> Resolve 1345: Index scrubber: log warnings when repair is not allowed

examples/src/main/java/com/apple/foundationdb/record/sample/Main.java
Add a couple of missing join()'s.
Also adopt more consistent style as noted https://github.com/FoundationDB/fdb-record-layer/pull/1350#discussion_r681694311
=> Fixes #1349: Example doesn't seem to work

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/rules/ImplementInUnionRule.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java
This is the port of the `resolves #1369: relax restrictions enforced in ImplementInUnionRule` PR to a branch off of `3.0.209`
=> resolves #1369: relax restrictions enforced in ImplementInUnionRule

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursor.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java
Nice Utility to add if someone would like to use Stream interface.
=> Resolves #1409: Add the ability to get a Stream<T> from a RecordCursor<T>

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/QueryPlanInfo.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/QueryPlanResult.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/CascadesPlanner.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/QueryPlanInfoTest.java
make Make QueryPlanResult and QueryPlanInfo immutable:
- Create builder for QueryPlanInfo
- Remove setter methods from QueryPlanInfo
- Add constructor with PlanInfo to QueryPlanResult
=> Resolve #1456 : Make QueryPlanResult and QueryPlanInfo immutable.

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAnalyzerFactory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAnalyzerRegistry.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAnalyzerRegistryImpl.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainerFactory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/ngram/NgramAnalyzer.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
…query, and use standard analyzer on query time for ngram index
=> Resolves #1486: LuceneIndexMaintainer should have 2 separate analyzers for indexing time and query time

fdb-extensions/src/main/java/com/apple/foundationdb/util/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/IndexScanType.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/QueryPlanUtils.java, fdb-record-layer-core/src/main/proto/record_cursor.proto, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexQueryPlan.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneSpellcheckRecordCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneSpellcheckResultCursor.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
This is based off Yizuo's commits and includes those as well. I will continue to rebase what he does on top.
=> Spellcheck2

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java
Add declareValueIndex to ScrubbingPolicy's builder.
=> Allow scrubbing of non-"value" indexes (#1551)

fdb-record-layer-lucene/gradle.properties, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/IndexWriterCommitCheckAsync.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCodec.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundReader.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedSegmentInfoFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedAnalyzingInfixSuggester.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/ngram/NgramAnalyzer.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBLuceneTestIndex.java
This is an upgrade of the record layer to Lucene 8.11.1.
=> Resolves #1556: Upgrade Lucene to 8.11.1 from 7.7.2

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCodec.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPostingsFormat.java, fdb-record-layer-lucene/src/main/java/org/apache/lucene/codecs/lucene84/LuceneOptimizedPostingsReader.java, fdb-record-layer-lucene/src/main/java/org/apache/lucene/codecs/lucene84/package-info.java, gradle/codequality/suppressions.xml
8.11.1 re-introduced checksums that we had attempted to remove in our prior version.
=> Lucene 8.11.1 re-introduced a lot of checksum issues #1567

fdb-record-layer-lucene/src/main/java/org/apache/lucene/codecs/lucene84/LuceneOptimizedPostingsReader.java
Attempts to open inputs in parallel (asynchronous inside the input) before accessing the input in the checkHeader calls (blocking).
=> Make LuceneOptimizedPostingsReader less sequential #1591

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java
=> Remove Hotspot during byte reading in FDBIndexInput #1619

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java
Also adds missing `@Nullable` annotations, which help make the contract more clear.
=> Fixes #1668: Unsupported comparisons cause exception for Lucene index

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ParserContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Scopes.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ExistsValue.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/ArithmeticValueTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/BooleanValueTest.java
also remove side-effect from ExistsValue.
=> Refactor ParserContext

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBFilterCoalescingQueryTest.java
This exposes that issue #2 works with Cascades.
=> Update more of FDBFilterCoalescingTest to use DualPlannerTest.

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/VersionIndexMaintainer.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/VersionIndexTest.java
Enable remote fetch for version index.
Add tests.
=> Resolve #1707: Enable index remote fetch for version index

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/AvailableFields.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanOrderingKey.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanWithOrderingKey.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/PlanWithStoredFields.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/visitor/RecordQueryPlannerSubstitutionVisitor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexQueryPlan.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePlanner.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java
=> Resolves #1652: Lucene plans should expose available fields

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java
=> ReadByte and WriteByte hotspot when determining trace logging... #1775

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/IndexKeyValueToPartialRecord.java
=> FieldCopier.copy hotspots during large covered index reads #1771

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java
Small nit but on a few profiles they burn cycles.
=> Remove seek and length trace logging #1786

fdb-extensions/src/main/java/com/apple/foundationdb/clientlog/FDBClientLogEvents.java
Changes per https://github.com/apple/foundationdb/commit/f4b0de7a56f3e5ebf76384d338489b6f8d34b03f, which updates more or less equivalent Python code.
=> Resolves #1794: FDBClientLogEvents needs to be updated for 7.x

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/ContextRestoringExecutor.java
=> ContextRestoringExecutor Hotspots during beforeTask and endTask #1800

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/clientlog/FDBClientLogEvents.java
per [ecccfd0868cea448e3c6e457dbf9e7155cacc3cb](https://github.com/apple/foundationdb/commit/ecccfd0868cea448e3c6e457dbf9e7155cacc3cb) and [57f5ca2522c3a9b94bbfecdd97cad2799948779f](https://github.com/apple/foundationdb/commit/57f5ca2522c3a9b94bbfecdd97cad2799948779f).
=> Update client event parsing to handle tenant

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/OrdinalFieldValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/QuantifiedColumnValue.java
* For repeated field, it returns empty array if not set.
=> Resolve #1718: Return null when a field is not set

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java
See https://github.com/FoundationDB/fdb-record-layer/pull/1823#discussion_r956450035
=> Resolves #1830: Make FDBRecordContext remember its config

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java
=> Resolve #1798: Emit a different KPI for each reason of index rebuilds

.idea/gradle.xml, build.gradle, docs/ReleaseNotes.md, fdb-record-layer-jmh/fdb-record-layer-jmh.gradle, fdb-record-layer-jmh/src/jmh/java/com/apple/foundationdb/record/benchmark/BasicBenchmark.java, fdb-record-layer-jmh/src/jmh/java/com/apple/foundationdb/record/benchmark/BenchmarkMetaData.java, fdb-record-layer-jmh/src/jmh/java/com/apple/foundationdb/record/benchmark/BenchmarkRecordStore.java, fdb-record-layer-jmh/src/jmh/java/com/apple/foundationdb/record/benchmark/BenchmarkRecordStores.java, fdb-record-layer-jmh/src/jmh/java/com/apple/foundationdb/record/benchmark/BenchmarkTimer.java, fdb-record-layer-jmh/src/jmh/java/com/apple/foundationdb/record/benchmark/LoadBenchmark.java, fdb-record-layer-jmh/src/jmh/java/com/apple/foundationdb/record/benchmark/PlannerBenchmark.java, fdb-record-layer-jmh/src/jmh/java/com/apple/foundationdb/record/benchmark/RankBenchmark.java, fdb-record-layer-jmh/src/jmh/java/com/apple/foundationdb/record/benchmark/package-info.java, fdb-record-layer-jmh/src/jmh/proto/benchmark_records_1.proto, settings.gradle
Create a JMH subproject with the outline of some benchmarks.
Reactivates #1157.
=> Resolves #1156: Improve infrastructure for FDBRecordStorePerformanceTest

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java
=> Fixing issue where indexes are lost when serializing Synthetic record types

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/PartialOrder.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/TopologicalSort.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/KeyPart.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Ordering.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/RequestedOrdering.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/Debugger.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/DistinctRecordsProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/OrderingProperty.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/AbstractDataAccessRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementDistinctUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementInJoinRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementInUnionRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementStreamingAggregationRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/RemoveSortRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/QuantifiedObjectValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/CompensateRecordConstructorRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/MatchOrCompensateFieldValueRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/MatchValueRule.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/PullUpValueRuleSet.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryIntersectionPlan.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryPlanFullySortedTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/OrderingTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/DebuggerWithSymbolTables.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/PlannerRepl.java
Note that this PR contains #1840.
=> Resolves #1618: orderings as partially-ordered sets

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordVersion.java
=> IDE was unhappy with Nonnull and Nullable in a couple of spots #1881

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedReadTransaction.java
Account for FDBStoreTimer.Counts.BYTES_READ in remote fetch
=> Resolve #1889

docker-local/fdb-build.sh
Add a script to automate the process of compiling a local version of FDB for use by record layer
=> Automate the build process for local version of FDB

fdb-record-layer-core/src/main/java-proto2/com/google/protobuf/ZeroCopyByteString.java, fdb-record-layer-core/src/main/java-proto2/com/google/protobuf/package-info.java, fdb-record-layer-core/src/main/java-proto3/com/google/protobuf/ZeroCopyByteString.java, fdb-record-layer-core/src/main/java-proto3/com/google/protobuf/package-info.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/FlatMapPipelinedCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/OrElseCursor.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/FormerIndex.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/Index.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/TupleFieldsHelper.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/text/TextCollatorRegistryJRE.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByIndex.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/SortedRecordSerializer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/BloomFilterCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/IntersectionCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/UnionCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/layers/interning/StringInterningLayer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboard.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/IndexKeyValueToPartialRecord.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/ComposedBitmapIndexContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/planning/BindingFunctions.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQuerySelectorPlan.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/FileSortCursorContinuation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/FileSorter.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/sorting/MemorySortCursorContinuation.java, fdb-record-layer-icu/src/main/java/com/apple/foundationdb/record/icu/TextCollatorRegistryICU.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneCursorContinuation.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBLuceneFileReference.java
Small nit but see a lot of object creation in production.
=> Consider tighter protobuf performance by removing array copies #1921

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordConstructorValue.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordConstructorValueTest.java
…pCopyIfNeeded() in RecordConstructorValue)
=> add support for enum in deepCopyIfNeeded() in RecordConstructorValue

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteResultCursor.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexValidator.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexValidatorTest.java
=> Validate lucene index autocomplete excluded fields

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
The refactoring in #2037 removed the HTML markup that used to be the default highlighting with the rather inconvenient message rebuilding. But left some calls to `fullTextSearch` with `highlight` on. Add some simpler markup and a new comparison using it for those tests.
Note that ngram index highlighting regressed with those changes, so some highlights are missing.
=> Put back actual testing of highlighting.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/runners/TransactionalRunnerTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/synthetic/SyntheticRecordPlannerTest.java
Addresses https://github.com/FoundationDB/fdb-record-layer/issues/2099
=> Ensure that Synthetic Record Types are not updated if the underlying indexes are all disabled

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java
This adds a new unit test to make sure that if an index is recreated with a new subspace key and the old key is left with a `FormerIndex`, then the old index will be cleared out at `checkVersion` time, and operations will use the new subspace key. This ensures that when an index is dropped and recreated in this way, we don't try and use old data for the new index.
This resolves #2123.
=> Resolves #2123: Add unit tests around recreating indexes with new subspace keys

docs/ReleaseNotes.md, fdb-extensions/src/main/java/com/apple/foundationdb/system/SystemKeyspace.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/TestKeySpace.java
* Resolves #2115: Add throttling tags to context config.
* Resolves #2116: Add optional conflict tracking to context config.
=> A couple of additions to FDBRecordContextConfig

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordCursor.java
Test coverage in FDBLuceneQueryTest.covering().  This is just a performance optimization to not load all stored values unless query requires them.
=> LuceneRecordCursor should only load stored values needed for query #2145

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCodec.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedDocValuesFormat.java
Removes Fetches during a simple insert when the segment readers init...
=> Make DocValuesFormat lazy #2161

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
Significant Performance Issue...
=> Issue were info logging was switched on vs. trace... #2173

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedIndexInput.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedIndexOutput.java
This is just a precursor so I can add a supplier and a close when incorporating a custom FieldInfo..
=> LuceneOptimizedWrappedDirectory needs to allow for extension #2180

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/TextIndexTestUtils.java, fdb-record-layer-core/src/test/proto/test_records_text.proto, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimized60FieldInfosFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCodec.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedCompoundReader.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedFieldInfosFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBLuceneFileReference.java, fdb-record-layer-lucene/src/main/proto/lucene_file_system.proto, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
Cherry pick #2214 into 390-branch
=> Resolve #2213: Reintroduce #2182 (#2214)

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java
LuceneOptimizedCodec is currently created per indexWriter.
=> LuceneOptimizedCodec should be static, wrong scope. #2220

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedFieldInfosFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedWrappedIndexInput.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
Reads from 100K email reference set dropped 100K.  Seems like a significant win.
=> Add cache for schema information #2190

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlannerConfiguration.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VariadicFunctionValue.java
Fix a couple of issues that caused local build to fail.
=> Resolve #2228: Fix a couple of build issues

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedFieldInfosFormat.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexInput.java
This is a cherry-pick of the two commits in #2235 onto a patch release branch for 3.3.396.0
=> Resolves: #2234

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ConditionSelectorValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/PickValue.java
This introduces `ConditionSelectorValue` which can be used in conjunction with `PickValue` to implement features such as SQL `case-when`
=> Add `ConditionSelectorValue`.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PromoteValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VariadicFunctionValue.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/VariadicFunctionValueTest.java
=> Resolves #2242: COALESCE does not work with non-scalar types

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/sorting/RecordQueryDamPlan.java
Change signature from #2129 to match #2128.
=> Fix merge skew in Dam plan addition.

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestUtils.java
Create a reproducing test for the Lucene thread deadlock
=> Resolve #2234: Fix readSchema deadlock.

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/MessageTransformationTest.java
=> Fix coerceArray to work with list of primitives 

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/TestKeySpace.java, fdb-record-layer-lucene/fdb-record-layer-lucene.gradle, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/LuceneScaleTest.java
This new test facilitates testing performance locally, outputting various metrics on operations to a csv as the size of the index increases.
=> Introduce a LuceneScaleTest for testing Lucene performance locally

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
=> set update pipeline size == 1

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBModificationQueryTest.java
=> RecordQueryAbstractDataModificationPlan does not produce stable hash with CoercionTrieNode

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/OfTypeValue.java
=> Fixes #2434: support record type in OfTypeValue

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java
This expands randomizedRepartitionTest to toggle whether it has OPTIMIZED_STORED_FIELDS_FORMAT_ENABLED and
PRIMARY_KEY_SEGMENT_INDEX_ENABLED.
It adds validation that the primaryKey-segment index is consistent and also uses those validations in two other tests with the primaryKey-segment index.
=> Add tests of rebalancing partitions with other options

docs/ReleaseNotes.md
This reverts commit 359af2fbf8152c152700911ec0442fd446c06993.
=> Revert "Release notes updated for version 3.4.0.0"

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
=> Add metric for Lucene number of file refs and their size

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneLogMessageKeys.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java
This feels specific enough, and may be helpful if we ever decide to add partitioning to any other index type.
=> Resolves #2614: LuceneLogMessageKeys.PARTITION -> INDEX_PARTITION

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyOpenerTest.java
This updates `LazyCloseableTest.testOpensLazilyExactlyOnceThreaded` (and its equivalent test in `LazyOpenerTest`) so that they no longer rely on `Suppliers.parallel` to schedule tasks in multiple threads. Instead, it uses a new helper method which will spawn one thread for each `Supplier`. The helper method also uses a `CountDownLatch` to ensure that we do not start to execute tasks until all of the threads have been spawned. This ensures that there are as many concurrent accesses to the `LazyOpener`/`LazyCloseable` as possible during the test, though Java's thread scheduling algorithm remains non-deterministic.
This fixes #2449.
=> Fixes #2449: LazyCloseableTest.testOpensLazilyExactlyOnceThreaded intermittently fails with: collection size <8> was less than <10>

fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCollateQueryTest.java, fdb-record-layer-icu/gradle.properties, fdb-record-layer-icu/src/test/java/com/apple/foundationdb/record/icu/FDBCollateICUQueryTest.java
Also bumps the ICU4J dependency a little bit, although I don't believe that is necessary.
=> Add a test of ICU numeric collation.

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java
=> Resolve #2636: AgilityContext: add applyInRecoveryPath test

docs/ReleaseNotes.md, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreConcurrentTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTestBase.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBInQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedRepeatedQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBOrQueryToUnionTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBPermutedMinMaxQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreRepeatedQueryTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/QueryPlanFullySortedTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/PlanComplexityExceededTest.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockFactory.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenePrimaryKeySegmentIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneQueryIntegrationTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneStoredFieldsTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/FDBLuceneHighlightingTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/LuceneLocaleTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/highlight/LuceneScaleTest.java
…ransaction merges are ongoing
- added 4 tests to `LuceneIndexTest`
=> RESOLVES #2701: Test FDBDirectory consistency while cross-transaction merges are ongoing

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordStoreState.java
(Similar functions already exist in FDBRecrodStore)
=> Resolve #2718: Add isScannable(), isReadableUniquePending() to RecordStoreState

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java
This commits a version of the summary comment from #2706 into the code, as requested during code review: https://github.com/FoundationDB/fdb-record-layer/pull/2706#pullrequestreview-2046477132
There are some slight differences, in that the original summary column attempted to explain what the code was trying to do and how it was failing, whereas the comment comitted here only contains information about what the code _currently_ does (which, is also what it's supposed to do, or at least that's the idea).
=> Commit comment from #2706: Permuted index can mis-assign fields in IndexKeyValueToPartialRecord

docs/ReleaseNotes.md
Fix release notes issue caused by incorrect build triggered
=> Fix Release notes

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java
Just to make sure it doesn't break
=> Add a lucene test that saves all possible unicode characters

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
Fix flaky test: break commit loop to smaller batches.
=> resolve #2756: fix test

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
Attempt to cause a conflict and abandon a file lock. 
The test is failing for 3.4.485.0
=> Resolve #2731: Reproduce abandoned FileLock due to conflict issue

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneLockFailureTest.java
Followup from #2730 -- this changes the test to commit the lock in a separate transaction.
This also updates testUpdateDocument to do the update in a separate transaction to keep the tests consistent and more correctly align with expected usages.
=> Change LuceneLockFailureTest.testDeleteAll to use more transactions

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexValidator.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRepartitionPlanner.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneRepartitionPlannerTest.java
- when a partition falls below the low watermark, and if one or both of its neighboring partitions have capacity to absorb, it will be merged into them.
This is a re-opening of #2740 which had some git history issues.
=> RESOLVES #2739: Merge partitions when they become too small

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRepartitionPlanner.java
- added a check to array size
- fixed sort order in query for oldest/newest docs
=> FIXES #2784: Fix out of bound exception with repartitioning

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ConstantObjectValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/PromoteValue.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/ConstantObjectValueTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/TypeTest.java
=> Fixes #2806: add Support for nested DynamicMessage in ConstantObjectValue

fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java
This simplifies the implementation, as noted in PR #2822
=> Simplify MoreAsyncUtil.combineAndFailFast

fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
Sleeping for a second between tests didn't seem to make the tests behave well, trying to slow down the document generation used in the most expensive tests.
Hopefully this will make #2842 no longer a problem.
=> Attempt to reduce FDB load during Lucene tests

docs/ReleaseNotes.md, fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java
This adds a breakdown of the time, plus a metrics diff for the store timer.
=> Resolves #2886: Add timings to "Repartitioned records" log

fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteQueryClause.java
This will hopefull help us root cause why this method is taking so long, or rule that this this is the method taking so long.
=> Resolves #2892: Log timing of LuceneAutoCompleteQueryClause.bind

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/DimensionsKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/QueryToKeyMatcher.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ComparisonRanges.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/MultidimensionalIndexTestBase.java, fdb-record-layer-core/src/test/proto/test_records_multidimensional.proto
=> resolves #2846

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/TreeLike.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/TreeLikeTest.java
=> Add `TreeLike#replaceLeavesMaybe` overload that does not pass new leaves to customer

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/CollateFunctionKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/text/TextCollatorRegistry.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/text/TextCollatorRegistryJRE.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/QueryKeyExpression.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/EncapsulationFunction.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/SemanticException.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/CollateValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/FromOrderedBytesValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RelOpValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ToOrderedBytesValue.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/ComparisonCompensation.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/CompensateToOrderedBytesValueRule.java, fdb-record-layer-core/src/main/proto/record_query_plan.proto, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBCollateQueryTest.java, fdb-record-layer-icu/src/main/java/com/apple/foundationdb/record/icu/CollateValueICU.java, fdb-record-layer-icu/src/main/java/com/apple/foundationdb/record/icu/TextCollatorRegistryICU.java, fdb-record-layer-icu/src/test/java/com/apple/foundationdb/record/icu/FDBCollateICUQueryTest.java
=> Implement Value for the collate_{jre,icu} functions

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java
This throttle information snapshot may help debugging issues.
=> Resolve #2946: indexer: Add information to "build index online" log message

docs/ReleaseNotes.md, fdb-extensions/src/test/java/com/apple/test/Tags.java, fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java
Add longer timeout to test that sometimes fail
Test will now only run in Nightly build
=> Resolve #2909: Add longer timeout to test

docs/ReleaseNotes.md, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexScrubbing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexScrubbingTools.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/ValueIndexMaintainer.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/ValueIndexScrubbingToolsDangling.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/ValueIndexScrubbingToolsMissing.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexing/IndexingRangeSet.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreUniqueIndexTest.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java
Create a generic index scrubbing that uses specific scrubbing tools from the index maintainers
=> Resolve #2984: Associate index scrubbing with index maintainers

docs/ReleaseNotes.md, fdb-relational-grpc/fdb-relational-grpc.gradle, fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalResultSetFacade.java, fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalRpcContinuation.java, fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/TypeConversion.java, fdb-relational-grpc/src/main/proto/grpc/relational/jdbc/v1/continuation.proto, fdb-relational-grpc/src/main/proto/grpc/relational/jdbc/v1/result_set.proto, fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/AbstractMockResultSet.java, fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/MockContinuation.java, fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/MockResultSet.java, fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/MockResultSetMetadata.java, fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/MockResultSetRow.java, fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/ProtobufConversionTest.java, fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/ResultSetContinuationTest.java, fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/TestUtils.java, fdb-relational-server/fdb-relational-server.gradle, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/Command.java, yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryConfig.java, yaml-tests/src/test/java/JDBCYamlIntegrationTests.java, yaml-tests/src/test/resources/deprecated-fields-tests-proto.yamsql
Create a branch from the 4.0.559.0 tag with additional changes needed for additional testing of the 559 release.
=> 4.0.559 release branch

build/commit_yamsql_updates.py
This is a simpler output that is easier to process I also added exception handling so you can see the output if the diff fails
=> Use git diff instead of git status to determine if there are changes

gradle/check.gradle, gradle/libs.versions.toml
TODO check SpotBugs release notes: https://github.com/spotbugs/spotbugs/releases
=> Bump spotbugs gradle plugin from 4.6.1 to 6.1.3

fdb-relational-cli/src/test/java/com/apple/foundationdb/relational/cli/SQLLineTest.java
The previous code called `SqlLine.main` which would call `System.exit` once SqlLine finished processing, which would mean that JUnit wouldn't get any result back, and the test would be marked as ignored.
This doesn't seem like great design from the gradle perspective. During the rework, I also discovered that:
1. If you create the `SqlLine` object, you can change the `OutputStream` it uses (and error), so you don't need to change system out, or err.
2. The driver provided was wrong (it is `JDBCRelationalDriver`, not `JDBCEmbedDriver`)
3. the url was wrong (it's `jdbc:relational` not `jdbc:embed`, and you need three / before the database, not 1)
4. it missed the `-` before the `-e` in the argument list
Note: I thought about adding an interactive test, where it runs multiple statements, but …
=> Rework SqlLineTest so that it actually interacts with the database

gradle/testing.gradle
This fixes failing mixedModeTest gradle task
=> Fix getMixedModeVersion() to match display name

fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingSubspaces.java, fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexing/IndexingRangeSet.java, fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java
Resolve #3315
There where leftover requested changes in PR #3298 that are addressed here
=> Extra cleanup for the index scrubbing code

docs/sphinx/source/ReleaseNotes.md
The cherry-pick was not clean, so I just copied the section over.
=> Bring in 4.3.3.1 release notes

fdb-relational-jdbc/src/test/java/com/apple/foundationdb/relational/jdbc/JDBCAutoCommitTest.java, fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/jdbc/v1/TransactionRequestHandler.java
This changes the transactional logic to correctly handle mutations
Fixes: #3475
=> Fix transactional insert throwing No Value Present in server
